# Import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Mount drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Thiết lập để hiển thị tất cả dòng và cột dataframe

In [ ]:
pd.set_option('display.max_rows', None)  # Hiển thị tất cả các dòng
pd.set_option('display.max_columns', None)  # Hiển thị tất cả các cột

# Đọc & xử lý dữ liệu

In [ ]:
data_path  = "/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/EDA"

In [ ]:
# Load dữ liệu
df = pd.read_excel(data_path + "/04.xeploaiav_EDA.xlsx") # Có thể thay đổi theo shortcut trên drive

In [ ]:
# Bỏ các ký tự đặc biệt, chữ thường, xóa khoảng trắng
for column in df.select_dtypes(include=['object']).columns:
  if column != 'mssv':
    df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%]", '', regex=True)

# Kiểm tra dữ liệu bị khuyết

In [ ]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv         6
total        6
mamh       201
ghichu    4803
dtype: int64

In [ ]:
# Tỷ lệ giá trị thiếu
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)
print("Tỷ lệ giá trị thiếu (%):")
print(missing_percentage)

Tỷ lệ giá trị thiếu (%):
ghichu    75.649709
mamh       3.165853
mssv       0.094503
total      0.094503
dtype: float64

In [ ]:
# Kiểm tra số dòng chứa giá trị null
num_null_rows = df.isnull().any(axis=1).sum()
print(f"Số dòng chứa giá trị null: {num_null_rows}")

Số dòng chứa giá trị null: 4810

In [ ]:
# Lọc các dòng có chứa giá trị null
rows_with_null = df[df.isnull().any(axis=1)]
print(rows_with_null)

                                          mssv  total    mamh          ghichu
0     DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ   15.0     NaN             NaN
1     336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ   15.0     NaN             NaN
2     67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e   16.0     NaN             NaN
3     387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN   16.0     NaN             NaN
4     13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM   18.0     NaN             NaN
5     AD5DDB61XPvAibaEXe97wmuqTYuV7bFPojsU1F+x   18.0     NaN             NaN
6     EBC55C2BXPvAibaEXe/7YVAxOsMwOk0EasYVdFSG   18.0     NaN             NaN
7     31656E5EXPvAibaEXe9N+b7C2VGPszP5c8rfamtp   18.0     NaN             NaN
8     CBB55F72XPvAibaEXe9Hp2TeoSwCGX/R/AU50aAF   19.0     NaN             NaN
9     40D2257DXPvAibaEXe9Hp2TeoSwCGTMp/uHWnnOo   19.0     NaN             NaN
10    CB6377B6XPvAibaEXe8808q51BnmQgFXOVlspk8F   20.0     NaN             NaN
11    1C5409B8XPvAibaEXe+/1KYXP+fweAeOyBmRMHFS   20.0     NaN             NaN
12    09DAA20BXPvAibaEXe8cJKtXZaLmvUsH6H9yaOrj   20.0     NaN             NaN
13    D3C8FCBFXPvAibaEXe9uaaZ/YedHVE2vFI3CwdF0   20.0     NaN             NaN
14    E16A784CXPvAibaEXe96K1aB3B4cKVqj15x8J3Fa   22.0     NaN             NaN
15    D9987866XPvAibaEXe+5AEinM7he3nNXvaIkjIqo   22.0     NaN             NaN
16    DE53507FXPvAibaEXe+fEAEfw3o+Ko6TvTSgijy3   22.0     NaN             NaN
17    158FB8C2XPvAibaEXe+x/3KKGWxYH2pEsBjyxoBO   22.0     NaN             NaN
18    6D8F53BDXPvAibaEXe8cJKtXZaLmvZGbeRUvU9Ym   22.0     NaN             NaN
19    D40A5224XPvAibaEXe/sW+jVmHnQGrpyj9mM/5XW   22.0     NaN             NaN
20    751C5CD8XPvAibaEXe8OoiZ7Qg2eT/MgIge5XLta   23.0     NaN             NaN
21    E1E49AA0XPvAibaEXe9uaaZ/YedHVPiewa5uM8QS   23.0     NaN             NaN
22    1B5C151DXPvAibaEXe9CFhTkHod3yUw8wiccXxfg   23.0     NaN             NaN
23    EE124006XPvAibaEXe+x/3KKGWxYH5eE8fYkddOq   23.0     NaN             NaN
24    BE04727AXPvAibaEXe8OoiZ7Qg2eT9tClu4Cs32M   23.0     NaN             NaN
25    4E3B2E64XPvAibaEXe93t/fGOsRpn05lMH4zm7Cp   23.0     NaN             NaN
26    0A29A66BXPvAibaEXe9CFhTkHod3yS4qPQKSYcEO   23.0     NaN             NaN
27    49ABC5EFXPvAibaEXe8eWl5Nr7OWQt3VotR9dXYx   23.0     NaN             NaN
28    789C02AAXPvAibaEXe+/1KYXP+fweK/y54Tvf704   24.0     NaN             NaN
29    A111A056XPvAibaEXe88G96lR9q/HbP6O5OR4CqK   24.0     NaN             NaN
30    6BDC0FB3XPvAibaEXe+5AEinM7he3oT9mkidxPDW   24.0     NaN             NaN
31    C805294BXPvAibaEXe8cJKtXZaLmvXmkH+PgfnFb   24.0     NaN             NaN
32    8474C347XPvAibaEXe+/1KYXP+fweAETvLS68nEF   24.0     NaN             NaN
33    E0C52A16XPvAibaEXe904Wq1lYkfi/ntiwVmPGZr   25.0     NaN             NaN
34    8A73C0A4XPvAibaEXe9uaaZ/YedHVG4ke7HP5CVh   25.0     NaN             NaN
35    E679EB47XPvAibaEXe+eIy6TmCsZuwhDZyQzJ/il   25.0     NaN             NaN
36    ACC6BE03XPvAibaEXe/7jEMhYBA6GZiEn3v4da33   25.0     NaN             NaN
37    7BAE4D59XPvAibaEXe/04IiIK7okBc/e3nqwl6Yl   25.0     NaN             NaN
38    E7959B13XPvAibaEXe93t/fGOsRpn/6DkGbVhKDL   25.0     NaN             NaN
39    CF820E88XPvAibaEXe88G96lR9q/HWQHdno6Q1dE   25.0     NaN             NaN
40    B3BB25C7XPvAibaEXe8E8MfopOpLfow3YpFUxKb9   25.0     NaN             NaN
41    F4F90434XPvAibaEXe/04IiIK7okBT/n8bF22cJ4   25.0     NaN             NaN
42    27A62100XPvAibaEXe+/1KYXP+fweJyZsRuyxmIg   25.0     NaN             NaN
43    63276F86XPvAibaEXe9Hp2TeoSwCGTQ0JelgLNZH   25.0     NaN             NaN
44    3A14E413XPvAibaEXe9uaaZ/YedHVADddd6jtCYd   26.0     NaN             NaN
45    19E0EE8FXPvAibaEXe97wmuqTYuV7djoRDmkvxKL   26.0     NaN             NaN
46    59F24D89XPvAibaEXe+MMervxP1vAFgzvQQfMwEA   26.0     NaN             NaN
47    E747458DXPvAibaEXe96K1aB3B4cKQggKDkChiCr   26.0     NaN             NaN
48    1E458D16XPvAibaEXe92C4qaj9kvH6/S4CNEqhXl   26.0     NaN             NaN
49    8EDF0CBCXPvAibaEXe+eIy6TmCsZu0mu7wa7hWrc   26.0     NaN             NaN
50    C1C2D49CXPvAibaEXe+5AEinM7he3lYo4Yh3wzso   26.0     NaN             NaN
51    0E3CC85BXPvAibaEXe/7YVAxOsMwOq19C4IZbCNV   26.0     NaN             NaN
52    039A40EBXPvAibaEXe/sW+jVmHnQGlexsxcKegMx   26.0     NaN             NaN
53    55164ECCXPvAibaEXe8NrxrmA741rzp6pr4JjBBO   27.0     NaN             NaN
54    E5B72901XPvAibaEXe/04IiIK7okBVX65TwUbxSQ   27.0     NaN             NaN
55    D77BA55CXPvAibaEXe97wmuqTYuV7ZzXGRkYG5x/   27.0     NaN             NaN
56    AF786B20XPvAibaEXe+MMervxP1vAEwg60BSZIR9   27.0     NaN             NaN
57    BDF344E0XPvAibaEXe97wmuqTYuV7e+YykH8Z97h   27.0     NaN             NaN
58    B4BB0B80XPvAibaEXe/sW+jVmHnQGrbV2aMBZxbl   27.0     NaN             NaN
59    D20DDE4FXPvAibaEXe8HWu5TvPOfaN9KOnh24+IZ   27.0     NaN             NaN
60    2B9BB841XPvAibaEXe/7YVAxOsMwOsVlHgtpSb0I   27.0     NaN             NaN
61    DB9FA965XPvAibaEXe904Wq1lYkfi1x2F3Ukc2Og   27.0     NaN             NaN
62    464EEB66XPvAibaEXe93t/fGOsRpnwKvZu4uHWUr   28.0     NaN             NaN
63    1A074443XPvAibaEXe/aqMXYDLKHRzKFKPFlF+3v   28.0     NaN             NaN
64    D6F5BEF7XPvAibaEXe+MMervxP1vAHvM1MwhSFCY   28.0     NaN             NaN
65    342257EAXPvAibaEXe/aqMXYDLKHR3SjNQBzsJDf   28.0     NaN             NaN
66    CE5AA641XPvAibaEXe/UTqPTjBxFVqOsv91ZMjHy   28.0     NaN             NaN
67    8851E69BXPvAibaEXe+eIy6TmCsZuzduBAHXYnYj   28.0     NaN             NaN
68    32425155XPvAibaEXe/jd8ghaf1GTDJ2RkglGilP   28.0     NaN             NaN
69    E19EA87BXPvAibaEXe96K1aB3B4cKbTxUAPWhMbc   29.0     NaN             NaN
70    BD12868AXPvAibaEXe8OoiZ7Qg2eT6mcyIhrsW0w   29.0     NaN             NaN
71    8F1119D3XPvAibaEXe/04IiIK7okBcgSWyeIFMKt   29.0     NaN             NaN
72    BFF8DA2FXPvAibaEXe+5AEinM7he3tn9b67IIJsR   29.0     NaN             NaN
73    2CFFC4A4XPvAibaEXe/UTqPTjBxFVmaKYeKYiNBw   29.0     NaN             NaN
74    A5C691C3XPvAibaEXe+MMervxP1vAHa9ZKGghhV0   30.0     NaN             NaN
75    408D0B61XPvAibaEXe/04IiIK7okBdYvNYs5MiFQ   30.0     NaN             NaN
76    6DE3DA07XPvAibaEXe+SI2uhC5CMEYmTe/FcwE7t   30.0     NaN             NaN
77    902895CAXPvAibaEXe9Hp2TeoSwCGUc05NETHA4y   30.0     NaN             NaN
78    0D56970AXPvAibaEXe+/1KYXP+fweMd3DfpYccg/   30.0     NaN             NaN
79    C6142704XPvAibaEXe88G96lR9q/HVMhBqOaOjJX   30.0     NaN             NaN
80    232946CFXPvAibaEXe/JhqMYLzzrR02+yvZ+pT+i   30.0     NaN             NaN
81    59884D21XPvAibaEXe8NrxrmA741r7Pe5nXtcI17   31.0     NaN             NaN
82    5E19BA75XPvAibaEXe96K1aB3B4cKVe+zJZEtwvN   31.0     NaN             NaN
83    6E786189XPvAibaEXe9N+b7C2VGPs5hGjFNP9OPe   31.0     NaN             NaN
84    33C734B5XPvAibaEXe+/1KYXP+fweL6Sr/n8oIDs   31.0     NaN             NaN
85    F400B823XPvAibaEXe92C4qaj9kvH9/66t3hNsRx   31.0     NaN             NaN
86    E32F85C4XPvAibaEXe8OoiZ7Qg2eTzHFJYtJfMmx   31.0     NaN             NaN
87    F934AFD4XPvAibaEXe/7YVAxOsMwOmFzQTm7dOKr   31.0     NaN             NaN
88    485EE734XPvAibaEXe9N+b7C2VGPs9muAnhMpjeF   32.0     NaN             NaN
89    ED123CFBXPvAibaEXe92C4qaj9kvHzy3ywisWZ4a   32.0     NaN             NaN
90    98885261XPvAibaEXe+fEAEfw3o+KtD8p1BCYU+u   32.0     NaN             NaN
91    1352A661XPvAibaEXe+eIy6TmCsZu+qEHG5QxOAG   32.0     NaN             NaN
92    7D6A1FB2XPvAibaEXe904Wq1lYkfi03olJ53wEUL   32.0     NaN             NaN
93    5ABD2AEBXPvAibaEXe8E8MfopOpLfpzgaVQKHwFD   33.0     NaN             NaN
94    72059684XPvAibaEXe9N+b7C2VGPs6rwW5yBcs12   33.0     NaN             NaN
95    C7C98961XPvAibaEXe/UTqPTjBxFVtKmLCQure30   33.0     NaN             NaN
96    5120F34CXPvAibaEXe8808q51BnmQvUpJUeNEyRf   33.0     NaN             NaN
97    FE6A40FDXPvAibaEXe+x/3KKGWxYH7Njftr2o+Ld   34.0     NaN             NaN
98    26504393XPvAibaEXe97wmuqTYuV7f7oqpX5KaC9   34.0     NaN             NaN
99    B2DF2BCBXPvAibaEXe/aqMXYDLKHR/Rvx1vG7yZ8   34.0     NaN             NaN
100   51E5CFABXPvAibaEXe93t/fGOsRpnwBCueYR01nj   34.0     NaN             NaN
101   F473C1ABXPvAibaEXe/jd8ghaf1GTNdb+cfjD9JK   35.0     NaN             NaN
102   EA5C3600XPvAibaEXe96K1aB3B4cKYcgi+qudqoq   35.0     NaN             NaN
103   09EA1246XPvAibaEXe9N+b7C2VGPs7VmmYGpq5S4   35.0     NaN             NaN
104   271B286AXPvAibaEXe9CFhTkHod3yfY0OnaNvlXt   35.0     NaN             NaN
105   A087B8CAXPvAibaEXe96K1aB3B4cKeZgLP7Zudq0   35.0     NaN             NaN
106   2E7766A4XPvAibaEXe8cJKtXZaLmvYU52KoCieBc   36.0     NaN             NaN
107   E4A8F3C3XPvAibaEXe8OoiZ7Qg2eT+Jy+LbBom1V   36.0     NaN             NaN
108   843B6F23XPvAibaEXe93t/fGOsRpn9x0GlU2wsFG   37.0     NaN             NaN
109   F74A82C2XPvAibaEXe9uaaZ/YedHVBLMZpuFaBWv   37.0     NaN             NaN
110   9FBBFEDAXPvAibaEXe9uaaZ/YedHVDIAvlASfm3N   37.0     NaN             NaN
111   DB711988XPvAibaEXe8E8MfopOpLfuvKyaJThdNU   37.0     NaN             NaN
112   5A8FC80AXPvAibaEXe9Hp2TeoSwCGQOTvUMD2sdV   37.0     NaN             NaN
113   075CAE0AXPvAibaEXe/7jEMhYBA6GRpJvL6kzgyG   37.0     NaN             NaN
114   DD6DDD9BXPvAibaEXe8808q51BnmQgYlXLk+6Sms   38.0     NaN             NaN
115   461F878CXPvAibaEXe88G96lR9q/HUNPesL1mp7V   38.0     NaN             NaN
116   5D84A808XPvAibaEXe/04IiIK7okBVnVDuMtAOeG   38.0     NaN             NaN
117   12C6CEBDXPvAibaEXe8HWu5TvPOfaHJ8WggqhfpV   38.0     NaN             NaN
118   47C7F0D8XPvAibaEXe8cJKtXZaLmvW7+9X9I1l88   39.0     NaN             NaN
119   62CB9074XPvAibaEXe+5AEinM7he3lQjjwdeAKvG   39.0     NaN             NaN
120   63850E1DXPvAibaEXe9uaaZ/YedHVMbH1bo0wP7i   40.0     NaN             NaN
121   BCD2B356XPvAibaEXe/UTqPTjBxFVlHUdLueHP1K   40.0     NaN             NaN
122   ED940AE5XPvAibaEXe/sW+jVmHnQGmpcv505KQtY   40.0     NaN             NaN
123   0DB26593XPvAibaEXe+fEAEfw3o+Koj1aryhxwXB   42.0     NaN             NaN
124   37E8854FXPvAibaEXe93t/fGOsRpn2pIVjPlvyxA   42.0     NaN             NaN
125   260F89E3XPvAibaEXe904Wq1lYkfi3SWlgS7D671   43.0     NaN             NaN
126   50710A05XPvAibaEXe+5AEinM7he3i2ud45eDBqh   43.0     NaN             NaN
127   F0261509XPvAibaEXe+eIy6TmCsZu0RLWC8H9A9f   43.0     NaN             NaN
128   B280054FXPvAibaEXe/aqMXYDLKHRx1deGanA5Uq   44.0     NaN             NaN
129   88F1979DXPvAibaEXe9uaaZ/YedHVLTpfQz3FFXG   46.0     NaN             NaN
130   962B588DXPvAibaEXe8808q51BnmQv7uo+CT+yEW   47.0     NaN             NaN
131   8A06BCB7XPvAibaEXe+/1KYXP+fweAfbWbYeLDhP   48.0     NaN             NaN
132   FC15E78FXPvAibaEXe92C4qaj9kvH9Xq+b0SgU4o   49.0     NaN             NaN
133   CD72A72AXPvAibaEXe/sW+jVmHnQGj7x1GbslKUs   50.0     NaN             NaN
134   82778F75XPvAibaEXe93t/fGOsRpn50R4yA7HNuJ   51.0     NaN             NaN
135   9E8D0CE7XPvAibaEXe+/1KYXP+fweLFNn49rOazP   51.0     NaN             NaN
136   017CD572XPvAibaEXe9CFhTkHod3yQuYGl3Dx7Ko   51.0     NaN             NaN
137   E5DDE060XPvAibaEXe/7YVAxOsMwOgzKuxoPANYq   52.0     NaN             NaN
138   A3B55E76XPvAibaEXe/7YVAxOsMwOlSm2jrgLdri   53.0     NaN             NaN
139   F9F00F9BXPvAibaEXe/7YVAxOsMwOkCUOyzVAIdc   54.0     NaN             NaN
140   EF351515XPvAibaEXe9CFhTkHod3yS5z1VDkCy75   54.0     NaN             NaN
141   FA26D15DXPvAibaEXe+x/3KKGWxYH5f+BLhTctEV   55.0     NaN             NaN
142   77AA22BDXPvAibaEXe/5h0vZw0NHLw1SiBz29uk2   56.0     NaN             NaN
143   41879EDBXPvAibaEXe8HWu5TvPOfaMIlvMjXTKxE   58.0     NaN             NaN
144   7605FEEEXPvAibaEXe8808q51BnmQv/RCCjB4N+s   59.0     NaN             NaN
145   92D79C05XPvAibaEXe+x/3KKGWxYH9g/4fJgJYs6   60.0     NaN             NaN
146   62BFFE2EXPvAibaEXe/9ugxkUZcLfPe37BSUxSyd    0.0    avsc             NaN
147   2D9401D8XPvAibaEXe9wxm0WjsXoKi8Gkvb5OPeR   11.0    avsc             NaN
148   59F1708DXPvAibaEXe+dMotnUFI9LS1TYt9joenk   11.0    avsc             NaN
149   EA1D81AFXPvAibaEXe/RnFf25EKRr7/Z28Po+End   13.0    avsc             NaN
150   9FA1AF84XPvAibaEXe9JJ0DEqozv6EHh9Z2rxnaz   14.0    avsc             NaN
151   192E4235XPvAibaEXe92Jin2iMtHChKANAao8ZUk   15.0    avsc             NaN
152   A3609609XPvAibaEXe/5h0vZw0NHL1nnBX6fWEJQ   15.0    avsc             NaN
153   CFD92B12XPvAibaEXe8NrxrmA741rwjdaY15+2D+   16.0    avsc             NaN
154   61180195XPvAibaEXe9gcLLHJLBBnR5wpoU3apq+   16.0    avsc             NaN
155   02B5E19DXPvAibaEXe+6DwsvcvouVduD45n92KAo   16.0    avsc             NaN
156   4152FE50XPvAibaEXe9G2n4phUxISJmNzq1KHgOO   16.0    avsc             NaN
157   B5B671BFXPvAibaEXe8Ve7JqRML75doVJ2SaEcz4   16.0    avsc             NaN
158   BA8D8AFEXPvAibaEXe+6DwsvcvouVfTF+jYi4dQZ   16.0    avsc             NaN
159   973154C3XPvAibaEXe+Y2Dmraxe1iYT8oxNVsVdy   16.0    avsc             NaN
160   D9B44B1CXPvAibaEXe9ASX2YKqk5Aeh+/OS8HqTX   16.0    avsc             NaN
161   5F015460XPvAibaEXe/5h0vZw0NHL3rTJlBbR6W0   17.0    avsc             NaN
162   32180497XPvAibaEXe/t7ClCI88v7sGEqCvtpJrq   17.0    avsc             NaN
163   2900754CXPvAibaEXe9gcLLHJLBBnX1D4yMOsVg0   17.0    avsc             NaN
164   3DD6D60BXPvAibaEXe/81GDNmtxKsSpculnFzj6s   17.0    avsc             NaN
165   01377D44XPvAibaEXe/BLy1WUS+NVlzbxIIHMtmt   18.0    avsc             NaN
166   FF9BCACDXPvAibaEXe9a9WHB728zIL656Mdf6zEw   18.0    avsc             NaN
167   22101E7EXPvAibaEXe+EYzJPHISY88zmD5Ggw1zy   18.0    avsc             NaN
168   7F03C845XPvAibaEXe9mDsFtgVHJ/rHAoglzQPuR   19.0    avsc             NaN
169   68481D94XPvAibaEXe+3sZoWnetaj+cTym+QdnwT   19.0    avsc             NaN
170   1C245E0EXPvAibaEXe/rR9uJzGOYEuQ8DvEilYoI   19.0    avsc             NaN
171   1018ADF8XPvAibaEXe/5n/8z7IorIk20OdhUEnK0   19.0    avsc             NaN
172   330A20C4XPvAibaEXe+n4oL3iuTqC+0PyxPF31kr   19.0    avsc             NaN
173   6E854833XPvAibaEXe9a9WHB728zIMSTTWhKiiWi   19.0    avsc             NaN
174   A99910D5XPvAibaEXe8X/UxhAbbOGw8A+5PDAGk9   19.0    avsc             NaN
175   3B36303EXPvAibaEXe92Jin2iMtHCuWTyMGfWwjT   19.0    avsc             NaN
176   D18E8F78XPvAibaEXe8G+DN2/i3pryst66Pf9PYJ   19.0    avsc             NaN
177   F26FD744XPvAibaEXe8OLQLlidG6//6ShwJ1wZku   19.0    avsc             NaN
178   4C9B57D9XPvAibaEXe8eJZh5OyStbNCI+BAkeQmo   19.0    avsc             NaN
179   15A008BEXPvAibaEXe8X/UxhAbbOG1sG/TbS5k88   19.0    avsc             NaN
180   92F8B64EXPvAibaEXe+YFpGAAgvtefsYfGW2BhK3   19.0    avsc             NaN
181   119C7562XPvAibaEXe/rR9uJzGOYEkfPMWFUTNpZ   19.0    avsc             NaN
182   8A28E60EXPvAibaEXe9OORQ1xsw6nv5CUStjJAu6   19.0    avsc             NaN
183   89BF1B4BXPvAibaEXe/v5x/h23myCcvAATP35Y2J   20.0    avsc             NaN
184   56996328XPvAibaEXe8FGyuwtFnKnOqpMxWSLkC/   20.0    avsc             NaN
185   649B938BXPvAibaEXe9IFJLLU9DVVZoHDwmaCg4s   20.0    avsc             NaN
186   DCD90AC2XPvAibaEXe9KS65t7Tb/qM1p6wX0RxXR   20.0    avsc             NaN
187   B3F16D5DXPvAibaEXe/agc6/owW5CGwRRuccquwf   20.0    avsc             NaN
188   DD10B95EXPvAibaEXe/PQrWCRBKWOUTASXEgaMpR   20.0    avsc             NaN
189   C2218479XPvAibaEXe/agc6/owW5CH4478G8f1TP   20.0    avsc             NaN
190   FD80AB73XPvAibaEXe+XQbEHiLBIRamkrkJOEq58   20.0    avsc             NaN
191   FE3AC989XPvAibaEXe8VnqU11737Hl6IFmKBfB+P   20.0    avsc             NaN
192   7D4060BBXPvAibaEXe8Ve7JqRML75f60sgal9POH   20.0    avsc             NaN
193   3C65A25EXPvAibaEXe998fVikzcJIuk4ang3tj+3   20.0    avsc             NaN
194   E5B18116XPvAibaEXe/7jtQOMcuJ+3mMd8xWafpS   20.0    avsc             NaN
195   ADC5F05DXPvAibaEXe+3sZoWnetajz661V0/hMR1   20.0    avsc             NaN
196   2B8BC614XPvAibaEXe/uPR0E3TEtQm7Vvb2UfkDr   20.0    avsc             NaN
197   00E148C2XPvAibaEXe+YFpGAAgvteQTcTeueqms0   20.0    avsc             NaN
198   487A9A3FXPvAibaEXe+n4oL3iuTqC6vV9FvUFu7N   20.0    avsc             NaN
199   BD0493E1XPvAibaEXe/WTR5UGsYutA7PJ6yFCsBD   20.0    avsc             NaN
200   21478CA5XPvAibaEXe87069oyWO+Ia90rjo5SvVw   21.0    avsc             NaN
201   D6527C3BXPvAibaEXe9eYPx3anXXhH8it6AZlLzp   21.0    avsc             NaN
202   CC6A9A36XPvAibaEXe87069oyWO+IdRQUNsRf3jJ   21.0    avsc             NaN
203   84C35FAEXPvAibaEXe/BLy1WUS+NVj4ytGkizcS1   21.0    avsc             NaN
204   1EDA2DA4XPvAibaEXe8lzySxhHiT0RqGwGqh/eBg   21.0    avsc             NaN
205   DF522B8DXPvAibaEXe+zrGHfAUSFacLkM4T9DLZg   21.0    avsc             NaN
206   58C3BAECXPvAibaEXe/jA2MATe6eKg/8OGy+CwwB   21.0    avsc             NaN
207   604A61D2XPvAibaEXe+g2dQ0D263aZSBBb1uQ+ou   21.0    avsc             NaN
208   4842D442XPvAibaEXe+wVOsoF63SsLCyCepkMYRu   21.0    avsc             NaN
209   006E432EXPvAibaEXe8UGNMJasZG8PBqBoa4ReWL   21.0    avsc             NaN
210   25E596D7XPvAibaEXe9W7fV/x7qyQKb8gpK3QObP   21.0    avsc             NaN
211   28F6E5E2XPvAibaEXe8UBGVVSBKSkgHdFRn4cEDg   21.0    avsc             NaN
212   7F57E0CAXPvAibaEXe9CJmVsz9P34gSFnyCRxpl4   21.0    avsc             NaN
213   73EBC2A0XPvAibaEXe9A3Yjgh4iPfsTl7Hkve08O   21.0    avsc             NaN
214   48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO   21.0    avsc             NaN
215   2D14C10DXPvAibaEXe9XrYsEpevBo9IvzkP6Fz7n   22.0    avsc             NaN
216   27DEED3DXPvAibaEXe+wVOsoF63SsFd2Mp70LIMr   22.0    avsc             NaN
217   EE6BEA20XPvAibaEXe87qJpUsO6V7Q5qVfwmgf40   22.0    avsc             NaN
218   85B8581AXPvAibaEXe9kJ+qYUUrp691e6albNlig   22.0    avsc             NaN
219   3B582529XPvAibaEXe8FAisiSJM2IrqJDUgjWexI   22.0    avsc             NaN
220   CE26DE57XPvAibaEXe/ns/wSuHF6kIdO4NoVtFhP   22.0    avsc             NaN
221   3E7F9BAEXPvAibaEXe/PQrWCRBKWOXm6NoDezPNj   22.0    avsc             NaN
222   923950A6XPvAibaEXe8UBGVVSBKSkqDyKnP1YxDR   22.0    avsc             NaN
223   4CC723E2XPvAibaEXe876wt31yGPP6r9sXqNueqs   22.0    avsc             NaN
224   10E59E76XPvAibaEXe998fVikzcJIr3mNM3FOo5P   22.0    avsc             NaN
225   0B431A01XPvAibaEXe87069oyWO+IS0M6kVzLXKw   22.0    avsc             NaN
226   148B0735XPvAibaEXe/PpYImsUfHqE1zMz8TOUpD   22.0    avsc             NaN
227   45C1AE02XPvAibaEXe+Y2Dmraxe1iZRzEs93KNw/   22.0    avsc             NaN
228   EA7B8E5FXPvAibaEXe8zjuWfAVBr9cS9jZZ7+sgV   22.0    avsc             NaN
229   E402E8DCXPvAibaEXe876wt31yGPP/BDYut7u/p4   22.0    avsc             NaN
230   843E09D5XPvAibaEXe+wVOsoF63SsA/SMCcbPHeo   22.0    avsc             NaN
231   7B20E493XPvAibaEXe+LbmSTUWVMuONuSvs2x/3l   22.0    avsc             NaN
232   106C1014XPvAibaEXe9CJmVsz9P34llPLLtWfMbO   22.0    avsc             NaN
233   424EB384XPvAibaEXe/ns/wSuHF6kAg0pvH9yY1n   22.0    avsc             NaN
234   6346E154XPvAibaEXe8enouoh243g/dhreMbu5xg   23.0    avsc             NaN
235   E40D7555XPvAibaEXe+7uLWSh9XvQldFZO++DN6K   23.0    avsc             NaN
236   9459651DXPvAibaEXe88L+jeN4TPm+kq8KkjBzW+   23.0    avsc             NaN
237   DA535D84XPvAibaEXe/KpP1fV6ua5yY+4IoIEWJj   23.0    avsc             NaN
238   3670B2F3XPvAibaEXe92Jin2iMtHCooAV2Og/xCx   23.0    avsc             NaN
239   95812940XPvAibaEXe9OORQ1xsw6noRj8oxMKORS   23.0    avsc             NaN
240   353291D0XPvAibaEXe+u8DuxWGTFfOeTkx29Aj4l   23.0    avsc             NaN
241   178F60F5XPvAibaEXe9WgQQLl7rkk9xNzvD5m8xA   23.0    avsc             NaN
242   7E5F0261XPvAibaEXe9x7FcJ6vxIP/wyKPNs2niT   23.0    avsc             NaN
243   B2366359XPvAibaEXe8lzySxhHiT0abgjQcayJU6   23.0    avsc             NaN
244   B76C034CXPvAibaEXe+7P4TS0/ikVaiShJPRi8D8   23.0    avsc             NaN
245   EC385B25XPvAibaEXe+zrGHfAUSFaSWfOcnuwhIE   23.0    avsc             NaN
246   3A751C91XPvAibaEXe876wt31yGPP4jtOTSRHqgW   23.0    avsc             NaN
247   00ACC499XPvAibaEXe8ciyLBP/Qla4g3ka0I3o/F   23.0    avsc             NaN
248   89B9E37AXPvAibaEXe9x7FcJ6vxIP8ZfUeeTsqYu   23.0    avsc             NaN
249   BED5368DXPvAibaEXe+YFpGAAgvteWQNcBQnhVHj   23.0    avsc             NaN
250   829A6930XPvAibaEXe9wxm0WjsXoKvogSZjqOrmh   23.0    avsc             NaN
251   C85CAC55XPvAibaEXe8eWl5Nr7OWQnSDhPbn24Ji   23.0    avsc             NaN
252   7F122563XPvAibaEXe9W7fV/x7qyQJdcv/a2vx7K   23.0    avsc             NaN
253   3F6464F9XPvAibaEXe8pd25OrRS+bfhEJhQJNXId   23.0    avsc             NaN
254   2FF04FA8XPvAibaEXe/5h0vZw0NHLz1icbUz+Z9r   23.0    avsc             NaN

# Xử lý dữ liệu

### cột mssv

Drop dữ liệu bị khuyết trong total và mssv do dữ liệu bị khuyết rất nhỏ

In [ ]:
# Kiểm tra dữ liệu khuyết
missing_count = df['mssv'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'mssv': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'mssv': 6

In [ ]:
# Kiểm tra trùng lặp dữ liệu với khóa chính là tổ hợp mssv
duplicate_count = df.duplicated(subset=['mssv']).sum()
print(f"Số giá trị trùng lặp trong tổ hợp 'mssv': {duplicate_count + 1}")

Số giá trị trùng lặp trong tổ hợp 'mssv': 6

In [ ]:
# Danh sách các giá trị 'mssv' bị trùng lặp
duplicate_values = df[df.duplicated(subset='mssv', keep=False)]['mssv'].unique()
print("Các giá trị bị trùng lặp:", duplicate_values)

Các giá trị bị trùng lặp: [nan]

In [ ]:
df.dropna(subset=['mssv'], inplace=True)

### cột mamh

Đối với cột mamh sẽ được điền theo môn xuất hiện nhiều nhất

In [ ]:
# Kiểm tra dữ liệu khuyết
missing_count = df['mamh'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'mamh': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'mamh': 195

In [ ]:
# Các giá trị duy nhất và tần suất cho các cột định mamh
print("\nGiá trị duy nhất trong cột 'mamh':")
print(df['mamh'].value_counts())
print(df['mamh'].unique())

Giá trị duy nhất trong cột 'mamh':
mamh
eng01         1297
avsc1         1261
avsc2          824
eng02          713
en001          563
avsc           415
eng03          406
eng04          261
eng05          225
miễn eng03     111
en002           72
Name: count, dtype: int64
[nan ' avsc' ' en001' ' en002' ' eng01' ' eng02' ' eng03' ' eng05'
 ' eng04' ' avsc1' ' avsc2' ' miễn eng03']

In [ ]:
df['mamh'].mode()

0     eng01
Name: mamh, dtype: object

In [ ]:
# Điền dữ liệu khuyết theo mode
df['mamh'].fillna(df['mamh'].mode()[0], inplace=True)

<ipython-input-18-d936217bc7fc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mamh'].fillna(df['mamh'].mode()[0], inplace=True)

### cột ghichu

Do là dữ liệu cột ghi chú chỉ có thông tin về TOEIC nên sẽ chuyển thông tin từ dữ liệu cột ghi chú qua cột mamh vì cột điểm ở cột total tại những dòng có ghi chú là TOEIC thì điểm đó total không còn bằng tổng 'listening', 'reading'

In [ ]:
# kiểm tra dữ liệu khuyết
missing_count = df['ghichu'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'ghichu': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'ghichu': 4797

In [ ]:
df['ghichu'].unique()

array([nan, ' qui đổi toeic'], dtype=object)

In [ ]:
# Lọc dữ liệu theo ghi chú liên quan đến TOEIC
toeic_conditions = [' qui đổi toeic']
toeic_columns = df[df['ghichu'].isin(toeic_conditions)]

In [ ]:
# Chuyển giá trị từ cột `ghichu` sang `mamh`
df.loc[df['ghichu'].isin(toeic_conditions), 'mamh'] = 'toeic'

In [ ]:
df['mamh'].unique()

array([' eng01', ' avsc', ' en001', ' en002', ' eng02', ' eng03',
       ' eng05', ' eng04', ' avsc1', ' avsc2', 'toeic'], dtype=object)

In [ ]:
# Loại bỏ cột 'ghichu' khỏi dữ liệu
df.drop(columns=['ghichu'], inplace=True)

In [ ]:
# Các cột còn lại
df.dtypes

mssv      object
total    float64
mamh      object
dtype: object

### Kiểm tra cột total

In [ ]:
# kiểm tra dữ liệu khuyết
missing_count = df['total'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'total': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'total': 0

In [ ]:
# Các giá trị duy nhất và tần suất trong cột total
print(f"\nGiá trị duy nhất trong cột 'total':")
print(df['total'].value_counts())
print(df['total'].unique())

Giá trị duy nhất trong cột 'total':
total
43.0     113
48.0     109
40.0     103
50.0     102
44.0      97
36.0      96
41.0      96
52.0      94
46.0      93
55.0      91
37.0      91
54.0      90
38.0      89
56.0      87
49.0      85
45.0      85
39.0      84
57.0      82
53.0      81
42.0      80
35.0      79
47.0      79
61.0      72
32.0      72
58.0      71
63.0      70
70.0      68
69.0      66
33.0      66
60.0      65
51.0      63
29.0      63
31.0      62
68.0      61
27.0      61
64.0      60
59.0      59
66.0      59
34.0      59
28.0      59
25.0      58
62.0      58
65.0      57
30.0      55
72.0      54
75.0      54
260.0     51
280.0     50
73.0      50
235.0     49
24.0      48
26.0      47
77.0      44
71.0      44
67.0      44
82.0      43
74.0      42
23.0      42
285.0     41
210.0     41
76.0      40
78.0      40
265.0     40
87.0      39
83.0      39
80.0      36
190.0     36
85.0      36
91.0      35
215.0     35
305.0     35
240.0     34
245.0     33
310.0     33
22.0      32
255.0     31
195.0     31
86.0      31
79.0      30
81.0      30
400.0     29
84.0      29
96.0      28
205.0     28
93.0      28
90.0      28
275.0     28
92.0      27
200.0     27
88.0      27
185.0     26
270.0     26
220.0     25
250.0     25
325.0     25
89.0      25
20.0      24
300.0     24
320.0     23
330.0     22
180.0     22
95.0      21
94.0      21
365.0     21
295.0     21
19.0      20
335.0     20
98.0      20
405.0     19
175.0     19
415.0     19
440.0     19
100.0     19
21.0      18
315.0     18
455.0     18
97.0      18
350.0     17
500.0     17
340.0     16
345.0     16
430.0     15
101.0     15
410.0     14
390.0     14
395.0     14
225.0     14
106.0     14
470.0     14
435.0     14
370.0     14
445.0     13
104.0     13
380.0     13
385.0     13
375.0     13
450.0     13
230.0     13
355.0     11
103.0     11
475.0     11
480.0     11
520.0     11
530.0     11
465.0     11
420.0     10
16.0      10
155.0     10
460.0      9
170.0      9
105.0      9
99.0       9
510.0      9
18.0       8
290.0      8
165.0      8
425.0      8
17.0       7
535.0      7
360.0      7
109.0      7
485.0      7
107.0      7
160.0      6
140.0      6
15.0       6
102.0      6
505.0      6
110.0      6
560.0      6
565.0      6
111.0      6
515.0      5
525.0      5
540.0      5
555.0      5
495.0      5
108.0      4
490.0      3
570.0      3
585.0      3
114.0      3
575.0      3
11.0       3
150.0      3
113.0      2
13.0       2
112.0      2
610.0      2
605.0      2
14.0       2
580.0      2
545.0      2
145.0      1
135.0      1
0.0        1
630.0      1
6.0        1
10.0       1
116.0      1
600.0      1
595.0      1
590.0      1
125.0      1
Name: count, dtype: int64
[ 15.  16.  18.  19.  20.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  42.  43.  44.  46.
  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  58.  59.  60.   0.
  11.  13.  14.  17.  21.  41.  45.  57.  61.  62.  63.  65.  66.  87.
  83.  64.  75.  90.  67.  85.  72.  69.  84.  88.  70.  68.  74.  93.
  95.  71.  82.  91.  73.  77.  78.  79.  81.  89.  76.  86.  80.  92.
  94.  96. 104. 105. 106. 112. 110.  97.  98. 114.  99. 103. 109. 113.
 102. 100. 111. 108. 107. 101.   6.  10. 116. 630. 610. 605. 600. 595.
 590. 585. 580. 575. 570. 565. 560. 555. 545. 540. 535. 530. 525. 520.
 515. 510. 505. 500. 495. 490. 485. 480. 475. 470. 465. 460. 455. 450.
 445. 440. 435. 430. 425. 420. 415. 410. 405. 400. 395. 390. 385. 380.
 375. 370. 365. 360. 355. 350. 345. 340. 335. 330. 325. 320. 315. 310.
 305. 300. 295. 290. 285. 280. 275. 270. 265. 260. 255. 250. 245. 240.
 235. 230. 225. 220. 215. 210. 205. 200. 195. 190. 185. 180. 175. 170.
 165. 160. 155. 150. 145. 140. 135. 125.]

In [ ]:
# Đổi tên các cột để cho phù hợp với nội dung của của dữ liệu
df.columns = ['mssv', 'diemta', 'mamta']

### Lưu dữ liệu đã làm sạch

In [ ]:
df.to_excel("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/04.xeploaiav.xlsx", index=False)