# Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Thiết lập để hiển thị tất cả dòng và cột dataframe

In [3]:
pd.set_option('display.max_rows', None)  # Hiển thị tất cả các dòng
pd.set_option('display.max_columns', None)  # Hiển thị tất cả các cột

# Đọc & xử lý dữ liệu

In [4]:
data_path  = "/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/EDA"

In [5]:
# Load dữ liệu
df = pd.read_excel(data_path + "/08.XLHV_EDA.xlsx") # Có thể thay đổi theo shortcut trên drive

In [6]:
# Loại trừ các cột 'A', 'C', 'D'
exclude_columns = ['mssv', 'lydo', 'ngayqd']

# Chỉ xử lý các cột kiểu object và không nằm trong exclude_columns
for column in df.select_dtypes(include=['object']).columns:
    if column not in exclude_columns:
        df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%\-]", '', regex=True)

In [7]:
df.head(10)

,mssv,tinhtrang,lydo,hocky,namhoc,ngayqd
0,98247E19XPvAibaEXe93PEySAJOVkxsz+HIviyYJ,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
1,52B1CC2DXPvAibaEXe+kwIr/VXjl0w+FyuW1abQ7,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
2,5666EAF4XPvAibaEXe+Z7KfNHYLttJaLI+SH+DpO,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
3,682C32E0XPvAibaEXe/Bn5cQSu92WX0DcIKdud8D,2.0,Bị cảnh cáo vì ĐTB 2 học kỳ liên tiếp < 4,2.0,2016.0,2017-04-18 00:00:00
4,7901D3A9XPvAibaEXe+6MN9FoW2mqYEmruXXBNsS,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
5,82D67FF0XPvAibaEXe9Bx5CZuIA9z+ymYnRBj6Fr,2.0,Bị cảnh cáo vì:\n- ĐTB học kỳ 1 < 3\n- Đóng h...,2.0,2016.0,2017-04-18 00:00:00
6,FBD9AAFEXPvAibaEXe+5oCRQPDKXsjh0OTYpdD2Y,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
7,B47BC5E8XPvAibaEXe/H1VZJBzJAwmY5aGwFIvk2,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00
8,7FBD0513XPvAibaEXe+ltCXpm838vaXT1ZHB2inA,2.0,Bị cảnh cáo vì đóng học phí trễ,2.0,2016.0,2017-04-18 00:00:00
9,C3E0BACEXPvAibaEXe8zBeLfIMmoBC4sDuuDh1j3,2.0,Bị cảnh cáo vì ĐTB học kỳ 1 < 3,2.0,2016.0,2017-04-18 00:00:00

# Kiểm tra dữ liệu bị khuyết

In [8]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv           7
tinhtrang      7
lydo           7
hocky          7
namhoc         7
ngayqd       953
dtype: int64

In [9]:
# Tỷ lệ giá trị thiếu
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)
print("Tỷ lệ giá trị thiếu (%):")
print(missing_percentage)

Tỷ lệ giá trị thiếu (%):
ngayqd       27.607184
mssv          0.202781
tinhtrang     0.202781
lydo          0.202781
hocky         0.202781
namhoc        0.202781
dtype: float64

In [10]:
# Kiểm tra số dòng chứa giá trị null
num_null_rows = df.isnull().any(axis=1).sum()
print(f"Số dòng chứa giá trị null: {num_null_rows}")

Số dòng chứa giá trị null: 953

In [11]:
# Lọc các dòng có chứa giá trị null
rows_with_null = df[df.isnull().any(axis=1)]
print(rows_with_null)

                                          mssv  tinhtrang  \
498                                        NaN        NaN
1003                                       NaN        NaN
1502  119C7562XPvAibaEXe/rR9uJzGOYEkfPMWFUTNpZ        5.0
1503                                       NaN        NaN
1999  498EE480XPvAibaEXe8TrN3vUI8MaHHVw1RfTSHE        2.0
2000                                       NaN        NaN
2470  ED115863XPvAibaEXe9puzAyruoCKVqmP5JLKX2e        2.0
2471                                       NaN        NaN
2505  AE2F1B61XPvAibaEXe9BgVwdGgzpac6mspMdyLgK        2.0
2506  F42652EDXPvAibaEXe8Ve7JqRML75ZotBOnQHExP        2.0
2507  35DA89B4XPvAibaEXe/pS44gx8Fm9tOJ1EFCqalV        2.0
2508  445B1666XPvAibaEXe/eRksRS1wGeLe60/QESEnH        2.0
2509  3A2BE3ECXPvAibaEXe/hadw09FE3WmcRG1NdhIvW        2.0
2510  A259F1D8XPvAibaEXe+LbmSTUWVMuNAoY/EQV9z/        2.0
2511  04C4D9F8XPvAibaEXe+/MvKIb2VAVSyw+efhOMhT        2.0
2512  687112ECXPvAibaEXe8ciyLBP/Qla/1I7+xi3CDh        2.0
2513  18D53A17XPvAibaEXe/7VXm0xgXldKrj4VJp0HeL        2.0
2514  DEB053E1XPvAibaEXe8091B3Eu2czB1zall3nIQM        2.0
2515  FAC2CB19XPvAibaEXe9hweWHK/GxsCZwqeiCNyRF        2.0
2516  49A1BA5BXPvAibaEXe9Q2McsUcINThdliToQ9eZW        2.0
2517  6FF0201BXPvAibaEXe8CSUzma4ok0qaqULSZihQx        2.0
2518  A32EFA8EXPvAibaEXe/ceziXFRXnLR7U3YmgWB2n        2.0
2519  F9AB3110XPvAibaEXe9Fy2hCq9OiA5v/Y7zbJ0xU        2.0
2520  BE1A9ABEXPvAibaEXe92Umf5pb/ttjv+Q4aigMmx        2.0
2521  79DF0DD4XPvAibaEXe9Rxq3EQECnGd5G/qR26MNG        2.0
2522  EC99E930XPvAibaEXe+tSA7t7USLJxsqKIT1dxt6        2.0
2523  826FA2C3XPvAibaEXe9YgNnR0JxPhZ0g/j/FBtq4        2.0
2524  2EB80034XPvAibaEXe/8X6gsb95YiHj38qo0I8/f        2.0
2525  E9663523XPvAibaEXe9NZBs7fjgAwcNVPcSAOMdb        2.0
2526  77AA22BDXPvAibaEXe/5h0vZw0NHLw1SiBz29uk2        2.0
2527  5B997E53XPvAibaEXe+E+n9mGyneJ70Lhr+6U41d        2.0
2528  608BEFE7XPvAibaEXe+F+2tZHEiFCUiDU7HYOWwp        2.0
2529  A78DB0A7XPvAibaEXe8pr9LKErUcFccIBSJ6B04w        2.0
2530  CB9BB1D7XPvAibaEXe8BxOZlGHrYNymZpYFw4ucN        2.0
2531  F6059576XPvAibaEXe99yNsueYx+seyUo79Ylb6Y        2.0
2532  288E4445XPvAibaEXe8iGDMJikW1wv69BjaGCsB1        2.0
2533  953C6A47XPvAibaEXe+5AEinM7he3uLH7djD90X8        2.0
2534  86053F82XPvAibaEXe81r7KrCH0uc8qhbnpGNt/A        2.0
2535  FF575360XPvAibaEXe9wgACCA7SCWWiaUs/GWfcV        2.0
2536  88451395XPvAibaEXe8zN2KKhdLFumVa/8Mv/que        2.0
2537  D6F8D120XPvAibaEXe8jwcgah0IjmlZkieUL7FU5        2.0
2538  D2607DA4XPvAibaEXe+Xxbs4kvH/k3apAf4rYUUN        2.0
2539  D58840DCXPvAibaEXe9ZsjBGMHTvphkgWrjhffHl        2.0
2540  B961FA7FXPvAibaEXe8FWWF7xHXRAD9tn9AVbX5C        2.0
2541  F9E0FADCXPvAibaEXe/sDxpKTuGnIFrIL+atz1A4        2.0
2542  372B8B67XPvAibaEXe9Veo8epKbTmDULBuPb9MJv        2.0
2543  80DC25ADXPvAibaEXe9DjwUQ+Cta8TJ0gcpyEAkF        2.0
2544  8442D4A1XPvAibaEXe8n6FFpptVzUnUcDJxNSI27        2.0
2545  2773033DXPvAibaEXe/45+b0LBlJ7DcasbYNV/NV        2.0
2546  2B14A7FDXPvAibaEXe9WcTnuikKYKkkapOSDRceM        2.0
2547  B2F1F3CEXPvAibaEXe8a4mdANazFZH7X437gU+Fq        2.0
2548  211E77C4XPvAibaEXe8zLanLNVS12e4d+7rbcZ6A        2.0
2549  D0C629C0XPvAibaEXe+fPSOag5leTeota8X7NDoH        2.0
2550  94280F25XPvAibaEXe+cHxM5cHw4WohfI8Ubq4u0        2.0
2551  2051316CXPvAibaEXe8y6/RMXZRwBSpb0VHJadCX        2.0
2552  C4B38772XPvAibaEXe+Z64Gg7q108LicaFLhBWqn        2.0
2553  F321EBC0XPvAibaEXe+BUGeEgVnB4DpkT8waCpJm        2.0
2554  2EE8EACBXPvAibaEXe/PQrWCRBKWOUgYNGbFx+gp        2.0
2555  EA5B909FXPvAibaEXe+7P4TS0/ikVWIgtv30JvpE        2.0
2556  A2367341XPvAibaEXe92CdOgj+Qa/Tg3EV7CxWaE        2.0
2557  CA90782BXPvAibaEXe8qBtIUs9INC+5foK/FHD/Y        2.0
2558  677BE13BXPvAibaEXe/Ojw5gA+9jXlEdHdnjvK4V        2.0
2559  5B6968B2XPvAibaEXe9zGba8fcKEKLU7bxzsmzRq        2.0
2560  017CD572XPvAibaEXe9CFhTkHod3yQuYGl3Dx7Ko        2.0
2561  19E0EE8FXPvAibaEXe97wmuqTYuV7djoRDmkvxKL        2.0
2562  F6CF10BEXPvAibaEXe8Vh+AQMuj+NESVsTzy0/8c        2.0
2563  AA25E369XPvAibaEXe/pnXUIwMJHJhFO1g+5TPvA        2.0
2564  91061907XPvAibaEXe+n07P56kWx2Is7/sk+fJvN        2.0
2565  854BACA2XPvAibaEXe/MFNByxh05b03wVM7UTjgR        2.0
2566  026C80C5XPvAibaEXe8kGcWiFCcO6X+kqE6zW6qM        2.0
2567  CC1BE9F4XPvAibaEXe+NqszRBbPDty51v94rQVP2        2.0
2568  D544AA69XPvAibaEXe8d+xuL7f/QxAt4Q32aLRfb        2.0
2569  0597247FXPvAibaEXe+NyYotv4FWdZdBHNs2i/Tz        2.0
2570  A7AB37EFXPvAibaEXe9e953jV3NnLvoA80RNYv2Z        2.0
2571  0A8C9A4BXPvAibaEXe/9n4RXguPAYPQDYpD5T/PA        2.0
2572  5953AB21XPvAibaEXe+zCbAzes7YilyRDT2FFsyj        2.0
2573  45955949XPvAibaEXe9/83vYrk4yZqaijlL6ZDkW        2.0
2574  527C966AXPvAibaEXe/QqI5At3DBgllfI4aLLozN        2.0
2575  98CD88C1XPvAibaEXe+98B3vqZGkWJL9coZfZjOD        2.0
2576  36D640F7XPvAibaEXe9mDsFtgVHJ/mDfL0P5OcbN        2.0
2577  02B5E19DXPvAibaEXe+6DwsvcvouVduD45n92KAo        2.0
2578  F47350D9XPvAibaEXe/YiexZYoq8n8FP0R71ulza        2.0
2579  0B2AAC0EXPvAibaEXe9CJmVsz9P34qS8MDP5qhfn        2.0
2580  3526D59AXPvAibaEXe9GqQkS1wvjIRxFTurXY4N0        2.0
2581  46C3D7D4XPvAibaEXe80NXGyYVtTlkERJq09lvgo        2.0
2582  8C88FE6EXPvAibaEXe86ShnmDByrm22zyHZfDrSs        2.0
2583  D14BACDEXPvAibaEXe8CSUzma4ok0s7kddgc18YO        2.0
2584  D1798717XPvAibaEXe/QWjvABg0+vSlIbzlE3m0j        2.0
2585  555C9700XPvAibaEXe/HUuIVo8uCRy5SjHacmu89        2.0
2586  4D5FD232XPvAibaEXe+XOEV1VJ5O2wEclPqJdH7D        2.0
2587  E64CBEE4XPvAibaEXe+pfrKEojyOywunpcdatpyn        2.0
2588  DA0D2FAFXPvAibaEXe/EaMzFFtVZpBZ08/yfvr8P        2.0
2589  E8BDCD70XPvAibaEXe8zN2KKhdLFumRSso4oNxFS        2.0
2590  F8700482XPvAibaEXe+uWtCFQV0fxqnF/HE4xzaP        2.0
2591  3D94AABBXPvAibaEXe8XU1E8XgQL2L9f6WwoB2ic        2.0
2592  5BD9C85EXPvAibaEXe92HFjDDFybWxozYf9bciQb        2.0
2593  35E443D8XPvAibaEXe8jOKYsh0sA3s5U2/czWiIJ        2.0
2594  DC72A7BCXPvAibaEXe99J3nD1pBZIkYSOA+W9OcM        2.0
2595  566261C0XPvAibaEXe+HeL85QGo03a9hUZtbafsZ        2.0
2596  3BF5FDDCXPvAibaEXe9dKITjhF3qTVm6H0rizjd2        2.0
2597  FC2D6D51XPvAibaEXe+F+2tZHEiFCZwi7+hDtFZG        2.0
2598  F92FF77DXPvAibaEXe++R9hzjt1s76O2QnX+X0fd        2.0
2599  779568E5XPvAibaEXe++R9hzjt1s79WrsGQ5d4Ek        2.0
2600  ECD0FB3CXPvAibaEXe9E+yOJSz6HoWo8/+e+gTa4        2.0
2601  740A2C5AXPvAibaEXe9NdAclo3+sVy/niSBfKxtQ        2.0
2602  6BF47AC8XPvAibaEXe+BUGeEgVnB4JyRonENPufx        2.0
2603  E1E49AA0XPvAibaEXe9uaaZ/YedHVPiewa5uM8QS        2.0
2604  DDC50740XPvAibaEXe+uWtCFQV0fxrVbThib+Xc/        2.0
2605  C0834F79XPvAibaEXe/EvmuerN6w1HGYDTWudCyQ        2.0
2606  8DD2E6EEXPvAibaEXe+72vl6t/d8GaNddOCQ3/Hg        2.0
2607  265D05F3XPvAibaEXe8qgRlcblbl2m+OPn9cljQO        2.0
2608  B5BEF93FXPvAibaEXe9exxmVkEmOjQJ2B0xplyqv        2.0
2609  92272147XPvAibaEXe+9uXUaDIzyiEgtD12YVcZW        2.0
2610  49CAEA2EXPvAibaEXe9Fy2hCq9OiA2TWWInpEgrD        2.0
2611  E3F10A8EXPvAibaEXe9Y6XKwco8jye7qm3Gd9doU        2.0
2612  3A22442CXPvAibaEXe9gJazs/pDnMZFjneWIQeTm        2.0
2613  CBC03CBBXPvAibaEXe8t4cDFHKW3SYNNcG5KTGR2        2.0
2614  0F175AE8XPvAibaEXe+9v37KcInSIcX1yhIx0ss7        2.0
2615  293AD60DXPvAibaEXe+TUHAdEwrOx+CnJmDYnZhL        2.0
2616  A5BDD88CXPvAibaEXe8IXn+MV9wqkkkoWxNCMMdN        2.0
2617  EC7ABE87XPvAibaEXe9pXJcjrAt8XvnwV3kiU5pl        2.0
2618  5620CB58XPvAibaEXe8GdASsTPmlXj1JoELIu63e        2.0
2619  47D5BAFEXPvAibaEXe8Dld2HmzmH+qR0JkQNBecF        2.0
2620  94BE2CBFXPvAibaEXe+3bWVxnzRRwADoBx0JK62+        2.0
2621  23205DFAXPvAibaEXe90E3nxW1nyaQj090NDrI+u        2.0
2622  E890E973XPvAibaEXe9syD7Vfew2qUAmdsidJGcM        2.0
2623  DC313FC1XPvAibaEXe/zT99h3DDtvYOXvmuymjkM        2.0
2624  08CBD18EXPvAibaEXe+rucNIMwNDA5sDARWnhseX        2.0
2625  77E79CEDXPvAibaEXe+v5SvySgrZwOJ2iKMECUZ/        2.0
2626  C974A3F5XPvAibaEXe+4OTPvnL5gPw992xn6q9Y4        2.0
2627  B5A93F62XPvAibaEXe+sQSfsqovN9xHpRFKKgMkI        2.0
2628  476F6055XPvAibaEXe+Em+qhkpGqwEUl4byQOpeh        2.0
2629  7FBD0513XPvAibaEXe+ltCXpm838vaXT1ZHB2inA        5.0
2630  DDF19F0EXPvAibaEXe/m6K07u0dn96+TfOaK2Y3s        5.0
2631  DB450774XPvAibaEXe9PHS03bFe3hD0Qa+NoDGgz        5.0
2632  F53BA52CXPvAibaEXe9tSnfLfDeWaueQwjeqwSSh        5.0
2633  B1E1E60CXPvAibaEXe8LX4hhYKrFZmDukW2Kr76x        5.0
2634  ED9C52B9XPvAibaEXe+oAybUv81bbjsBgUnuLAOx        5.0
2635  479EBE2EXPvAibaEXe+RTFcnyQdP1gfGfoRc/nF7        5.0
2636  59D90864XPvAibaEXe84OR/xkBCpMdyO8M9H+TEw        5.0
2637  70487DCAXPvAibaEXe9sDqR+NysAHn8fxcoiFVas        5.0
2638  C9370AC9XPvAibaEXe/eCkq6I30ZSv1tTDLa2dnf        5.0
2639  C4A1C2F2XPvAibaEXe+65Is9PO18G6A7s3TWVdLj        5.0
2640  678D7DDFXPvAibaEXe+tKlY40ATmdRi+ljMSm4lA        5.0
2641  E90E1277XPvAibaEXe/wM5TrBBCDMYjuhhJRnFGL        5.0
2642  737325ADXPvAibaEXe/F8UIBT+N0T7zT5670DhFt        5.0
2643  BF4C679AXPvAibaEXe80b1fr0fH/Jv61hy6qy552        5.0
2644  31EEFFADXPvAibaEXe8BxOZlGHrYN/g8b2/ctmX8        5.0
2645  437EBCDFXPvAibaEXe8AMmr3Xq9FJxZ08fEe/gKW        5.0
2646  E402E8DCXPvAibaEXe876wt31yGPP/BDYut7u/p4        2.0
2647  3A2BE3ECXPvAibaEXe/hadw09FE3WmcRG1NdhIvW        5.0
2648  687112ECXPvAibaEXe8ciyLBP/Qla/1I7+xi3CDh        5.0
2649  49A1BA5BXPvAibaEXe9Q2McsUcINThdliToQ9eZW        5.0
2650  6FF0201BXPvAibaEXe8CSUzma4ok0qaqULSZihQx        5.0
2651  C8C4E0F7XPvAibaEXe+0Dwp+QXLoYhMctx8Zb86s        5.0
2652  9C9BB502XPvAibaEXe91UcttbrYag5HwwfofsC9O        5.0
2653  79DF0DD4XPvAibaEXe9Rxq3EQECnGd5G/qR26MNG        5.0
2654  826FA2C3XPvAibaEXe9YgNnR0JxPhZ0g/j/FBtq4        5.0
2655  AF4DB700XPvAibaEXe87cFnqlCoR2T+JwgHDCUqk        5.0
2656  0C462C74XPvAibaEXe98rLBMbW9WWdnI+g77HgqD        5.0
2657  DB5FE1BCXPvAibaEXe+pDN88/1DR4PKidTMibtkC        5.0
2658  2A8A1E92XPvAibaEXe9x0CaUg4pZoxy78IQ6wez6        5.0
2659  88EF2277XPvAibaEXe9hYalhCsDQbSfXq4xG0YaN        5.0
2660  B9CF2D72XPvAibaEXe9zES3Ot4N4SPNMTvQS/qcE        5.0
2661  84B07D27XPvAibaEXe/8X6gsb95YiEWmebrSaF9F        5.0
2662  DF932FD2XPvAibaEXe8bHoSDwbr9UuMnJlkSC+Zy        5.0
2663  A02C92D9XPvAibaEXe/9n4RXguPAYASjIqcBPLH1        5.0
2664  DBADF75BXPvAibaEXe9Veo8epKbTmEllYDnzT2vC        5.0
2665  7BEDC07CXPvAibaEXe9KWpGOh3zHl5qOD67ZCwQD        2.0
2666  D77B1380XPvAibaEXe+zrGHfAUSFaQpSAqeM2bzz        5.0
2667  41EF8A63XPvAibaEXe92CdOgj+Qa/faRc4eW+qld        5.0
2668  00ACC499XPvAibaEXe8ciyLBP/Qla4g3ka0I3o/F        5.0
2669  F24ECB8DXPvAibaEXe8qh9FRNDK+MSP8dv3PW7SX        5.0
2670  56BD6434XPvAibaEXe/a4DMmDlc8UEL9For+TSgJ        5.0
2671  5C97EE80XPvAibaEXe+e2tIVVtPhOfjOF9gwxX+j        5.0
2672  EAEA332CXPvAibaEXe9/su+qLcYDMtK7PvaLWMdM        5.0
2673  7F9BCB64XPvAibaEXe/WSo41+3xFkIxBymBcPpdb        5.0
2674  C746AD35XPvAibaEXe/S5mChdnrLm2q3zEsvbew7        5.0
2675  E3F3FD6DXPvAibaEXe8z1Io4iT8HJIqsyxTD1vIz        5.0
2676  49255D19XPvAibaEXe/nv6PZ4rt50lkxyYawzY4B        5.0
2677  EE25A9E6XPvAibaEXe8a4mdANazFZDH5DQK1A90v        5.0
2678  FCF4928FXPvAibaEXe9iOtseai5jcnyu3hno2/5g        5.0
2679  2DAA5463XPvAibaEXe9YXJ3+ew7OHFGc2QqzMPf3        5.0
2680  26BA2C03XPvAibaEXe+Y0lGmaTa/AO+2ehaTjeTz        5.0
2681  07B199C7XPvAibaEXe8NowY/Kl2AXhRCYVw9Upq0        5.0
2682  3CA2F06BXPvAibaEXe9kkdDkOt5iFu++oQ526GXI        5.0
2683  CB548A33XPvAibaEXe+T+pdYLenbrh/MSouM7hbM        5.0
2684  675617C3XPvAibaEXe9rbQR8nwnz2Ffm+aNEIdyX        5.0
2685  7EE1CD5FXPvAibaEXe/EKiY6F5FD8IAVxFaXKRNs        5.0
2686  F0DDE2E8XPvAibaEXe9tVd6vhP62h6WlGDFtlvFt        5.0
2687  4C91FC64XPvAibaEXe92Umf5pb/ttn5JQ3WRiOHb        5.0
2688  C6F46501XPvAibaEXe+W0wzzSkKF2mLF4C3u0lkW        5.0
2689  8D203797XPvAibaEXe99j2P15eeB0yiSFSPp6gj3        5.0
2690  A555843FXPvAibaEXe88UewilValgCdn3PFv7Eck        5.0
2691  256CAF61XPvAibaEXe8e8TJXhGRqkEsxlP7P0zFV        5.0
2692  2051316CXPvAibaEXe8y6/RMXZRwBSpb0VHJadCX        5.0
2693  F6CF10BEXPvAibaEXe8Vh+AQMuj+NESVsTzy0/8c        5.0
2694  AA25E369XPvAibaEXe/pnXUIwMJHJhFO1g+5TPvA        5.0
2695  854BACA2XPvAibaEXe/MFNByxh05b03wVM7UTjgR        5.0
2696  E5B72901XPvAibaEXe/04IiIK7okBVX65TwUbxSQ        5.0
2697  8B6B6B01XPvAibaEXe9puzAyruoCKY5SIobrPyeV        5.0
2698  555C9700XPvAibaEXe/HUuIVo8uCRy5SjHacmu89        5.0
2699  F731CB9DXPvAibaEXe8XU1E8XgQL2LgKqutu93os        5.0
2700  4D5FD232XPvAibaEXe+XOEV1VJ5O2wEclPqJdH7D        5.0
2701  E64CBEE4XPvAibaEXe+pfrKEojyOywunpcdatpyn        5.0
2702  26D13F40XPvAibaEXe9MpQ5WhbYsPjjnjvfeoMJ6        5.0
2703  35E443D8XPvAibaEXe8jOKYsh0sA3s5U2/czWiIJ        5.0
2704  81B56530XPvAibaEXe9syD7Vfew2qe4lDpkMCxew        5.0
2705  CDC5F17AXPvAibaEXe9dY3g0Pb8XoMZ8n4VQ+rNz        5.0
2706  C0834F79XPvAibaEXe/EvmuerN6w1HGYDTWudCyQ        5.0
2707  83C48DC7XPvAibaEXe8IXn+MV9wqkkAswm7lxemz        5.0
2708  70E6860FXPvAibaEXe8AK9BJf0PqfPqpG9mpVS2V        5.0
2709  CBC03CBBXPvAibaEXe8t4cDFHKW3SYNNcG5KTGR2        5.0
2710  ABE403F3XPvAibaEXe8zi/ZLIzSiuCcf7eh0896P        5.0
2711  73AB42FBXPvAibaEXe+LaXEhdAaoNN8kHcuz6VWe        5.0
2712  A5BDD88CXPvAibaEXe8IXn+MV9wqkkkoWxNCMMdN        5.0
2713  BAFEFADEXPvAibaEXe8Pc6kxKoLNaWucSNjkift+        5.0
2714  19220744XPvAibaEXe9cUsS4F6r57fg/S/HCyNTC        5.0
2715  7A8986F1XPvAibaEXe8+Y7C9z9gIQ9ytSF4hYGk4        5.0
2716  D9B39BA6XPvAibaEXe+ywvHYTnIXuOL9P7zUqeNl        5.0
2717  F7CD8361XPvAibaEXe/N50hRf+Du8SYr3oJdS5Xy        5.0
2718  1CB6BE2BXPvAibaEXe+DUF+563kBvVnx1Z39pSj8        5.0
2719  47D5BAFEXPvAibaEXe8Dld2HmzmH+qR0JkQNBecF        5.0
2720  DC313FC1XPvAibaEXe/zT99h3DDtvYOXvmuymjkM        5.0
2721  4EF61D4EXPvAibaEXe9A8avg2Xms/zKwCfbKnTpz        5.0
2722  77E79CEDXPvAibaEXe+v5SvySgrZwOJ2iKMECUZ/        5.0
2723  42F00DCFXPvAibaEXe+pX9RZhc1jhpkO3b8v15wU        5.0
2724  A78DB0A7XPvAibaEXe8pr9LKErUcFccIBSJ6B04w        5.0
2725  31F0B8C9XPvAibaEXe91kmICrkek2m3ZgFKALQoG        5.0
2726  E2A54B84XPvAibaEXe8ZCBSJNuktiFDmfkbZOMfm        5.0
2727  91BF9650XPvAibaEXe+69U8I0R94EUA0eX/wKmb+        5.0
2728  4A223D49XPvAibaEXe+xxRCacZP96myvp3MKYFxv        2.0
2729  587117ECXPvAibaEXe+TioGOAQy/3xs11Ox39j0M        2.0
2730  66A9B4FBXPvAibaEXe+BUGeEgVnB4P/PVf37xsAo        2.0
2731  9E302D16XPvAibaEXe8AMmr3Xq9FJ67Yqt1Ub3Mo        2.0
2732  9AFD5C84XPvAibaEXe//Z7+CGDQLoHD+WJYS0Uvi        2.0
2733  28BA21D6XPvAibaEXe90ZzX2oanjjs5FxU3lHZPx        2.0
2734  1EDA2DA4XPvAibaEXe8lzySxhHiT0RqGwGqh/eBg        2.0
2735  232946CFXPvAibaEXe/JhqMYLzzrR02+yvZ+pT+i        2.0
2736  9FA1AF84XPvAibaEXe9JJ0DEqozv6EHh9Z2rxnaz        2.0
2737  36EFD430XPvAibaEXe9zGba8fcKEKJZz/WjQKnhb        2.0
2738  41E95C45XPvAibaEXe88L+jeN4TPm4VR5HvH4X8t        2.0
2739  DC88F693XPvAibaEXe/Z2D1Qs9UWoCNG/k5FncYF        2.0
2740  820D4115XPvAibaEXe9ylQoUTvcEfwP2rEGTClQb        2.0
2741  320B951DXPvAibaEXe8b36blNCVklRDcN/awSZaK        2.0
2742  8A3C61C3XPvAibaEXe8kGcWiFCcO6cCaPR2fU+qE        2.0
2743  2FC1D165XPvAibaEXe/8rx8cZm8Qsd1BKDKQ2GnL        2.0
2744  A1F1A0EBXPvAibaEXe9Vh8FJ4R+4oQmcC3pUVfWh        2.0
2745  74FAA182XPvAibaEXe/ESOA28kZtDiYIeykRfinM        2.0
2746  D5CCC0F0XPvAibaEXe9xLM9bjmqfKXYiG4DipNYr        2.0
2747  262628CCXPvAibaEXe97q47CdxnNZIi4AOvaSLHr        2.0
2748  1C441061XPvAibaEXe/3Z2K7mhA0JWvZ1ODngPiY        2.0
2749  61F8125DXPvAibaEXe9RBNO8knVPD1aCyE6IUBmm        2.0
2750  FA7CB31DXPvAibaEXe/Q6C3BndaQUGiZ+OgRkshk        2.0
2751  CC3AD1E9XPvAibaEXe+F+2tZHEiFCfNt8GFoThy6        2.0
2752  180E4E80XPvAibaEXe9mjVtuyMJi9GJtzpwv947h        2.0
2753  D213ED0DXPvAibaEXe9ESTQu9OOcIEH3IzPs1iiR        2.0
2754  79A8C079XPvAibaEXe/lyY7+7E9oi82rS57hxGU5        2.0
2755  48F5B603XPvAibaEXe+pZU+khqBqysRQvPC+IuSI        2.0
2756  C39EC9E7XPvAibaEXe/d4nFnIhFaQm1KX1sm6B+1        2.0
2757  C34CB14FXPvAibaEXe+dVXFbWVwKlYf2u7qop3EE        2.0
2758  7A0295BEXPvAibaEXe9GqQkS1wvjIY8Eyvx1K5/i        2.0
2759  9D86B13DXPvAibaEXe8lzySxhHiT0WPIM25OzMa/        2.0
2760  3547A27CXPvAibaEXe/JRR+qhRXMm5LPIyI46Mn9        2.0
2761  F96F26BDXPvAibaEXe/7jtQOMcuJ+4eFmj09T6qD        2.0
2762  445B1666XPvAibaEXe/eRksRS1wGeLe60/QESEnH        2.0
2763  8B9DD5F1XPvAibaEXe/7VXm0xgXldIyNDzaf66fA        2.0
2764  DA80B340XPvAibaEXe8at9gGXzJnLyGN7FYOAOGc        2.0
2765  01C3E360XPvAibaEXe8aLAPPdCF+aQPfV91kc+Cb        2.0
2766  1E7CAD17XPvAibaEXe+uWtCFQV0fxthjRK/B02HM        2.0
2767  BE1A9ABEXPvAibaEXe92Umf5pb/ttjv+Q4aigMmx        2.0
2768  05FB97EDXPvAibaEXe+1n9LzrMgTlwuXodOCiGW6        2.0
2769  22202B9FXPvAibaEXe9Rxq3EQECnGYGcMkgOfwOv        2.0
2770  742B1E08XPvAibaEXe8qxKHWIxudAKb8Z+/8qlwv        2.0
2771  327B0751XPvAibaEXe/9LBBkdbcCWFBbfXlCb9MQ        2.0
2772  86D95EF1XPvAibaEXe+wnAHzeNC8Ynp88+vLxS5+        2.0
2773  D95DCCC6XPvAibaEXe+GGliW+AfAjPVsAFjRjr1S        2.0
2774  AD2D3287XPvAibaEXe/X5qOvA9deFUS0IY8Er9pu        2.0
2775  2D73D29DXPvAibaEXe8f56j3W7C5xpu9Ayea6tcb        2.0
2776  4813A23DXPvAibaEXe/waquVAMA8TuWB0ajB6F8a        2.0
2777  E9663523XPvAibaEXe9NZBs7fjgAwcNVPcSAOMdb        2.0
2778  5B7E86ECXPvAibaEXe+fPSOag5leTemrjmHmhVHy        2.0
2779  97DB8803XPvAibaEXe9d+rE/yvWoKGk9ziLro4mY        2.0
2780  013DFC27XPvAibaEXe9KWpGOh3zHlxPSiJ5QTA8b        2.0
2781  24500250XPvAibaEXe+dVXFbWVwKlZWoN4Lv4G5x        2.0
2782  04CA893BXPvAibaEXe/SouBySQ9Uj8rioKR0JeF/        2.0
2783  F473C1ABXPvAibaEXe/jd8ghaf1GTNdb+cfjD9JK        2.0
2784  0E3CC85BXPvAibaEXe/7YVAxOsMwOq19C4IZbCNV        2.0
2785  D0067B90XPvAibaEXe9F+oU8wuNbqC85Gv/05gSU        2.0
2786  4125A39CXPvAibaEXe9FHRfjQvHQkTjETZ+oAYjM        2.0
2787  08782EBCXPvAibaEXe9zVZKaStZ09MV9x0bcbU8i        2.0
2788  81A16E02XPvAibaEXe98rLBMbW9WWZYzqql2Y9VW        2.0
2789  E42E9B51XPvAibaEXe97yKczitj7gnLErDmUHlEC        2.0
2790  C417282BXPvAibaEXe+SrLE9JUD3pJ8L3ybcUv+j        2.0
2791  72C18F32XPvAibaEXe9pz/hgBFL5ILG7SOWQGRft        2.0
2792  C545722AXPvAibaEXe9E+yOJSz6HocEJuG3fpsq5        2.0
2793  D1CF0680XPvAibaEXe8y6/RMXZRwBRNEtSk1fgWN        2.0
2794  7AFD7535XPvAibaEXe8y6/RMXZRwBXIh5HEXe283        2.0
2795  DA872026XPvAibaEXe/wvgrdNVCyf2uA0Nmul7oQ        2.0
2796  2B825CEBXPvAibaEXe+BUGeEgVnB4J2reWP3zJfy        2.0
2797  D8C5E6AEXPvAibaEXe+XQbEHiLBIRcv+3+egRe9e        2.0
2798  465C97DCXPvAibaEXe9ggqkCdMDyeHNNaGK2sNUx        2.0
2799  17FFC7CCXPvAibaEXe+wCRIlhV+1XwB91jd9TqF4        2.0
2800  0DD35B47XPvAibaEXe80b1fr0fH/JjIAGw7YBF/0        2.0
2801  5BB2616AXPvAibaEXe+dJypLAXKUX+vZTES+v3MA        2.0
2802  D2EB1EB6XPvAibaEXe9Hp2TeoSwCGebpfL629QyM        2.0
2803  2DA6FC78XPvAibaEXe8l2SPBJihvxX4b38rruk85        2.0
2804  004E12B9XPvAibaEXe81r7KrCH0uc0uxBtoBw4BG        2.0
2805  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4        2.0
2806  9643C165XPvAibaEXe/0W4kDBen431/6V6M74k/g        2.0
2807  B507B5D1XPvAibaEXe/HZd2ATF04tBDESiZA5/UN        2.0
2808  17C0BA29XPvAibaEXe+g4B5cywZjwdHw/yKkfaHU        2.0
2809  7CD02A9FXPvAibaEXe+g4B5cywZjwcj8TsG91YaQ        2.0
2810  0CF74531XPvAibaEXe8x4DBJAYNqX7MmOvd3RNwO        2.0
2811  DF9F19C7XPvAibaEXe/7VNok06ub0JvLoH9dyvXN        2.0
2812  008BC94CXPvAibaEXe9/w7qCPr4fx1vMkMDBbGR/        2.0
2813  57D87DB5XPvAibaEXe+Ee/bNoyDJskfGApkK8T+o        2.0
2814  E6963FB3XPvAibaEXe/XOPUzjjLegHdSw5mPkBXa        2.0
2815  74325201XPvAibaEXe8y6/RMXZRwBdjV4+4KROgH        2.0
2816  6175A313XPvAibaEXe86krjHGvaiWwI8pzNJ+7Zl        2.0
2817  8C053506XPvAibaEXe8VziDgYa0u7kXETb28eD9J        2.0
2818  0BAF3540XPvAibaEXe9HXpb1PepyFQeHHIpoFKlX        2.0
2819  325E5A25XPvAibaEXe9PDEhlfOA/z55ir9S9Xy8y        2.0
2820  02BF7901XPvAibaEXe81w9eVvyp+l/OBpi+Ps6nu        2.0
2821  BA859156XPvAibaEXe+cHxM5cHw4WkpeapAn73Y4        2.0
2822  B0170AACXPvAibaEXe9TMBdu4IUyd43pUEcpgIf5        2.0
2823  5D284A3DXPvAibaEXe9p78qxnH96y+U6SLz2uzt8        2.0
2824  B8204A58XPvAibaEXe/d4nFnIhFaQtp/+y0BKQUB        2.0
2825  1E43797CXPvAibaEXe/81GDNmtxKsQIri7NYICsC        2.0
2826  62BFFE2EXPvAibaEXe/9ugxkUZcLfPe37BSUxSyd        2.0
2827  2ED165A9XPvAibaEXe/eRksRS1wGeJQzNqtERAKg        2.0
2828  FAF7008FXPvAibaEXe/Z2D1Qs9UWoLz0wvrvwm+Q        2.0
2829  21478CA5XPvAibaEXe87069oyWO+Ia90rjo5SvVw        2.0
2830  AE624A96XPvAibaEXe/8dEMQ5HsLlwvZ5/2Rqe9y        2.0
2831  B04176ADXPvAibaEXe+pfrKEojyOyy/jsqKQmizY        2.0
2832  CB8BCA7FXPvAibaEXe88EN6DQQEtSQ7yKpQCGuhQ        2.0
2833  FF47BE24XPvAibaEXe+g4B5cywZjwcX/S5XMQp36        2.0
2834  6EC9B467XPvAibaEXe+g4B5cywZjwZVD7kCf00e1        2.0
2835  BB3DB683XPvAibaEXe+g4B5cywZjwSIIdpUdzbuP        2.0
2836  238E4A5CXPvAibaEXe9mpn5IvDinR+4dnES1zYX7        2.0
2837  51164227XPvAibaEXe95BgJyC1XgNTdcv0Dg5gvu        2.0
2838  82CDD006XPvAibaEXe9WGATIMl02LLfwAtGJNJ7j        2.0
2839  9D14729AXPvAibaEXe8WdGcsQTF3yLZ3B0b1W9X0        2.0

# Xử lý dữ liệu

### Cột mssv

In [12]:
# kiểm tra dữ liệu khuyết
missing_count = df['mssv'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'mssv': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'mssv': 7

In [13]:
# Loại bỏ các cột bị khuyết
df.dropna(subset=['mssv'], inplace=True)

### cột tinhtrang

In [14]:
# Số lượng dữ liệu khuyết
missing_count = df['tinhtrang'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'tinhtrang': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'tinhtrang': 0

In [15]:
# Chuyển đổi cột 'namsinh' sang kiểu số nguyên để loại bỏ phần .0
df['tinhtrang'] = df['tinhtrang'].astype('Int64')

### cột lydo

In [16]:
# Số lượng khuyết
missing_count = df['lydo'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'lydo': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'lydo': 0

In [17]:
# Xóa khoảng trắng thừa trong cột "lydo"
df['lydo'] = df['lydo'].str.strip()  # Xóa khoảng trắng đầu và cuối
df['lydo'] = df['lydo'].str.replace(r'\s+', '', regex=True)  # Xóa khoảng trắng thừa giữa các từ

In [31]:
# Loại trừ các cột 'A', 'D'
exclude_columns = ['mssv', 'ngayqd']

# Chỉ xử lý các cột kiểu object và không nằm trong exclude_columns
for column in df.select_dtypes(include=['object']).columns:
    if column not in exclude_columns:
        df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%\-]", '', regex=True)

## cột hocky

In [18]:
# Số lượng khuyết
missing_count = df['hocky'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'hocky': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'hocky': 0

In [19]:
# Chuyển đổi cột 'hocky' sang kiểu số nguyên để loại bỏ phần .0
df['hocky'] = df['hocky'].astype('Int64')

## cột namhoc

In [20]:
# Số lượng khuyết
missing_count = df['namhoc'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'namhoc': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'namhoc': 0

In [21]:
# Chuyển đổi cột 'namhoc' sang kiểu số nguyên để loại bỏ phần .0
df['namhoc'] = df['namhoc'].astype('Int64')

## cột ngayqd

In [35]:
# Kiểm tra giá trị khuyết
missing_count = df['ngayqd'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'ngayqd': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'ngayqd': 2

In [36]:
# Xử lý giá trị khuyết bằng các điền mode
df['ngayqd'].fillna(df['ngayqd'].mode()[0], inplace=True)

<ipython-input-36-f1f1f70cfc04>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ngayqd'].fillna(df['ngayqd'].mode()[0], inplace=True)

In [37]:
# Chạy lần 2
df['ngayqd'].fillna(df['ngayqd'].mode()[0], inplace=True)

In [38]:
# Thay đổi dữ liệu về định dạng chung dd/mm/yyyy
df['ngayqd'] = pd.to_datetime(df['ngayqd'], errors='coerce').dt.strftime('%d/%m/%Y')

<ipython-input-38-6908411bedb3>:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['ngayqd'] = pd.to_datetime(df['ngayqd'], errors='coerce').dt.strftime('%d/%m/%Y')

### Kiểm tra lại Dataframe đã sửa đổi

In [32]:
df.head(100)

,mssv,tinhtrang,lydo,hocky,namhoc,ngayqd
0,98247E19XPvAibaEXe93PEySAJOVkxsz+HIviyYJ,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
1,52B1CC2DXPvAibaEXe+kwIr/VXjl0w+FyuW1abQ7,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
2,5666EAF4XPvAibaEXe+Z7KfNHYLttJaLI+SH+DpO,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
3,682C32E0XPvAibaEXe/Bn5cQSu92WX0DcIKdud8D,2,bịcảnhcáovìđtb2họckỳliêntiếp<4,2,2016,18/04/2017
4,7901D3A9XPvAibaEXe+6MN9FoW2mqYEmruXXBNsS,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
5,82D67FF0XPvAibaEXe9Bx5CZuIA9z+ymYnRBj6Fr,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
6,FBD9AAFEXPvAibaEXe+5oCRQPDKXsjh0OTYpdD2Y,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
7,B47BC5E8XPvAibaEXe/H1VZJBzJAwmY5aGwFIvk2,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
8,7FBD0513XPvAibaEXe+ltCXpm838vaXT1ZHB2inA,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
9,C3E0BACEXPvAibaEXe8zBeLfIMmoBC4sDuuDh1j3,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
10,BAC0D992XPvAibaEXe/dMvqGUzyBHM+Z5FUq42cm,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
11,A5CFC3EAXPvAibaEXe8v1/72rbobbQBhkDh9w0n8,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
12,FDCA1F81XPvAibaEXe+xw+0gOjOR0FlMrNx/+TZG,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
13,C1F37059XPvAibaEXe9cYfl6D6BtPG7HzaS511bz,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
14,B2B5D9C3XPvAibaEXe/Uev7j/8EzmXD71ZVL116W,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
15,C5D19041XPvAibaEXe+NJiMjcH3vhGZBbbWixTpF,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
16,BFAB0BC0XPvAibaEXe+PAOVcd+LnOX59zGGn3cV1,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
17,DCA94B13XPvAibaEXe9RV3kg6cpLDHjSSrCU5mso,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
18,55E029BAXPvAibaEXe8SXrohzbXmS8MZUqnd4qx0,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
19,B721CE15XPvAibaEXe/WuJYGMdaNyLnzWcA+ZeDw,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
20,18BC3150XPvAibaEXe+RaLErOlzghWzZvcuDuYjh,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
21,E19C669FXPvAibaEXe/lyY7+7E9oi1Z9M6xWsk94,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
22,3788C7A4XPvAibaEXe/81GDNmtxKsfT2ovFuIAkG,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
23,3E756495XPvAibaEXe9P07hcrvmhCa0nLHGm6qSN,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
24,80790C23XPvAibaEXe83V/kFvw2bBdHxAZUKwYd8,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
25,3E479342XPvAibaEXe+kwIr/VXjl01D1BeeuKZAN,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
26,F498E5FEXPvAibaEXe9JDlHA4z2GHBZXhsR8PR1r,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
27,B2816B7BXPvAibaEXe/YKN5ysyYL7MS3vlfPnRU+,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
28,313A0C3EXPvAibaEXe9FiaSoce50DK2qcrsEDi/O,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
29,79F1E4DFXPvAibaEXe9MLbI3cCq2BHgHnnweUs+t,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
30,A31BDC0AXPvAibaEXe/Dy4K4yiQpOP0/iCEjMzqM,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
31,CD4BB846XPvAibaEXe/BqA0y8R3TRQX6Z3Fs2mNg,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
32,3EC4C95DXPvAibaEXe+Xxbs4kvH/k298KMqSjXz6,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
33,47D6DC8BXPvAibaEXe8VdV75E6kcrmlVENOwEPKK,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
34,48A22F9BXPvAibaEXe8oOckqmsrcbcSOt0BVGgjK,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
35,2D57A854XPvAibaEXe8WdGcsQTF3yDJk01mdVJzW,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
36,A8F153C6XPvAibaEXe9cYfl6D6BtPHGCj6z6qL7j,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
37,C386EE73XPvAibaEXe+HeL85QGo03ZNOv3tVjTb1,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
38,F0A647A5XPvAibaEXe+VDSoAYozpwxu4EUSrr8sK,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
39,AAF15D98XPvAibaEXe/X5ZhFzI36lAEFPRLVuRrt,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
40,882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
41,FB9D4C87XPvAibaEXe9W7fV/x7qyQPlsuf/c/sw3,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
42,373C7479XPvAibaEXe++bDwPCni17uzurhujbpFF,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
43,FE176735XPvAibaEXe+1P/4gNbgreQ94npTP4/sD,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
44,85AB9A11XPvAibaEXe+cD1fKElqxL3rmZzDf2Nuw,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
45,E934BCD3XPvAibaEXe86736b6Ol+/MLJ5vOrqV8U,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
46,9A2B00E7XPvAibaEXe+kwIr/VXjl0y8cEqB0jdRP,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
47,061A670AXPvAibaEXe9fafwYRU+NpkvJumT/CzS9,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
48,280C7EA5XPvAibaEXe/Lh6v1XxTKJQPUP8Q5F4WX,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
49,DC3809C1XPvAibaEXe+suUpvSAu/oxffaDJ7qIWv,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
50,B324AA62XPvAibaEXe9h45naFhFKYnJpwCUzzMDr,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
51,40E6B6E5XPvAibaEXe+BHZkA9XgGXRJzAFhTNzBm,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
52,BAD275EDXPvAibaEXe+6MN9FoW2mqadHvO5K6fIQ,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
53,6DCCEA04XPvAibaEXe/+PcSgI7YkeTfztD9kDzr/,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
54,97C2C03FXPvAibaEXe+PhKfQb0+XJ2fDNXQs9az5,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
55,1B290682XPvAibaEXe9HKUC7sboLjhj6Skar7Eh0,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
56,50B2DD22XPvAibaEXe+pDN88/1DR4Nnc7Q9fHda/,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
57,98857340XPvAibaEXe+pDN88/1DR4IgAxOQlHkuX,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
58,59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
59,AC17A2EBXPvAibaEXe+ltCXpm838vTWWVUsJrTsd,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
60,0F633F90XPvAibaEXe9o/lUQXb5f/3wDMeffVbKe,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
61,789BE82DXPvAibaEXe/NRwqjPAC0MH7Z5B/F4F4Y,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
62,F0DA4E5BXPvAibaEXe88UewilValgCEO6Q/IE/fA,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
63,005116E7XPvAibaEXe8VdV75E6kcrk07Zn1wf/T8,2,bịcảnhcáo\nvìđtb2họckỳliêntiếp<4\nvìđónghọcphítrễ,2,2016,18/04/2017
64,68A9F6E0XPvAibaEXe+Wjq/eoSKNhSFFR3HqFJZ7,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
65,0A275EF0XPvAibaEXe9j81k8MH0oJ07F7M1SwTm7,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
66,7A877B93XPvAibaEXe/dMvqGUzyBHKb1SK3FzsOv,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
67,FF1F91C6XPvAibaEXe9QJDM9nE85iG8enJ2bG8BP,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
68,E8B314E9XPvAibaEXe/GP74oAJxkeJbsEk9Q36Ww,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
69,62A950A6XPvAibaEXe8yzZ/8QUtgdv/TDzLoF+yc,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
70,14F36C86XPvAibaEXe+E+n9mGyneJx876KeeY376,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
71,F7AEF87FXPvAibaEXe9tSnfLfDeWaq2I5IvDc2nY,2,bịcảnhcáovì\nvìđtbhọckỳ1<3\nvìđónghọcphítrễ,2,2016,18/04/2017
72,B2895E1BXPvAibaEXe+k2gCw0RZzlS5qI5KJx1wi,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
73,C545722AXPvAibaEXe9E+yOJSz6HocEJuG3fpsq5,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
74,F451D99AXPvAibaEXe+fPSOag5leTcWuR+r937fj,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
75,7AFD7535XPvAibaEXe8y6/RMXZRwBXIh5HEXe283,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
76,891F156CXPvAibaEXe/wvgrdNVCyf5jLOkWpgXlY,2,bịcảnhcáovìđónghọcphítrễ,2,2016,18/04/2017
77,FF9BCACDXPvAibaEXe9a9WHB728zIL656Mdf6zEw,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
78,8405AB7AXPvAibaEXe8CSUzma4ok0sCCokPnZj1+,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
79,387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
80,342257EAXPvAibaEXe/aqMXYDLKHR3SjNQBzsJDf,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
81,B4DF0E0BXPvAibaEXe9lF2o7VejWNjZnP3XERPYN,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
82,C1BB7059XPvAibaEXe8ydgsBCmjqA7/XEotXcjT3,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
83,E670C383XPvAibaEXe/zHDidEgqCTiLQarAqK+wV,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
84,FCF45D05XPvAibaEXe+PhKfQb0+XJ1k496G8BNe/,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
85,D5AC7162XPvAibaEXe/caEx4rNa5qUnjFyjC1j1t,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
86,9DE3AA6DXPvAibaEXe+NmgQbVGcjJ/cDB85eYXzc,2,bịcảnhcáovìđtb2họckỳliêntiếp<4,2,2016,18/04/2017
87,387D399AXPvAibaEXe/S5mChdnrLm+CxikMaVKbO,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
88,91090A58XPvAibaEXe/twRH8x8eyg72wDhVxBSqI,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
89,34D2366BXPvAibaEXe9hSzSdeSAT0raoFevApL9Y,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
90,8A09D1DFXPvAibaEXe/KMtCr6bHausp9EaTq9IQh,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
91,AD4F8F98XPvAibaEXe+Wjq/eoSKNhWAfdL7IH9lt,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
92,D1D177EAXPvAibaEXe8dEe4TA8wgHwsqNRzsv5E9,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
93,FDA9DEA1XPvAibaEXe+TQJLvJOj4Bbq7Gu36vTA9,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
94,231393B0XPvAibaEXe+xw+0gOjOR0PK5J6OAawo7,2,bịcảnhcáovìđtb2họckỳliêntiếp<4,2,2016,18/04/2017
95,1A57D711XPvAibaEXe8dZIB3odxynish6zKkFVzW,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
96,8136D1C7XPvAibaEXe9RBNO8knVPDyLHjWaMh4f3,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017
97,18D2231EXPvAibaEXe8LX4hhYKrFZihlc2c5X1wP,2,bịcảnhcáovì\nđtbhọckỳ1<3\nđónghọcphítrễ,2,2016,18/04/2017
98,6EA715E1XPvAibaEXe9ESTQu9OOcIFrpC/9jWYjR,2,bịcảnhcáovì\nđtb2họckỳliêntiếp<4\nđónghọcphítrễ,2,2016,18/04/2017
99,E3B61324XPvAibaEXe+E43ovk5Cnp3VN23jDQPXu,2,bịcảnhcáovìđtbhọckỳ1<3,2,2016,18/04/2017

### Lưu dữ liệu đã làm sạch

In [40]:
df.to_excel("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/08.XLHV.xlsx", index=False)

In [39]:
missing_values = df.isnull().sum()
missing_values

mssv         0
tinhtrang    0
lydo         0
hocky        0
namhoc       0
ngayqd       0
dtype: int64