# Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Thiết lập để hiển thị tất cả dòng và cột dataframe

In [3]:
pd.set_option('display.max_rows', None)  # Hiển thị tất cả các dòng
pd.set_option('display.max_columns', None)  # Hiển thị tất cả các cột

# Đọc & xử lý dữ liệu

In [4]:
data_path  = "/content/drive/MyDrive/Data/Data_clean/EDA"

In [5]:
# Load dữ liệu
df = pd.read_excel(data_path + "/diem_Thu_EDA.xlsx") # Có thể thay đổi theo shortcut trên drive

In [6]:
# Loại trừ các cột 'mssv'
exclude_columns = ['mssv']

# Chỉ xử lý các cột kiểu object và không nằm trong exclude_columns
for column in df.select_dtypes(include=['object']).columns:
    if column not in exclude_columns:
        df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%\-]", '', regex=True)

In [7]:
df.head(10)

,mssv,mamh,sotc,hocky,namhoc,diem_hp,trangthai
0,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,carc1,3,1,2006,2.0,2
1,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,csc21,5,1,2006,5.0,1
2,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,eng02,0,1,2006,5.5,1
3,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,mat21,4,1,2006,6.5,1
4,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,pedu1,0,1,2006,7.0,1
5,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,phil2,5,1,2006,8.0,1
6,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,phy01,3,1,2006,6.5,1
7,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,dbss1,4,2,2006,6.5,1
8,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,dsal1,4,2,2006,3.5,2
9,2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc,eng03,0,2,2006,4.5,2

# Kiểm tra dữ liệu bị khuyết

In [8]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv           0
mamh           0
sotc           0
hocky          0
namhoc         0
diem_hp      614
trangthai      0
dtype: int64

In [9]:
# Tỷ lệ giá trị thiếu
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)
print("Tỷ lệ giá trị thiếu (%):")
print(missing_percentage)

Tỷ lệ giá trị thiếu (%):
diem_hp      0.091061
mssv         0.000000
mamh         0.000000
sotc         0.000000
hocky        0.000000
namhoc       0.000000
trangthai    0.000000
dtype: float64

In [10]:
# Kiểm tra số dòng chứa giá trị null
num_null_rows = df.isnull().any(axis=1).sum()
print(f"Số dòng chứa giá trị null: {num_null_rows}")

Số dòng chứa giá trị null: 614

In [11]:
# Lọc các dòng có chứa giá trị null
rows_with_null = df[df.isnull().any(axis=1)]
print(rows_with_null)

                                            mssv      mamh  sotc  hocky  \
138351  FC6E6027XPvAibaEXe97+rZxicl8Fu8rXx8+3RIa     se106     4      2
138354  9680CFF1XPvAibaEXe9Utyqc/TjnrehWvw0N65ZO     se106     4      2
138361  2ECE1A4AXPvAibaEXe/lSUoyv6mJfBgqqiRF5Um6     se106     4      2
138362  C212647BXPvAibaEXe9vhdgqp7cHT6XRtkgyoELO     se106     4      2
138366  BE43281FXPvAibaEXe9mL9UZSYh9+UZeCxtJ80lP     se106     4      2
138391  B6401893XPvAibaEXe/D9W4zOC/eDXAH+w5Giba8     se106     4      2
138434  18930CE9XPvAibaEXe+ot3jpjNDg2jpH+9G15DWM     se106     4      2
138973  172DCFADXPvAibaEXe/x2lXf9NFd48GFwYyxQSlA     se312     4      2
139092  4D210364XPvAibaEXe/rGCwvCZJDhhlJmnkTfwMs     se325     4      2
139093  06592550XPvAibaEXe95VWPeptLbJwVJDTgzyDTf     se325     4      2
139144  3355BCF5XPvAibaEXe9r+rIQSMuJbsRDWauLAZrT     se331     2      2
139146  11CD259EXPvAibaEXe8lbOtqETWafvVBJFI5V/O+     se331     2      2
139148  F2049C10XPvAibaEXe/U2f1dnGSXPQtkptTMg/fp     se331     2      2
139149  4A825A4AXPvAibaEXe9KfSJc58cZCMOhJcdrLpnn     se331     2      2
139175  C6545BC5XPvAibaEXe/CiA6lhXdOJGe3YfIRunvJ     se331     2      2
139187  C1663CBEXPvAibaEXe9fmk+IGAumNeGBRNlNuK5s     se331     2      2
139189  6455D88DXPvAibaEXe9fmk+IGAumNRame+T8o1HU     se331     2      2
139191  8A2158D5XPvAibaEXe87T7ptYh7OSH2GoHjV1isp     se331     2      2
139279  4D210364XPvAibaEXe/rGCwvCZJDhhlJmnkTfwMs     se418     3      2
139280  3355BCF5XPvAibaEXe9r+rIQSMuJbsRDWauLAZrT     se418     3      2
139281  06592550XPvAibaEXe95VWPeptLbJwVJDTgzyDTf     se418     3      2
139285  11CD259EXPvAibaEXe8lbOtqETWafvVBJFI5V/O+     se418     3      2
139308  26BB218CXPvAibaEXe+6B/SWZOkhUxUePOJo7mJx     se418     3      2
139310  3F6A2F01XPvAibaEXe/RQ4XonzCCeqPBjE2vT6gU     se418     3      2
139312  C29DAFF8XPvAibaEXe96MNa+AOhrt1XyTkotNZ7S     se418     3      2
139321  F90A8186XPvAibaEXe9gNdYxxH49oXelP6pXTzWH     se418     3      2
139327  722DE6E4XPvAibaEXe9QnRVgwBqH8uLTI0nID5i6     se418     3      2
139334  1E939130XPvAibaEXe9qFVjW5nX81hji9oLp1kve     se418     3      2
139351  EC53A837XPvAibaEXe8LS2f+PMhnWTTZakHmhtFi     se418     3      2
139358  77489354XPvAibaEXe+PQV3+n6192XuDPXI2lQNM     se418     3      2
139360  13D209DBXPvAibaEXe9Utyqc/TjnrcDjFNixyYzR     se418     3      2
139377  52BC7E75XPvAibaEXe+tsOVF0knUh4oqq2/aTF8R     se418     3      2
139378  B7F38A0AXPvAibaEXe+tsOVF0knUhyI8LLKkPh4G     se418     3      2
139411  F4204FAEXPvAibaEXe+jBiD6VkzWzCbjU4zhLLoT     se418     3      2
139441  CF5C418EXPvAibaEXe9iZHaMcYEyspeRJ7S3snlB     winp1     4      2
139444  13D209DBXPvAibaEXe9Utyqc/TjnrcDjFNixyYzR     winp1     4      2
139461  F027C3F4XPvAibaEXe9zRIqN26w0Bz0VC5K0U8Fw     winp1     4      2
139462  77D91F55XPvAibaEXe9zRIqN26w0B3OcZbCEvRY0     winp1     4      2
139464  1140C37BXPvAibaEXe+S5N09Nmtxa709Im07duJi     winp1     4      2
139465  5B83F489XPvAibaEXe/nzVfFzcfk2G6N165o8WeV     winp1     4      2
139471  36C44FA3XPvAibaEXe9B4DABGWTuPQC1WKvorGfO     winp1     4      2
139474  7B4679EFXPvAibaEXe+G0GCP+fnj3vRb4aI5ZIpY     winp1     4      2
139480  ED51A3A8XPvAibaEXe9poi1GJx57CdKwLDqgl/yK     winp1     4      2
139481  8B4DB17FXPvAibaEXe9poi1GJx57CTcHFstw6fGH     winp1     4      2
139486  14F4B3ABXPvAibaEXe8G83HieIGDAIl6Asqpzwa1     winp1     4      2
139490  90D71445XPvAibaEXe9VBFxKgc+YL7dGZQmZ9Q4T     winp1     4      2
139492  DA84FF79XPvAibaEXe9zjjuEw+R98YAbhFyKmFb9     winp1     4      2
139493  DE1895D5XPvAibaEXe/LLVSZzXjjqt3m7kOMYcHc     winp1     4      2
139497  CE3F76ADXPvAibaEXe8NZ2cy8d9iU9DTU8+5LLtP     winp1     4      2
139501  7DE2FA39XPvAibaEXe+K/omYw1flXagdppz+1DCN     winp1     4      2
139502  D284AF3DXPvAibaEXe9H2KS7fh217ntEjegldFmZ     winp1     4      2
139507  97527AAFXPvAibaEXe84pwaxft7JNxBBpkSdhFWL     winp1     4      2
139509  C95589A4XPvAibaEXe/1bsgFpjh4A+tDulPi2V+k     winp1     4      2
139516  893CDBA3XPvAibaEXe/Eu1NFTIhfjFib15Y17tQY     winp1     4      2
139521  02A64D77XPvAibaEXe+LLN9FKbXQHXhuevnAwP5/     winp1     4      2
139522  8D85F529XPvAibaEXe/6YJZF5tGlKPrH3Qz/yPT9     winp1     4      2
139523  0E62189DXPvAibaEXe/6YJZF5tGlKAB1Y6XdCtW4     winp1     4      2
139525  55EB26A4XPvAibaEXe9RMJQZMXNkfkqci3g+5nJx     winp1     4      2
139527  766CB0A8XPvAibaEXe+PZnml5xOwGQrDZNyEhgGG     winp1     4      2
139640  722DE6E4XPvAibaEXe9QnRVgwBqH8uLTI0nID5i6     winp1     4      2
139641  B4EE76C5XPvAibaEXe/7Lh49MHjRPsl+my2yh9pz     winp1     4      2
139656  78E3AEC9XPvAibaEXe9mrX3yvrmcnDYboK0DRt9G     winp1     4      2
139667  ECDF6ED7XPvAibaEXe/qF9LXCbOdo5j8TZzcH2BF     winp1     4      2
139668  088AADDBXPvAibaEXe8NZ2cy8d9iU6Vuw8DVQg6k     winp1     4      2
139677  CBB7DBC6XPvAibaEXe8FnjVcuk8k86N79wuEMLyK     winp1     4      2
139686  40C2704AXPvAibaEXe84/0NODcOMs/f9PaRPQmBT     winp1     4      2
139692  172DCFADXPvAibaEXe/x2lXf9NFd48GFwYyxQSlA     winp1     4      2
139708  A9CBB266XPvAibaEXe+s7fQX5t7T+r2g80TgVmbO     winp1     4      2
139709  9D43264CXPvAibaEXe/BJuSl0HxpASquQQMOhGPm     winp1     4      2
139710  2082B08DXPvAibaEXe96CsVvWqz3pWr0zzBrp2V/     winp1     4      2
139711  1FF62B8CXPvAibaEXe/U/4p31JRvs5X2iSimqRky     winp1     4      2
139712  54B05DFEXPvAibaEXe9YdST3ySUdgTafZ6yR4zTG     winp1     4      2
139789  635017E7XPvAibaEXe9JezsmM1abkrMy2JYnVSIl     winp1     3      2
140161  D57404CAXPvAibaEXe+I9YJtP5yoHvTO0SZfv8yN     cs107     4      2
140306  DE1895D5XPvAibaEXe/LLVSZzXjjqt3m7kOMYcHc     cs226     4      2
140307  B1EA698AXPvAibaEXe8ZAKwWf+vl6Y7zNhpf1MZD     cs226     4      2
140370  BA38CB61XPvAibaEXe8GwHuz6BzJpGZl2tzrFpHF     cs321     4      2
140376  2F70F3B1XPvAibaEXe/NJPkXkTyAbZfzhz24LsHm     cs321     4      2
140377  A0960D55XPvAibaEXe/kICEDbR0UV4gZ9HiaUFOJ     cs321     4      2
140380  695CFFDAXPvAibaEXe+4wpotlFp126XWOuwb59oE     cs321     4      2
140458  2C7FEF6AXPvAibaEXe++6wbq0vq2fQeG3AojNpx5     it002     4      2
140460  E28B84C3XPvAibaEXe/fDAGD/zOb33IfFo+aL4XU     it002     4      2
140461  A0C4A429XPvAibaEXe/1DhMuy6izRDOIYgvozIld     it002     4      2
140462  6D9E45D8XPvAibaEXe8cTa+1WgBUHGfvnKGp4AOX     it002     4      2
142462  340DF926XPvAibaEXe+RkKlLLxpa12CC1r8rL15d     se209     3      2
142463  48120C2DXPvAibaEXe+4DPh7tigtnR11Id7Mn3lp     winp1     4      2
142464  907EA77BXPvAibaEXe9lVL3Ce6e6Ej/gp/dTPMwW     winp1     4      2
144524  279A7389XPvAibaEXe/WaZKSSjfnhiAxIlEt0pqi     ce116     2      2
144551  5F4CE55AXPvAibaEXe/GdzI46oNBdqerHI2gJ9st     ce116     2      2
144701  C140D51AXPvAibaEXe8ygSRUk01nINkERGCesQSd     it003     4      2
144998  C2E7E0F7XPvAibaEXe9fSn/pJ5xyKosTz1gU4gVu     en001     4      2
145000  EECB20A5XPvAibaEXe/sZNFvZ3icVt5xJqJvsG2x     en001     4      2
145004  A7056892XPvAibaEXe+R1vbMbxqswHUEPwixSOV3     en001     4      2
145007  144D27B4XPvAibaEXe9j1fI1hRMZJlza14nMWS7c     en001     4      2
145024  129163A8XPvAibaEXe+1/NyW42Gu9RYwbz+B51c/     en001     4      2
145359  F79E2ECBXPvAibaEXe8f6OVD8w2NiOGN8EaNz2hs     en002     4      2
145953  ED82B769XPvAibaEXe9aO86Za47HuZMgzePKWbf4     hcmt1     2      2
145954  7E3EAA1DXPvAibaEXe/6UQnMeMDn19SaNjTliDfh     hcmt1     2      2
146301  722E2A6EXPvAibaEXe+S078GtKf+EaZ0mgN3Dvmn     phil1     5      2
146302  F9D07FBBXPvAibaEXe/nMVGveCiBPV4JVp5ggU/H     phil1     5      2
146306  F43D828EXPvAibaEXe9fmk+IGAumNcy+beGw1++M     phil1     5      2
244660  C4C5C3E4XPvAibaEXe/aPLdUCtOgClLL6Fk3loNV     en001     4      1
298475  4E60F742XPvAibaEXe9jjgNhrmbJFAqOieHYy/Vf     nt205     0      1
300188  9267A209XPvAibaEXe9fw8mX+aV2o1UACd+S7Mgz     it009     0      1
300296  2EC4B4B2XPvAibaEXe81w9eVvyp+l1AHVojZtwiB     it009     0      1
300378  360D43E5XPvAibaEXe/GqyBZHXBWrqzVEvlHKtI0     se400     0      1
300443  7B2E75BDXPvAibaEXe86736b6Ol+/BCzp68OCKKb     se101     0      1
301118  4E60F742XPvAibaEXe9jjgNhrmbJFAqOieHYy/Vf     nt331     0      1
301333  1BDEA353XPvAibaEXe+1q4RcodP1hOSDtwQdwsWx     it009     0      1
301350  F0EE1719XPvAibaEXe9o3csoNuwUvKSzmcM5X/Yg     it009     0      1
301405  986002E5XPvAibaEXe8GdejRAl8WnaqAGS4oUc+9     nt113     0      1
301677  546D6A53XPvAibaEXe8oOckqmsrcbRpKOCFuFfpS     cs221     0      1
301773  F751BE36XPvAibaEXe/lOccskaOiO+4LaUqrFAPR     se341     2      1
302033  360D43E5XPvAibaEXe/GqyBZHXBWrqzVEvlHKtI0     se405     0      1
302291  B77C6C1DXPvAibaEXe+/zOhAOw/nM8JzScPPvxEP     is336     0      1
302925  888666EAXPvAibaEXe+LbmSTUWVMuLq8nh/+h4LZ     it009     0      1
302974  86043790XPvAibaEXe83baLaXNpmvkZ7kfLtJPTP     is405     4      1
303046  7C10AC8FXPvAibaEXe/zHDidEgqCTtAT2i2TddLN     cs110     0      1
303452  86043790XPvAibaEXe83baLaXNpmvkZ7kfLtJPTP     is402     0      1
303565  86043790XPvAibaEXe83baLaXNpmvkZ7kfLtJPTP     is353     0      1
303719  37089769XPvAibaEXe9Hg4P9GaiGIKto+pKuelhT     is217     0      1
303728  B77C6C1DXPvAibaEXe+/zOhAOw/nM8JzScPPvxEP     is217     0      1
304132  76BBD44BXPvAibaEXe99GOtI/HwJhfnsANkwbGH8     is254     0      1
304201  360D43E5XPvAibaEXe/GqyBZHXBWrqzVEvlHKtI0     se401     0      1
304316  7B2E75BDXPvAibaEXe86736b6Ol+/BCzp68OCKKb     se100     0      1
304786  546D6A53XPvAibaEXe8oOckqmsrcbRpKOCFuFfpS     cs111     0      1
306517  7C10AC8FXPvAibaEXe/zHDidEgqCTtAT2i2TddLN     cs521     0      1
306579  546D6A53XPvAibaEXe8oOckqmsrcbRpKOCFuFfpS     cs110     0      1
306722  546D6A53XPvAibaEXe8oOckqmsrcbRpKOCFuFfpS     cs112     0      1
306726  0FAF5403XPvAibaEXe+uQMKXqrwYdigmaK3Sgzs7     cs112     0      1
306735  364C01E5XPvAibaEXe/baiw3K4HkF0B1jHz/g2mU     cs112     0      1
308199  4C30B34EXPvAibaEXe+SqGsEQP8cFH8d8LVY0szr     ma004     0      2
308203  DDC68E16XPvAibaEXe+9GFX9aWroRBh+F6DjT3HH     ma004     4      2
308208  65A8CE1EXPvAibaEXe+tg0ae8qw/gqDz/d+/K6ii     ma004     0      2
308781  41A6622AXPvAibaEXe9B92Nhb2J32+64zW4yCFVV     it003     0      2
309008  4C30B34EXPvAibaEXe+SqGsEQP8cFH8d8LVY0szr     ph002     0      2
309368  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     ph002     0      2
309471  590C5A22XPvAibaEXe/5SY0P9d9+eIFjN53F5Ry7     it003     0      2
309513  DDC68E16XPvAibaEXe+9GFX9aWroRBh+F6DjT3HH     it004     4      2
309686  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     ma005     0      2
309731  65A8CE1EXPvAibaEXe+tg0ae8qw/gqDz/d+/K6ii     ma002     0      2
309841  33BAB02CXPvAibaEXe9TpEyDfKIVdepPvHRN0/0F     ma002     3      2
310318  1E458D16XPvAibaEXe92C4qaj9kvH6/S4CNEqhXl     ma002     0      2
310641  C1732776XPvAibaEXe+UuZ4QW1XoS0uZyqgzu4FR     it007     0      2
310750  3622E58BXPvAibaEXe9lF2o7VejWNjkH+xdoXpbr     ph002     0      2
311033  66C7067DXPvAibaEXe8enouoh243g0BOY5+GdZI7     it003     0      2
311357  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt     ma002     0      2
311445  0CBDEB0CXPvAibaEXe/rtk4wDmxi9/bnL79EBcG7     ma002     0      2
311506  0CBDEB0CXPvAibaEXe/rtk4wDmxi9/bnL79EBcG7     ph002     0      2
311689  B753FA3BXPvAibaEXe97yKczitj7gqGApxUGKXhO     it007     4      2
311744  E0E7C64CXPvAibaEXe8HoD4Gp+zDKv0Whkg3wEeS     ce221     0      2
312019  66C7067DXPvAibaEXe8enouoh243g0BOY5+GdZI7     en004     0      2
312363  1E458D16XPvAibaEXe92C4qaj9kvH6/S4CNEqhXl     it003     0      2
312427  C0DD145CXPvAibaEXe9T3PnrA+QsrmHvTLOaX03L     is207     0      2
312513  590C5A22XPvAibaEXe/5SY0P9d9+eIFjN53F5Ry7     it005     0      2
312578  106CB769XPvAibaEXe/sgKB4TWbXBaOxNaFkn1fI     it007     0      2
312582  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt     it007     0      2
313417  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt     ma005     0      2
313507  0CBDEB0CXPvAibaEXe/rtk4wDmxi9/bnL79EBcG7     ma005     0      2
313544  41A6622AXPvAibaEXe9B92Nhb2J32+64zW4yCFVV     ma001     0      2
313559  65A8CE1EXPvAibaEXe+tg0ae8qw/gqDz/d+/K6ii     ma001     0      2
313678  1E458D16XPvAibaEXe92C4qaj9kvH6/S4CNEqhXl     en005     0      2
313988  17BA4B8FXPvAibaEXe8KSegZW1rFPGTg7c0KmSrO     it003     0      2
314286  590C5A22XPvAibaEXe/5SY0P9d9+eIFjN53F5Ry7     ph002     0      2
314394  33BAB02CXPvAibaEXe9TpEyDfKIVdepPvHRN0/0F     ph002     4      2
314691  1E458D16XPvAibaEXe92C4qaj9kvH6/S4CNEqhXl     ph002     0      2
314706  33BAB02CXPvAibaEXe9TpEyDfKIVdepPvHRN0/0F     en005     4      2
315076  106CB769XPvAibaEXe/sgKB4TWbXBaOxNaFkn1fI     is208     0      2
315109  C1732776XPvAibaEXe+UuZ4QW1XoS0uZyqgzu4FR     is208     0      2
315169  219DA657XPvAibaEXe8DipYGHw7d9SskCzEQU2OO     is207     0      2
315170  0D8C38D3XPvAibaEXe+gFeZqSF+MJRmEtifntiWc     is207     0      2
315335  371D7C02XPvAibaEXe9RBNO8knVPD6nhpMeb17yK     ss004     2      2
315480  0D8C38D3XPvAibaEXe+gFeZqSF+MJRmEtifntiWc     is216     0      2
315658  C1732776XPvAibaEXe+UuZ4QW1XoS0uZyqgzu4FR     ce315     0      2
315939  C0DD145CXPvAibaEXe9T3PnrA+QsrmHvTLOaX03L     is210     0      2
316622  33BAB02CXPvAibaEXe9TpEyDfKIVdepPvHRN0/0F     ss004     0      2
317002  41A6622AXPvAibaEXe9B92Nhb2J32+64zW4yCFVV     it007     0      2
319114  17BA4B8FXPvAibaEXe8KSegZW1rFPGTg7c0KmSrO     se111     0      2
319255  17BA4B8FXPvAibaEXe8KSegZW1rFPGTg7c0KmSrO     is201     0      2
319415  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt     it009     0      2
319876  F9322B54XPvAibaEXe/LN9eBLOG7duTK0/U9ncK5     ce105     4      2
320003  2086199EXPvAibaEXe9Qk6hDUWKQXYCENEFk6Wn/     is201     0      2
320634  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     cs113     0      2
320656  0FAF5403XPvAibaEXe+uQMKXqrwYdigmaK3Sgzs7     cs113     0      2
321656  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     cs226     0      2
321779  106CB769XPvAibaEXe/sgKB4TWbXBaOxNaFkn1fI     is217     0      2
322118  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt     cs113     0      2
322248  25B1BFD3XPvAibaEXe/NRwqjPAC0MJtMPSJVARBI     cs106     0      2
322251  0FAF5403XPvAibaEXe+uQMKXqrwYdigmaK3Sgzs7     cs106     0      2
322312  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     cs106     0      2
322402  2086199EXPvAibaEXe9Qk6hDUWKQXYCENEFk6Wn/     se106     0      2
324146  2086199EXPvAibaEXe9Qk6hDUWKQXYCENEFk6Wn/     se330     0      2
324318  41A6622AXPvAibaEXe9B92Nhb2J32+64zW4yCFVV     se310     0      2
324722  C0DD145CXPvAibaEXe9T3PnrA+QsrmHvTLOaX03L     is334     0      2
325035  106CB769XPvAibaEXe/sgKB4TWbXBaOxNaFkn1fI     is334     0      2
325710  2086199EXPvAibaEXe9Qk6hDUWKQXYCENEFk6Wn/     se214     0      2
325995  33BAB02CXPvAibaEXe9TpEyDfKIVdepPvHRN0/0F     it003     4      2
326058  25B1BFD3XPvAibaEXe/NRwqjPAC0MJtMPSJVARBI     cs336     0      2
326068  0FAF5403XPvAibaEXe+uQMKXqrwYdigmaK3Sgzs7     cs336     0      2
326116  B599CE38XPvAibaEXe+1PCCPiUY9ljI1Gka6PN6P     cs231     0      2
326138  25B1BFD3XPvAibaEXe/NRwqjPAC0MJtMPSJVARBI     cs231     0      2
326147  0FAF5403XPvAibaEXe+uQMKXqrwYdigmaK3Sgzs7     cs231     0      2
330506  EC7D1459XPvAibaEXe9+m/oQf3Tjzwv+6VGDA6L6     ph001     0      1
330558  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     en002     0      1
330644  81F387C6XPvAibaEXe/HUuIVo8uCRycGtET7E3Eu     en004     0      1
331091  0FB8124AXPvAibaEXe/67dyjFFUOJjjVs2DOezdY     ph001     3      1
331325  47D6DC8BXPvAibaEXe8VdV75E6kcrmlVENOwEPKK     it003     0      1
331924  79F1E4DFXPvAibaEXe9MLbI3cCq2BHgHnnweUs+t     ph001     0      1
332377  789BE82DXPvAibaEXe/NRwqjPAC0MH7Z5B/F4F4Y     it004     0      1
333175  34AAEBF7XPvAibaEXe+7uJh0aD4oApRQobnK00ZB     en004     4      1
333200  0FB8124AXPvAibaEXe/67dyjFFUOJjjVs2DOezdY     en004     4      1
333250  DCF46740XPvAibaEXe/Fuy4XnWnIVjAVU00sAZcd     en005     0      1
336097  789BE82DXPvAibaEXe/NRwqjPAC0MH7Z5B/F4F4Y     it005     0      1
336099  47D6DC8BXPvAibaEXe8VdV75E6kcrmlVENOwEPKK     it005     0      1
337516  34AAEBF7XPvAibaEXe+7uJh0aD4oApRQobnK00ZB     ph001     3      1
338166  E2A33F44XPvAibaEXe+Ps8zYokGtSaVIhvz9TD9T     it010     2      1
340165  2CD24F0BXPvAibaEXe8HhFIQfSEkkHRFKF/zhJXt     nt118     3      1
340392  1D85AA76XPvAibaEXe8b36blNCVklTt+tRSX8XSH     en004     0      1
340409  A8B0141DXPvAibaEXe9+3TdUbRXdLdw8cDgngIjx     en004     0      1
341150  E2A33F44XPvAibaEXe+Ps8zYokGtSaVIhvz9TD9T     ss004     2      1
342649  BAA21E56XPvAibaEXe9Xnw4t0GPgx5ergjwY9IdE     nt210     0      1
342750  EC7D1459XPvAibaEXe9+m/oQf3Tjzwv+6VGDA6L6     it009     0      1
344128  789BE82DXPvAibaEXe/NRwqjPAC0MH7Z5B/F4F4Y     cs111     0      1
344622  79F1E4DFXPvAibaEXe9MLbI3cCq2BHgHnnweUs+t     it002     0      1
344635  C0C9C20EXPvAibaEXe/y2t7DVG8TDRg2y/nF6frs     it002     0      1
345582  4D09D127XPvAibaEXe8pr9LKErUcFS4Ybav4Fa0F     nt132     0      1
346183  973154C3XPvAibaEXe+Y2Dmraxe1iYT8oxNVsVdy     ss002     3      1
346974  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     cs221     0      1
347035  DA77A23CXPvAibaEXe8TCemjJxtx9N+MBryz9bo1     it005     4      1
347446  789BE82DXPvAibaEXe/NRwqjPAC0MH7Z5B/F4F4Y     cs221     0      1
347610  BAA21E56XPvAibaEXe9Xnw4t0GPgx5ergjwY9IdE     nt331     0      1
348027  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     cs110     0      1
348118  1E875540XPvAibaEXe/MFNByxh05b5BrS1i0Rr6P     ss004     2      1
348684  0FB8124AXPvAibaEXe/67dyjFFUOJjjVs2DOezdY     it009     0      1
349344  C0C9C20EXPvAibaEXe/y2t7DVG8TDRg2y/nF6frs     is336     0      1
349752  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     cs112     0      1
351066  D6DA2754XPvAibaEXe9tdh69VvZt14BfENMelpA0     se104     0      1
351265  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     cs417     0      1
351367  BAA21E56XPvAibaEXe9Xnw4t0GPgx5ergjwY9IdE     is217     0      1
351651  59078061XPvAibaEXe9tdh69VvZt1+Ti0cTWxX8h     cs232     0      1
370935  AB68F073XPvAibaEXe8zjuWfAVBr9bNXLQe3EvcD     ce119     1      2
372721  AC17A2EBXPvAibaEXe+ltCXpm838vTWWVUsJrTsd     cs336     0      2
376859  806529A7XPvAibaEXe+q0E3QguGBpaRnFeH23a1j     ma006     4      1
376928  7B268A1EXPvAibaEXe+eLIaWcq1sIxuuUuwiSyyB     ma006     4      1
377508  7B268A1EXPvAibaEXe+eLIaWcq1sIxuuUuwiSyyB     ss004     2      1
377755  550DA54EXPvAibaEXe9mNMzpS14VgQuZB5vjk0sM     it004     4      1
379010  221BC6FEXPvAibaEXe/69hWWh+JD2bqvbrEM5LbX     nt105     0      1
379252  550DA54EXPvAibaEXe9mNMzpS14VgQuZB5vjk0sM     it005     4      1
379382  EFCB9543XPvAibaEXe9WGATIMl02LHB8H3jszgG1     it005     0      1
379835  B527F688XPvAibaEXe9U/K5zYZONT1/SQtZRNrnP     it003     0      1
380019  523FC174XPvAibaEXe+0Dwp+QXLoYisCEJFVmgYz     it005     4      1
380345  B527F688XPvAibaEXe9U/K5zYZONT1/SQtZRNrnP     is207     0      1
383043  5CAC932AXPvAibaEXe9p2uXWEeSl6nZ4xyTHcwcH     ma006     4      1
383217  C7750281XPvAibaEXe8E6yzSPpyFOUkenmh5LQzU     ma006     4      1
383228  83C48DC7XPvAibaEXe8IXn+MV9wqkkAswm7lxemz     ma006     4      1
384422  806529A7XPvAibaEXe+q0E3QguGBpaRnFeH23a1j     ma003     3      1
384772  C7750281XPvAibaEXe8E6yzSPpyFOUkenmh5LQzU     ma003     3      1
384783  83C48DC7XPvAibaEXe8IXn+MV9wqkkAswm7lxemz     ma003     3      1
385223  7B268A1EXPvAibaEXe+eLIaWcq1sIxuuUuwiSyyB     ma003     0      1
385735  F48EEE2EXPvAibaEXe92T150Nt0xZi8sMV7EYlBL     ce121     4      1
385736  806529A7XPvAibaEXe+q0E3QguGBpaRnFeH23a1j     ce121     4      1
386220  7B268A1EXPvAibaEXe+eLIaWcq1sIxuuUuwiSyyB     ph002     4      1
386709  32F1D5A6XPvAibaEXe9puzAyruoCKfbLKFeVYo2s     ss001     5      1
387407  E934BCD3XPvAibaEXe86736b6Ol+/MLJ5vOrqV8U     cs214     0      1
387620  C7750281XPvAibaEXe8E6yzSPpyFOUkenmh5LQzU     ce121     4      1
387631  83C48DC7XPvAibaEXe8IXn+MV9wqkkAswm7lxemz     ce121     4      1
388691  E934BCD3XPvAibaEXe86736b6Ol+/MLJ5vOrqV8U     it004     0      1
391054  0DB54EF3XPvAibaEXe9YYF5FMCfolFEcE74CV9kF     it008     0      1
391499  3FD5FC49XPvAibaEXe/s5yot2gW0Ov5AAkiZk6vT     se215     0      1
391608  18B0A997XPvAibaEXe+tKlY40ATmdY+I2LRutPEn     se215     0      1
391786  E22A2826XPvAibaEXe917PYvJ9Jl7e9CWUnHZ/H/     se102     0      1
392001  E22A2826XPvAibaEXe917PYvJ9Jl7e9CWUnHZ/H/     it008     0      1
392201  550DA54EXPvAibaEXe9mNMzpS14VgQuZB5vjk0sM     it008     4      1
392276  AE861457XPvAibaEXe8CSUzma4ok0vV/Cr7jHwGh     se114     0      1
392488  3FD5FC49XPvAibaEXe/s5yot2gW0Ov5AAkiZk6vT     se405     0      1
393100  0DB54EF3XPvAibaEXe9YYF5FMCfolFEcE74CV9kF     se341     0      1

# Xử lý dữ liệu

### Cột mssv

In [14]:
# kiểm tra dữ liệu khuyết
missing_count = df['mssv'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'mssv': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'mssv': 0

### cột mamh

In [15]:
# Số lượng dữ liệu khuyết
missing_count = df['mamh'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'mamh': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'mamh': 0

In [16]:
# Các giá trị duy nhất và tần suất trong cột mamh
print(f"\nGiá trị duy nhất trong cột 'mamh':")
print(df['mamh'].value_counts())
print(df['mamh'].unique())

Giá trị duy nhất trong cột 'mamh':
mamh
it002       15960
ma003       15759
it001       15632
it003       14615
it004       13166
ma005       13135
ma004       12887
it005       12120
ss004       11575
it007       10772
ss003       10310
ma006        9958
eng02        9880
eng01        9729
eng03        9644
pe001        9413
it006        9355
ph002        9340
pe002        9239
it009        8812
ss006        8534
ph001        8029
ss001        6691
ma001        6611
ma002        6498
se104        5641
ss002        5413
ss007        5233
ss008        4841
ss010        4838
eng04        4671
ss009        4358
se102        4280
lia01        4184
dsal1        4158
carc1        3958
mat04        3922
mat02        3903
hcmt1        3879
vcpl1        3827
oopt1        3772
mat01        3762
phy01        3744
csc01        3697
osys1        3652
dbss1        3562
winp1        3465
cnet1        3356
en004        3342
nt106        3306
en001        3299
pedu1        3298
phy02        3244
pedu2        3182
is208        3181
en002        3115
is207        3061
nt101        2925
is201        2917
en003        2825
nt118        2715
phil1        2668
pe012        2650
item1        2637
en005        2588
itew1        2558
it008        2548
se101        2416
smet2        2337
it012        2298
se106        2295
sta01        2140
se501        2101
cs106        2064
se114        1993
se100        1914
nt105        1912
nt113        1910
cs112        1895
is336        1895
ce103        1816
is334        1816
nt114        1760
se330        1707
nt132        1670
ie106        1666
is210        1665
ce119        1627
nt104        1620
se214        1598
nt109        1582
is211        1557
eng05        1548
cs111        1547
is353        1544
enbt         1542
is252        1539
is216        1509
ph003        1507
nt111        1396
ce101        1384
cs221        1379
ce105        1377
is217        1368
en006        1363
ce118        1357
cs105        1347
cs231        1331
se215        1319
ie101        1316
ie104        1314
it010        1307
mat22        1303
is105        1300
mat23        1287
nt131        1272
se310        1266
se346        1234
nt209        1210
ie105        1204
se109        1193
nt201        1163
is403        1161
ce501        1154
nt103        1143
ie103        1131
ce104        1127
nt334        1125
ce107        1118
nt204        1085
nt330        1064
se401        1044
se505        1015
is254        1014
se112        1009
is402         993
se405         983
cs110         971
nt505         969
csc21         966
se325         964
se108         962
se400         953
mat21         948
is405         944
ce201         928
ce121         909
se331         900
enga2         892
nt303         891
ce206         882
nt115         880
ie005         880
nt405         863
se111         856
nt208         855
phil2         815
ce117         814
cs115         813
nt112         810
cs005         805
cs114         802
nt207         801
ec001         801
se211         791
is232         775
se103         775
nt110         770
cs519         767
ce505         765
nt402         762
cs232         761
nt501         757
ie204         744
nt107         740
cs511         735
is335         733
se207         731
se105         728
se418         720
is005         712
se311         711
se005         708
mlpe1         704
nt108         704
se121         703
is220         702
soci1         696
nt532         689
nt213         683
cs336         680
cs406         672
cs211         672
is206         670
nt117         669
se209         668
ce005         659
nt102         658
nt203         653
se208         651
se210         650
nt202         649
ce109         643
se417         643
ce124         640
is212         639
is251         630
se122         627
nt534         620
jan01         615
nt219         614
cs331         613
nt332         612
ce212         612
is203         610
nt215         604
cs226         603
se213         595
ie202         594
is101         592
se113         591
ec201         590
is205         589
ce113         585
se322         583
ce102         583
nt005         582
is202         580
se347         573
nt301         569
ce110         564
cs214         563
engl1113      561
ce111         560
cs217         557
ce106         554
enga1         546
se312         544
nt205         543
nt015         540
engl1213      538
ce213         537
ie402         537
ie206         533
se212         533
ie213         532
nt210         527
cs113         524
is215         516
cs505         513
ce222         505
ce112         505
ce224         504
ce115         501
ce211         500
cs314         497
ie102         496
math2144      494
ec331         493
ie307         484
se358         482
nt133         482
ce108         480
nt302         478
cs102         478
jan02         475
is107         473
is103         471
is102         468
ce116         467
se313         465
se341         465
ie303         461
math2153      460
dsal2         459
cs1113        457
ec213         452
cs5423        451
math3013      449
ec003         447
ec335         445
cs4343        445
cs410         442
phys1114      441
cs3443        439
cs338         439
is106         438
is204         436
phys1214      436
cs4273        434
is104         434
cs4283        433
nt531         432
ce114         430
cs4323        427
nt230         426
ec337         426
ds102         424
is311         424
nt533         422
spch3723      419
jan03         419
cs117         402
cs2133        394
ce315         392
cs409         386
stat4033      385
is502         381
se337         370
cs3653        369
se301         362
se326         361
cs313         360
is501         359
cs222         358
nt119         357
ec005         356
jan04         354
nt503         352
cs116         351
nt536         351
ec214         349
cs4243        344
nt130         343
cs104         343
cs107         342
cs5433        339
nt305         335
ce232         334
ie403         330
se332         330
nt504         329
msis3033      323
nt502         322
nt403         317
spch2713      315
cs419         310
nt331         308
msis3303      307
msis4013      306
ce403         301
ce204         300
cs103         298
cs108         297
mlpe2         297
se357         291
is401         291
ce316         290
ce314         289
nt137         287
ce302         287
nt206         286
ec311         284
is301         279
ec312         275
cs109         273
nt521         267
phy03         263
ec229         262
cs315         257
se321         255
ce313         255
msis4263      254
se334         254
cs5030        252
cs321         251
ec208         247
jan05         246
cs316         241
ce221         241
is505         238
phy22         238
ds101         238
ce202         238
nt307         237
msis405       237
msis2433      234
jan06         234
cs431         233
cs212         233
cs5000        232
nt304         231
ce404         227
ec222         227
ec338         226
nt321         224
ce301         224
stat3013      223
jan07         223
ie309         222
cs324         222
se356         220
cski1         214
cs101         213
is404         211
se350         211
ce502         210
ie221         209
cs326         205
ie207         202
cs2433        201
nt406         200
nt407         200
ie212         199
cs526         198
ec202         198
cs3363        197
cs3373        196
nt121         196
ds103         194
cs4793        192
cs523         192
cs3613        191
ec219         190
ds005         188
se107         184
cs3423        183
ds105         182
cs322         182
ec301         181
ds201         178
ec302         177
ec203         173
cu001         171
eng00         170
msis207       168
ie229         167
cs530         166
acct5123      164
ce402         164
cs414         164
ds310         163
cs323         161
iem5723       161
cs522         160
msis402       160
ds304         158
se220         158
ce319         156
is303         155
ec212         155
cs521         155
cs311         154
ce324         154
cs407         153
ec002         151
adeng1        149
cs225         149
cs223         147
cs529         147
ce437         146
se339         146
ie505         141
msis4523      140
ce401         140
bus1125       135
ce405         135
cs332         134
cs227         132
iem4733       128
adeng2        127
ds200         124
nt320         122
spch3724      120
ce411         120
jan08         115
sc203         115
ie230         113
is213         113
nt211         112
int002        112
is253         111
cs412         110
ds106         105
ce434         104
cs301         104
cs302         103
nt535         102
cs404          99
cs4153         99
mktg5883       98
ce312          95
cs405          95
nt538          94
nt216          93
csbu007        91
engbt          90
oopt2          90
csbu003        90
ce409          89
csc12          89
cs401          89
eng13          88
ss005          88
csc11          87
csbu008        87
smet1          87
csbu006        87
cnbu002        87
ds104          86
mat11          85
mat14          85
eng11          84
se335          84
lia11          83
eng12          83
ec232          82
sp3724         82
phy11          82
csbu001        80
cnbu001        79
cs524          78
nt522          78
cs420          77
ce430          76
csbu010        75
ce219          75
csbu012        75
nt116          75
cs501          74
ds300          72
se344          71
cs527          71
csbu004        70
nt333          67
ie226          67
cs525          66
mat12          64
eng14          64
cs371          62
phy12          62
se221          61
cs351          61
cs372          60
eng15          60
csbu011        60
se340          60
cs352          60
csbu013        59
econ3313       56
ce435          55
ds202          54
msis4133       53
cs408          53
ds203          52
se328          51
nt404          50
ie209          50
cs339          50
cs531          49
ie203          47
cs532          46
stat11         44
ce410          44
ie107          44
csbu015        44
csbu014        44
ec333          44
is3303         44
csbu009        43
ds204          43
cs013          43
cs411          43
ds505          42
nt306          42
ce407          41
se323          40
is4013         40
is4523         39
se327          37
is4263         37
cs325          36
cs417          35
cs019          33
csbu101        33
csbu105        32
se333          32
ds303          32
ce326          32
is306          31
se324          31
cnbu003        31
ds307          30
is219          30
ce317          30
ce334          30
se343          30
is305          30
cs004          29
cs535          29
ce306          28
nt401          28
cs515          27
cs334          27
ai001          27
ds308          27
cs014          26
cs508          24
csbu016        23
ec401          23
nt311          23
ie301          23
cs403          22
cs4143         22
is3033         21
se355          21
csbu102        21
msis4800       20
is4133         20
cs229          19
msis4801       19
adeng3         19
se320          18
ce433          18
cnbu004        18
cs551          18
ds309          17
cs233          16
ie405          15
cnbu005        15
ce321          14
ce421          14
cs228          14
cs402          11
cs503          10
it011           8
cnbu008         7
cnbu006         7
cnbu007         7
nt509           5
cnbu009         5
vcph1           5
ce408           5
ce438           4
mat24           3
cs4344          3
is5100          3
me001           2
osys2           2
Name: count, dtype: int64
['carc1' 'csc21' 'eng02' 'mat21' 'pedu1' 'phil2' 'phy01' 'dbss1' 'dsal1'
 'eng03' 'mat22' 'oopt2' 'pedu2' 'phy22' 'cnet1' 'cski1' 'eng04' 'mat23'
 'mlpe2' 'osys1' 'winp1' 'cs104' 'cs105' 'cs106' 'mat04' 'vcpl1' 'ce105'
 'cs103' 'cs107' 'cs108' 'dsal2' 'hcmt1' 'cs102' 'cs109' 'cs211' 'cs311'
 'soci1' 'cs013' 'cs019' 'is207' 'item1' 'cs101' 'cs401' 'cs403' 'cs503'
 'se104' 'cs212' 'cs014' 'cs402' 'cs004' 'cs226' 'phil1' 'sta01' 'cs322'
 'vcph1' 'oopt1' 'eng05' 'ce101' 'ce102' 'ce108' 'ce103' 'ce104' 'ce106'
 'ce107' 'ce109' 'ce110' 'ce111' 'ce112' 'ce113' 'ce114' 'ce115' 'ce204'
 'itew1' 'ce116' 'ce301' 'ce501' 'smet2' 'ce314' 'ce505' 'is203' 'is102'
 'is103' 'is201' 'is204' 'is206' 'is104' 'is105' 'is205' 'is208' 'is106'
 'is107' 'is202' 'is301' 'is311' 'is305' 'is306' 'is501' 'is101' 'is505'
 'ce202' 'ce302' 'eng01' 'nt101' 'nt105' 'se101' 'se102' 'se103' 'se105'
 'se106' 'se207' 'se311' 'se324' 'se208' 'se209' 'se212' 'se213' 'se325'
 'se331' 'se417' 'se210' 'se211' 'se335' 'se337' 'se343' 'se418' 'se501'
 'se322' 'se326' 'se505' 'nt109' 'nt112' 'nt201' 'nt202' 'nt106' 'nt301'
 'nt303' 'nt113' 'nt401' 'nt103' 'nt110' 'se312' 'nt104' 'nt102' 'nt107'
 'nt108' 'nt111' 'nt203' 'nt302' 'nt501' 'nt502' 'nt503' 'nt504' 'nt509'
 'cs321' 'nt305' 'nt304' 'cs404' 'cs405' 'cs407' 'cs406' 'cs223' 'cs225'
 'cs525' 'nt505' 'cs408' 'ce312' 'smet1' 'nt307' 'nt403' 'nt320' 'is303'
 'nt306' 'cs501' 'cs334' 'eng00' 'mlpe1' 'phy02' 'eng11' 'eng13' 'mat11'
 'cs2433' 'csc11' 'eng12' 'mat12' 'cs4343' 'lia11' 'mat14' 'phy11'
 'sp3724' 'cs3443' 'cs5423' 'eng14' 'eng15' 'phy12' 'stat11' 'cs3363'
 'cs3373' 'cs4283' 'cs4323' 'is3303' 'cs3423' 'cs4243' 'cs4273' 'cs5433'
 'osys2' 'mat24' 'cs351' 'cs352' 'cs371' 'cs372' 'se321' 'csc12' 'cs3613'
 'cs4793' 'is4133' 'cs5030' 'is4523' 'ce117' 'csc01' 'lia01' 'mat01'
 'mat02' 'cs314' 'cs227' 'cs313' 'phy03' 'ce313' 'engbt' 'cs110' 'is5100'
 'is4263' 'msis4263' 'cs1113' 'is4013' 'is3033' 'en001' 'en002' 'cs5000'
 'it001' 'ph001' 'engl1113' 'adeng1' 'ss001' 'ma003' 'ma001' 'pe001'
 'econ3313' 'stat4033' 'math2144' 'msis4800' 'msis4801' 'ph002' 'it002'
 'it003' 'nt321' 'nt404' 'ph003' 'ce403' 'ma002' 'cs112' 'cs217' 'cs323'
 'cs228' 'en003' 'nt116' 'cs222' 'ce402' 'adeng2' 'engl1213' 'math2153'
 'phys1214' 'spch3723' 'cs2133' 'msis3303' 'ce404' 'se400' 'se401' 'se405'
 'cs301' 'pe002' 'is402' 'is404' 'cs409' 'cs410' 'cs411' 'is403' 'ma005'
 'ma004' 'msis3033' 'sc203' 'spch3724' 'se333' 'se344' 'cs508' 'cs515'
 'it004' 'it005' 'cs111' 'cs214' 'cs316' 'cs414' 'cs511' 'ce219' 'it006'
 'cs3653' 'is251' 'enbt' 'math3013' 'phys1114' 'ce119' 'it007' 'se323'
 'it008' 'cs412' 'se341' 'it009' 'is210' 'nt407' 'ss004' 'cs221'
 'msis4013' 'msis4523' 'ss002' 'ss003' 'cs505' 'cs302' 'nt216' 'is211'
 'is216' 'is335' 'ce316' 'ce118' 'is212' 'cs4344' 'cs326' 'se114' 'se301'
 'se332' 'se330' 'se339' 'is232' 'is213' 'cs231' 'cs315' 'is252' 'is336'
 'is215' 'cs531' 'ce221' 'ce324' 'is253' 'ie103' 'ce306' 'ce211' 'nt119'
 'se334' 'ss005' 'nt118' 'nt206' 'cs233' 'cs324' 'se109' 'se220' 'is334'
 'se107' 'ie102' 'nt117' 'nt211' 'se214' 'is254' 'ie101' 'ie104' 'nt334'
 'cs4143' 'ce317' 'ce212' 'ce222' 'ce315' 'en004' 'en005' 'ie105' 'se108'
 'is353' 'nt207' 'se215' 'nt130' 'nt204' 'nt131' 'se340' 'nt208' 'nt331'
 'ec202' 'is217' 'se346' 'se100' 'ec203' 'ie106' 'nt114' 'se111' 'se112'
 'nt330' 'ce206' 'ce201' 'is401' 'cs519' 'en006' 'ec201' 'ie402' 'nt332'
 'nt209' 'nt333' 'nt311' 'ie303' 'ec302' 'nt405' 'se313' 'nt115' 'cs113'
 'cs521' 'cs524' 'ie107' 'nt213' 'ie203' 'nt205' 'se310' 'ec301' 'ec001'
 'ie202' 'nt402' 'nt532' 'ce411' 'adeng3' 'nt210' 'cs325' 'is405' 'ce405'
 'se221' 'ie206' 'nt406' 'ce401' 'is219' 'cs420' 'ce326' 'ie403' 'ie204'
 'nt132' 'se328' 'nt534' 'nt531' 'cs419' 'se320' 'ec335' 'ie301' 'cs336'
 'ec212' 'ie505' 'ec401' 'spch2713' 'msis405' 'ma006' 'ce421' 'it010'
 'nt133' 'nt533' 'nt535' 'cs332' 'ec331' 'cs417' 'cs331' 'cs232' 'se327'
 'cs530' 'nt137' 'cs527' 'msis2433' 'int002' 'ec219' 'ec337' 'se350'
 'ce121' 'jan01' 'ce124' 'ie307' 'ie209' 'jan02' 'jan03' 'jan04' 'jan05'
 'jan06' 'jan07' 'cs523' 'enga2' 'stat3013' 'cs431' 'acct5123' 'ss006'
 'nt219' 'ce321' 'cs339' 'iem4733' 'ie213' 'iem5723' 'cs114' 'msis207'
 'cs522' 'msis402' 'ec003' 'ds101' 'enga1' 'mktg5883' 'ce213' 'se347'
 'cs338' 'cs4153' 'cs529' 'ec213' 'ce224' 'is220' 'ds103' 'ss008' 'ss010'
 'ss007' 'is502' 'ec312' 'ce430' 'ds102' 'ce409' 'se113' 'nt230' 'csbu001'
 'cnbu001' 'ds304' 'nt215' 'csbu003' 'ce232' 'csbu004' 'ec311' 'msis4133'
 'ss009' 'se121' 'pe012' 'it012' 'ce319' 'csbu007' 'csbu006' 'cnbu002'
 'ds202' 'nt536' 'nt005' 'ds105' 'cs535' 'ds201' 'ce005' 'ec222' 'ie005'
 'se005' 'csbu011' 'csbu012' 'csbu008' 'ec229' 'cs115' 'ds106' 'se357'
 'ec002' 'ec208' 'ce433' 'se122' 'csbu013' 'nt015' 'cnbu003' 'ds005'
 'cs005' 'is005' 'ec005' 'it011' 'ie221' 'ce434' 'ds310' 'ds203' 'se358'
 'ie229' 'cs229' 'ce502' 'ec232' 'nt121' 'csbu010' 'ds200' 'ce410'
 'csbu015' 'ie309' 'cnbu004' 'jan08' 'csbu014' 'cs526' 'cnbu005' 'cs117'
 'ce407' 'ec333' 'cnbu008' 'cnbu006' 'cnbu007' 'nt522' 'se356' 'nt521'
 'ds300' 'ds308' 'ce437' 'ds505' 'ec214' 'ec338' 'ie212' 'ie230' 'cs116'
 'ds104' 'ie405' 'ie226' 'ce408' 'cu001' 'ce438' 'ds303' 'cnbu009' 'cs532'
 'csbu016' 'ie207' 'ds204' 'csbu009' 'ce334' 'me001' 'ds309' 'bus1125'
 'cs551' 'nt538' 'ds307' 'se355' 'csbu102' 'ce435' 'csbu105' 'ai001'
 'csbu101']

In [17]:
# Bỏ khoảng trắng và viết thường trong các môn học
df['mamh'] = df['mamh'].str.replace(" ", "").str.lower().str.strip()

### cột sotc

In [18]:
# Số lượng khuyết
missing_count = df['sotc'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'sotc': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'sotc': 0

In [20]:
# Chuyển đổi cột 'hocky' sang kiểu số nguyên để loại bỏ phần .0
df['hocky'] = df['hocky'].astype('Int64')

## cột hocky

In [19]:
# Số lượng khuyết
missing_count = df['hocky'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'hocky': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'hocky': 0

In [21]:
# Chuyển đổi cột 'hocky' sang kiểu số nguyên để loại bỏ phần .0
df['hocky'] = df['hocky'].astype('Int64')

## cột namhoc

In [22]:
# Số lượng khuyết
missing_count = df['namhoc'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'namhoc': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'namhoc': 0

In [23]:
# Chuyển đổi cột 'namhoc' sang kiểu số nguyên để loại bỏ phần .0
df['namhoc'] = df['namhoc'].astype('Int64')

## cột diem_hp

In [24]:
# Kiểm tra giá trị khuyết
missing_count = df['diem_hp'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'diem_hp': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'diem_hp': 614

In [27]:
# Xử lý giá trị khuyết bằng các điền mean
df['diem_hp'].fillna(df['diem_hp'].mean(), inplace=True)

<ipython-input-27-6647ab322cea>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diem_hp'].fillna(df['diem_hp'].mean(), inplace=True)

## cột trangthai

In [31]:
# Kiểm tra giá trị khuyết
missing_count = df['trangthai'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'trangthai': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'trangthai': 0

In [32]:
# Chuyển đổi cột 'trangthai' sang kiểu số nguyên để loại bỏ phần .0
df['trangthai'] = df['trangthai'].astype('Int64')

### Lưu dữ liệu đã làm sạch

In [33]:
df.to_excel("/content/drive/MyDrive/Data/Data_clean/diem_Thu.xlsx", index=False)