# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Đọc & xử lý dữ liệu

In [3]:
data_path = '/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/EDA'

In [25]:
# Load dữ liệu
df = pd.read_excel(data_path + '/diemrl_EDA.xlsx')

# Kiểm tra dữ liệu bị khuyết

In [5]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv          0
hocky         0
namhoc        0
drl           0
ghichu    97210
dtype: int64

In [6]:
# Tỷ lệ giá trị thiếu
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)
print("Tỷ lệ giá trị thiếu (%):")
print(missing_percentage)

Tỷ lệ giá trị thiếu (%):
ghichu    86.811695
mssv       0.000000
hocky      0.000000
namhoc     0.000000
drl        0.000000
dtype: float64

In [7]:
# Kiểm tra số dòng chứa giá trị null
num_null_rows = df.isnull().any(axis=1).sum()
print(f"Số dòng chứa giá trị null: {num_null_rows}")

Số dòng chứa giá trị null: 97210

In [8]:
# Lọc các dòng có chứa giá trị null
rows_with_null = df[df.isnull().any(axis=1)]
print(rows_with_null)

                                            mssv  hocky  namhoc  drl ghichu
0       2A10C466XPvAibaEXe8vcQUX+A6FeNIl5Loug1zV      2    2013   81    NaN
1       903ADF1AXPvAibaEXe9p5G9u2qRxxZEjiJjD4Ztl      2    2013   88    NaN
2       F06EDFFEXPvAibaEXe8KSegZW1rFPMNPBQ+c9rst      2    2013   94    NaN
3       AA868AD5XPvAibaEXe+1Gm1QkI5oNyTYwjwmgxhx      2    2013   86    NaN
4       E7105148XPvAibaEXe+E7LJdSZ9AW2sUcg4OSCnU      2    2013   88    NaN
...                                          ...    ...     ...  ...    ...
104077  AA1C2CB0XPvAibaEXe+gzQv7yQRYbtqPu+C2Ean+      2    2021   84    NaN
104078  C5B47790XPvAibaEXe8XtTI6VHhlKI0qhA2KfoCe      2    2021   85    NaN
104079  4BD52092XPvAibaEXe/sKOWIYAkjtqMmin54+S4E      2    2021   97    NaN
104080  C50FB698XPvAibaEXe+9v37KcInSIff/FxEfaYpI      2    2021   96    NaN
104081  C652408CXPvAibaEXe/baiw3K4HkF5HM+yiC7grI      2    2021   70    NaN

[97210 rows x 5 columns]

# Xử lý dữ liệu

### Cột hocky

In [9]:
# kiểm tra dữ liệu khuyết
missing_count = df['hocky'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'hocky': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'hocky': 0

### cột namhoc

In [10]:
# Số lượng dữ liệu khuyết
missing_count = df['namhoc'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'namhoc': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'namhoc': 0

### cột drl

In [11]:
# Số lượng khuyết
missing_count = df['drl'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'drl': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'drl': 0

### cột ghichu

In [12]:
# Số lượng khuyết
missing_count = df['ghichu'].isnull().sum()
print(f"Số lượng dữ liệu khuyết trong cột 'ghichu': {missing_count}")

Số lượng dữ liệu khuyết trong cột 'ghichu': 97210

In [26]:
# Hàm gán giá trị vào cột ghichu dựa trên giá trị drl
def assign_rating(drl):
  '''
    Hàm gán giá trị vào cột ghichu dựa trên giá trị drl
    Param:
      drl: Giá trị có trong cột drl
  '''
  if drl >= 90:
      return 'Xuất sắc'
  elif 80 < drl <= 90:
      return 'Tốt'
  elif 65 < drl <= 80:
      return 'Khá'
  elif 50 < drl <= 65:
      return 'Trung bình'
  else:
      return 'Yếu'

# Cập nhật cột ghichu
df['ghichu'] = df['drl'].apply(assign_rating)

In [27]:
# Kiểm tra giá trị duy nhất có trong cột ghi chú
df['ghichu'].unique()

array(['Tốt', 'Xuất sắc', 'Khá', 'Trung bình', 'Yếu'], dtype=object)

In [30]:
# Bỏ các ký tự đặc biệt, chữ thường, xóa khoảng trắng
excute_column = ['mssv']
for column  in df.select_dtypes(include=['object']).columns:
  if column not in excute_column:
    df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%]", '', regex=True)

In [32]:
# Xóa khoảng trắng thừa trong cột "ghichu"
df['ghichu'] = df['ghichu'].str.strip()  # Xóa khoảng trắng đầu và cuối
df['ghichu'] = df['ghichu'].str.replace(r'\s+', '', regex=True)  # Xóa khoảng trắng thừa giữa các từ

### Kiểm tra lại Dataframe sau chỉnh sửa

In [33]:
df.sample(20)

,mssv,hocky,namhoc,drl,ghichu
46697,70F90D42XPvAibaEXe9Veo8epKbTmBeI/A+3r/Mr,1,2017,80,khá
45299,A16D54D0XPvAibaEXe+uRfOPQ+iOmU4FqQ+HPoKK,1,2010,69,khá
107952,34C8F91FXPvAibaEXe+ROAqc8OE8mGe/GYBHOQio,1,2022,77,khá
103975,87BD981FXPvAibaEXe8d+xuL7f/QxNgglGkOAI2P,2,2021,100,xuấtsắc
91096,5FCD6E38XPvAibaEXe+J+IMbPBeTHOiPyDpCWIGx,1,2021,100,xuấtsắc
86750,CBBBFABBXPvAibaEXe8at9gGXzJnL8bRZxskX4x7,2,2020,84,tốt
71520,488467C0XPvAibaEXe/PfwiDaLddEqWLLsSKR16Z,2,2019,100,xuấtsắc
51533,1668B1AEXPvAibaEXe8LHfATqQ4bHvpZYxNsj+iv,2,2017,75,khá
97748,DB28A6B8XPvAibaEXe+E43ovk5Cnp7bfzCqOTUE4,2,2021,58,trungbình
81783,052DD070XPvAibaEXe915NmCViXOMIckuNlCM3i6,1,2020,78,khá
31801,C5F83251XPvAibaEXe8BeS0kgrxaCtDztZepCgw3,1,2013,72,khá
29412,EEBF2442XPvAibaEXe/2qwApU9UOazn+Mhld4KaC,2,2011,38,yếu
46526,64670803XPvAibaEXe9MQ7MBXxp/MzXtVck0yGt0,1,2017,63,trungbình
47736,5066E750XPvAibaEXe+RTFcnyQdP1gV8o5sqlLTq,1,2017,80,khá
108438,4674CC98XPvAibaEXe+NFoCjcOelGcqCxyqIcpkF,1,2022,99,xuấtsắc
17522,D570716AXPvAibaEXe/ve/U6YLNUGj0thvrllJB1,2,2015,49,yếu
24079,85F1114EXPvAibaEXe8VjSa+EGRlUdDzKHwFjWXS,1,2012,95,xuấtsắc
96286,1EA57FE2XPvAibaEXe8KuJNEATWS84Upb9tIcBqb,1,2021,69,khá
86396,3982AEB8XPvAibaEXe9sAb//V6ZS2KXwfbGgg74X,2,2020,88,tốt
69137,1341EFFDXPvAibaEXe+m4TIigwhBB1SEozhT0EVe,1,2019,76,khá

### Lưu dữ liệu đã làm sạch

In [34]:
df.to_excel("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/diemrl.xlsx", index=False)