# Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Thiết lập để hiển thị tất cả các dòng và cột dataframe

In [3]:
pd.set_option('display.max_rows', None)  # Hiển thị tất cả các dòng
pd.set_option('display.max_columns', None)  # Hiển thị tất cả các cột

# Đọc và xử lý dữ liệu

In [5]:
data_path  = "/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/EDA" # Đường dẫn đến Folder Drive lưu file dữ liệu x_EDA.xlsx

In [6]:
# Load dữ liệu
df = pd.read_excel(data_path + "/sinhvien_dtb_toankhoa_EDA.xlsx") # Có thể thay đổi theo shortcut trên drive

In [7]:
# Bỏ các ký tự đặc biệt, chữ thường, xóa khoảng trắng
for column in df.select_dtypes(include=['object']).columns:
  if column != 'mssv':
    df[column] = df[column].str.lower().str.replace(r"[',:);*@$/%]", '', regex=True)

# Kiểm tra dữ liệu bị khuyết

In [8]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv              0
dtb_toankhoa    322
dtb_tichluy     322
dtype: int64

In [9]:
# Tỷ lệ giá trị thiếu
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)
print("Tỷ lệ giá trị thiếu (%):")
print(missing_percentage)

Tỷ lệ giá trị thiếu (%):
dtb_toankhoa    2.304939
dtb_tichluy     2.304939
mssv            0.000000
dtype: float64

In [10]:
# Lọc các dòng có chứa giá trị null
rows_with_null = df[df.isnull().any(axis=1)]
print(rows_with_null)

                                           mssv  dtb_toankhoa  dtb_tichluy
3558   FFFAFB51XPvAibaEXe+F+2tZHEiFCbIwAZfR+51z           NaN          NaN
3603   F8FD0FE0XPvAibaEXe9NdAclo3+sV2nNlXxOTO2G           NaN          NaN
3639   4EBB055AXPvAibaEXe+pZU+khqBqym2HqfAwq7dR           NaN          NaN
3652   55B938EBXPvAibaEXe/j7U1wtp2b2U32RKuDYEOK           NaN          NaN
3719   A90A53BCXPvAibaEXe+YGniCiyMp04jJX2Wr85uH           NaN          NaN
3771   B915F286XPvAibaEXe/wvgrdNVCyf0irX7eDS0FW           NaN          NaN
3842   DDC4070CXPvAibaEXe8LX4hhYKrFZmeNvj1Ubc+X           NaN          NaN
3893   073A03BFXPvAibaEXe99J3nD1pBZIiykbD6Ly8MS           NaN          NaN
3956   4FEB2D39XPvAibaEXe+zCbAzes7YiuqisXuJ0GNT           NaN          NaN
4009   247ED76DXPvAibaEXe8BxOZlGHrYN+ZHkVM9KmT2           NaN          NaN
4014   D81E16AAXPvAibaEXe9d+rE/yvWoKOl34nkMQeKu           NaN          NaN
4019   EAAF21FEXPvAibaEXe/j7U1wtp2b2btZP75Vmr6c           NaN          NaN
4026   5F33F5CDXPvAibaEXe9WcTnuikKYKm2ng7qW0qt2           NaN          NaN
4027   6C364EC2XPvAibaEXe+YGniCiyMp0ysDTVqqe/o1           NaN          NaN
4028   C9B7E55CXPvAibaEXe9TMBdu4IUydyjQ+IcV61W3           NaN          NaN
4068   2A8DAF58XPvAibaEXe9xHju59ydahQVO3VPCz9O+           NaN          NaN
4110   DB3FB9AEXPvAibaEXe9Veo8epKbTmPijix6h2pRo           NaN          NaN
4113   B19140F5XPvAibaEXe9PDEhlfOA/zwOh/mp/bbZG           NaN          NaN
4232   45600323XPvAibaEXe9TMBdu4IUydzVNIzlS0ihI           NaN          NaN
4333   742DCC7EXPvAibaEXe8+PBTAPRlCYxA3E10quceV           NaN          NaN
4358   1BE14FA9XPvAibaEXe9xHju59ydahYMcfLW/WKy7           NaN          NaN
4360   13E44A72XPvAibaEXe9YXJ3+ew7OHBUv+FzO1GAl           NaN          NaN
4364   BC9C1728XPvAibaEXe+p5WOBbWD0MyMRBU65qtRf           NaN          NaN
4592   FEEC7092XPvAibaEXe8LHfATqQ4bHilEeS+SAsbV           NaN          NaN
4593   15C3825BXPvAibaEXe8AEUw13Ud6KgFnNzR7Jqtt           NaN          NaN
4600   B4B88F35XPvAibaEXe/baiw3K4HkF15CSs+1LTON           NaN          NaN
4601   84E1B7FCXPvAibaEXe/H1VZJBzJAwtmPCbS42/eJ           NaN          NaN
4602   B27C60A8XPvAibaEXe/rp0ev/rDe04oF2ZCGJraa           NaN          NaN
4603   87494DFBXPvAibaEXe9MSDlNDFbYdriI+E5L+SQr           NaN          NaN
4612   A18CFAAFXPvAibaEXe8WA4OgPtanSHqRtig6lIG0           NaN          NaN
4613   1610764BXPvAibaEXe8b4sJvH2gx3J8X3BqSAqmg           NaN          NaN
4615   1B5F6841XPvAibaEXe8b4sJvH2gx3Bihm3+m+w7B           NaN          NaN
4619   2BAF0FCDXPvAibaEXe/tRbq0ZEBEr8MDsZ7SnUus           NaN          NaN
4620   947612FDXPvAibaEXe/tRbq0ZEBErzmiytjdgmCJ           NaN          NaN
4622   05C7951FXPvAibaEXe8dEe4TA8wgH73bwcRJQPHJ           NaN          NaN
4629   B711FFDCXPvAibaEXe8dEe4TA8wgHyNr5LM0ii+H           NaN          NaN
4640   98F99BABXPvAibaEXe8YaJ+XvjGNa6bcx9UHF7ua           NaN          NaN
4648   1F325948XPvAibaEXe+sRe0ac318AwrlfwFsmVdZ           NaN          NaN
4649   11E6F160XPvAibaEXe/NExuU8f5CH6I7+GF6mOEp           NaN          NaN
4651   67D80C3CXPvAibaEXe+TQJLvJOj4Bd1swjdYrlSo           NaN          NaN
4653   DF608ADFXPvAibaEXe+TQJLvJOj4BTgX/pCJf4E4           NaN          NaN
4658   3A2C6176XPvAibaEXe+9WAygB66RlHLalw4pRD42           NaN          NaN
4661   D42EA478XPvAibaEXe+TQJLvJOj4BU9+RAzl3JCG           NaN          NaN
4664   C600AEEEXPvAibaEXe/NExuU8f5CH5S+V1hvxPev           NaN          NaN
4679   B78FD1BAXPvAibaEXe/NExuU8f5CH567V6o2MbQ9           NaN          NaN
4686   3464F57BXPvAibaEXe8x8S8Fn/vYpnHq5N2lIyX5           NaN          NaN
4688   8DE7D40BXPvAibaEXe9QJDM9nE85iLS70B9rixRG           NaN          NaN
4689   B2AEA953XPvAibaEXe9QJDM9nE85iBfzZRRJon7A           NaN          NaN
4691   FE79A224XPvAibaEXe+sRe0ac318AxHLzFESOit4           NaN          NaN
4700   B0202D56XPvAibaEXe8v1/72rbobbUwRJwgIs6xq           NaN          NaN
4701   A0CB9706XPvAibaEXe8v1/72rbobbROV94x8WEMT           NaN          NaN
4705   7F0D99A2XPvAibaEXe+sRe0ac318A1ENksQuyDQc           NaN          NaN
4718   545B846DXPvAibaEXe/5SY0P9d9+eMfkVaZwN4JB           NaN          NaN
4735   BBD8D849XPvAibaEXe/baiw3K4HkFwJ6E2uiAYB5           NaN          NaN
4737   D84E5A23XPvAibaEXe+xw+0gOjOR0CMYE0umEfHW           NaN          NaN
4744   384667D5XPvAibaEXe+xw+0gOjOR0HLJh9yvwYSu           NaN          NaN
4748   CBAFB769XPvAibaEXe8dZIB3odxynmrD8DYmiabX           NaN          NaN
4754   37352DA9XPvAibaEXe8dZIB3odxynpxd9rhvHWQs           NaN          NaN
4756   113564A7XPvAibaEXe+XNXOqfiZ3jPb+X6uC90hc           NaN          NaN
4773   ABE52AF6XPvAibaEXe+XNXOqfiZ3jJ5aRnSAU2vQ           NaN          NaN
4778   1C73FCA9XPvAibaEXe8c53vaOKMxC/gQIVqrJzaS           NaN          NaN
4780   970A9DD6XPvAibaEXe9cZqyTkM8+AZ60v51yihfJ           NaN          NaN
4783   733522D4XPvAibaEXe+xxRCacZP96ihSUhw6bXAc           NaN          NaN
4785   F59A38E4XPvAibaEXe+xxRCacZP96i/00p5A0uhS           NaN          NaN
4791   DB60DB0DXPvAibaEXe9cZqyTkM8+AfSi2NLEaX67           NaN          NaN
4798   B5354425XPvAibaEXe9oenRjqNmEXy6WNlXEuPvM           NaN          NaN
4806   94506E49XPvAibaEXe9cYfl6D6BtPE5Vp+WsONSv           NaN          NaN
4811   5602780AXPvAibaEXe8WA4OgPtanSAkji+sJLqWR           NaN          NaN
4814   1915387DXPvAibaEXe9oenRjqNmEX7xh4NWX9vVX           NaN          NaN
4822   45E2F9FBXPvAibaEXe/cg9419ghLE0dEACR/5m/u           NaN          NaN
4826   094C91FFXPvAibaEXe97q47CdxnNZNSAqgOy4plN           NaN          NaN
4827   9593B137XPvAibaEXe/KGOYNCaEaWdmOwMFzut+H           NaN          NaN
4835   718948BEXPvAibaEXe8VziDgYa0u7pX4fnolK02s           NaN          NaN
4855   B2D7AE6BXPvAibaEXe/Uev7j/8EzmRHUL4JRIhuC           NaN          NaN
4892   BCD5A87DXPvAibaEXe8p5yvHQtPES+8Dy1v0Z3sv           NaN          NaN
4893   581B8737XPvAibaEXe8p5yvHQtPES2OLhy17L1ZN           NaN          NaN
4906   0207CAD2XPvAibaEXe/rp0ev/rDe075RWU3TMOuT           NaN          NaN
4922   463D573DXPvAibaEXe8AEUw13Ud6KmuHOgx3Ud2+           NaN          NaN
4933   10BCBCB5XPvAibaEXe8e8TJXhGRqkKRdiTlHFwOj           NaN          NaN
4937   AD4C75D0XPvAibaEXe8e8TJXhGRqkPej4JP3jRAP           NaN          NaN
4956   99525DB4XPvAibaEXe+Xxbs4kvH/k48ZqkD+A9gs           NaN          NaN
4960   2E2CC21FXPvAibaEXe+9lRniSKKShy7LnjHXuek8           NaN          NaN
4963   018792F1XPvAibaEXe8e/5ryJ9YpuQE7W/tVuJ9z           NaN          NaN
4969   32AE3C8BXPvAibaEXe/69hWWh+JD2e9gQRyf9Ue5           NaN          NaN
4973   388D15A8XPvAibaEXe/ETkXgDMKQ8VRRKuwI0MLx           NaN          NaN
4990   1393EF9FXPvAibaEXe9cZqyTkM8+AXQOldJpfyIW           NaN          NaN
4993   83011458XPvAibaEXe9cYfl6D6BtPNmZ3cDNtDDD           NaN          NaN
4995   8EDD6CFAXPvAibaEXe9cZqyTkM8+AY7jBpwXaPLC           NaN          NaN
5000   8ED431EEXPvAibaEXe8hLNatuVCg+enrFFuMTE+Z           NaN          NaN
5006   F5DB132BXPvAibaEXe/Twrxaq444c6loN2w4O+XH           NaN          NaN
5008   D8AFA7B8XPvAibaEXe/Twrxaq444c8XRyNy/yAfc           NaN          NaN
5011   FF8A75E8XPvAibaEXe8TrN3vUI8MaASe6w5UIf4q           NaN          NaN
5015   29FDD184XPvAibaEXe9ej2kTw4OUmgziIf4r8V/G           NaN          NaN
5019   5C9936FAXPvAibaEXe/VTtmkh7JuOnI2EE2vN0Vo           NaN          NaN
5027   2ED79E8DXPvAibaEXe/twRH8x8eyg6p469sUGlP7           NaN          NaN
5033   A8C7B136XPvAibaEXe9tdh69VvZt1yS2nLSrUwG8           NaN          NaN
5034   4B4D24A6XPvAibaEXe/nRR7q+hWy3E0JfgAKl7U5           NaN          NaN
5039   091CBDBAXPvAibaEXe+9lRniSKKSh07xd/heq9Ds           NaN          NaN
5046   E9D834E9XPvAibaEXe8FWWF7xHXRAKlGe3gzsVj1           NaN          NaN
5050   53EBE27AXPvAibaEXe/Ko3VBeq65/y9WsAPxIWm+           NaN          NaN
5052   A69D92A9XPvAibaEXe/ETkXgDMKQ8TUQyCgDzzyE           NaN          NaN
5064   3E914727XPvAibaEXe+ai34rvuG7eL66Qe/gAH81           NaN          NaN
5065   E26FD96EXPvAibaEXe8oOckqmsrcbbrgH+v0pq6V           NaN          NaN
5066   18FABD24XPvAibaEXe+ai34rvuG7eDYg0/QaChn9           NaN          NaN
5067   2230BCB0XPvAibaEXe8oOckqmsrcbRF+ACJ5QEXf           NaN          NaN
5071   284011BEXPvAibaEXe/KMtCr6bHaunqAOsX+6mxi           NaN          NaN
5074   6786C17AXPvAibaEXe+Wjq/eoSKNhXbDuAqwMJn7           NaN          NaN
5076   EE22119AXPvAibaEXe+UuZ4QW1XoS5NXt79G11BW           NaN          NaN
5082   5FEA688BXPvAibaEXe+sRe0ac318A4IOGf4XOdrZ           NaN          NaN
5098   1E445A85XPvAibaEXe8dZIB3odxynqvptgs/hfmW           NaN          NaN
5102   67E88EF6XPvAibaEXe/dSnTMEtLaY97BoZYK+nhU           NaN          NaN
5108   FCE1959FXPvAibaEXe9cZqyTkM8+AUJMUir9X3C9           NaN          NaN
5109   CB9F41C2XPvAibaEXe9cZqyTkM8+AeWPf76RWAkx           NaN          NaN
5112   82083B45XPvAibaEXe/KGOYNCaEaWVUr+qOMJa/p           NaN          NaN
5113   37669E68XPvAibaEXe/GFbVLDV6SZNusSHgpvhGe           NaN          NaN
5122   DE98630BXPvAibaEXe9LZwdMb86KA0pyyZH7xxB8           NaN          NaN
5123   2061A4B2XPvAibaEXe/kJUgsv26UawcT4KIjkLxn           NaN          NaN
5130   A202BE33XPvAibaEXe8WA4OgPtanSPUBFtwVVkmi           NaN          NaN
5149   E416AFB1XPvAibaEXe/a3PM8AP2Ng4RI+Xvmb9tJ           NaN          NaN
5154   810C1E49XPvAibaEXe8IlpBhypyXxoaj0uno3WdM           NaN          NaN
5155   52D43643XPvAibaEXe+tg0ae8qw/gjk4UsrDASy1           NaN          NaN
5161   A5612176XPvAibaEXe/1obfbwrsd5+8PU43AiPq+           NaN          NaN
5164   67412419XPvAibaEXe8WA4OgPtanSFiJ8Ki5nRP1           NaN          NaN
5165   39FBEE06XPvAibaEXe9hSzSdeSAT0v/Ow1T/77Oc           NaN          NaN
5169   5792A717XPvAibaEXe8v1/72rbobbVIPmppRnJfa           NaN          NaN
5172   BC2C7920XPvAibaEXe80CLygfiFTYPr5lgKbYsph           NaN          NaN
5174   ACFCA90CXPvAibaEXe+xw+0gOjOR0E9o5MPyXM3d           NaN          NaN
5175   5ACDD92BXPvAibaEXe8dZIB3odxyngpdQByie8BD           NaN          NaN
5177   9C46D02EXPvAibaEXe9cZqyTkM8+AW3GcrutPPbm           NaN          NaN
5180   0D88FE54XPvAibaEXe9oenRjqNmEX8XcSnlxva4F           NaN          NaN
5182   58F272B7XPvAibaEXe/cg9419ghLEz/iNuRqINqD           NaN          NaN
5192   C4D67351XPvAibaEXe/NExuU8f5CH1ZOfYqtQBgG           NaN          NaN
5215   6828B353XPvAibaEXe/twRH8x8eyg4+L+Y6tFKJb           NaN          NaN
5222   B5C6C6B9XPvAibaEXe8e/5ryJ9YpuUZlwPVkxL/g           NaN          NaN
5226   B80537CAXPvAibaEXe9hSzSdeSAT0m2N/HOQrgOH           NaN          NaN
5227   CF42097FXPvAibaEXe+ltCXpm838vWxQsmFNV1ys           NaN          NaN
5236   4A603E02XPvAibaEXe8aMmuWiMhL4hgHzS+poCB2           NaN          NaN
5237   A669532AXPvAibaEXe+9WAygB66RlDLjY62SRM+r           NaN          NaN
5241   B1BED6A0XPvAibaEXe9U/K5zYZONT7ZGbI4e4m1i           NaN          NaN
5246   47C27624XPvAibaEXe9x0CaUg4pZowWix8R/WdkH           NaN          NaN
5251   16FB2C15XPvAibaEXe/H1VZJBzJAwqy5uZpjEduk           NaN          NaN
5257   87376DCBXPvAibaEXe8z1Io4iT8HJJtBe2CEHGeu           NaN          NaN
5270   514A3DECXPvAibaEXe9ETemEVgJcUegdg+rNr/lb           NaN          NaN
5283   5D4F1A9DXPvAibaEXe+kaKwPBw23VnNHQgxDyDTN           NaN          NaN
5287   A02DA74EXPvAibaEXe8FWWF7xHXRAFyhaIEVFlOs           NaN          NaN
5288   0A9F8229XPvAibaEXe8aMmuWiMhL4hRbn8qCDJRD           NaN          NaN
5307   D0C95292XPvAibaEXe8VdV75E6kcrgLVrs1Fi4Sq           NaN          NaN
5313   7DB2644EXPvAibaEXe/Ko3VBeq65//CJkj+rtDjH           NaN          NaN
5315   ADC1C454XPvAibaEXe8zBeLfIMmoBCq0Emuria73           NaN          NaN
5319   1CA077EDXPvAibaEXe8e/5ryJ9Ypuf1lR99ZI926           NaN          NaN
5329   7D0C0BD9XPvAibaEXe/y2t7DVG8TDV7FWLODvhqI           NaN          NaN
5331   FA7EDD2FXPvAibaEXe+ai34rvuG7eP9E6G4wRLcH           NaN          NaN
5336   58017A22XPvAibaEXe/KMtCr6bHauiT9JZDCXFa4           NaN          NaN
5351   16EA2800XPvAibaEXe8b4sJvH2gx3OzQRETVkPQ6           NaN          NaN
5370   55AE44C5XPvAibaEXe8YaJ+XvjGNa9Ke6XinqLVW           NaN          NaN
5371   7A660769XPvAibaEXe+uQMKXqrwYdiS3zycdWPbH           NaN          NaN
5372   97F2BB4AXPvAibaEXe+uQMKXqrwYdj8koGG6h5t7           NaN          NaN
5394   C4CDCBC5XPvAibaEXe9iBRrLJjO8dVLxBibN1VVb           NaN          NaN
5398   65452B54XPvAibaEXe/GP74oAJxkeIY4984e2edl           NaN          NaN
5405   23AA54C7XPvAibaEXe9x0CaUg4pZo3odOfsQT8EC           NaN          NaN
5406   F5B15821XPvAibaEXe/NExuU8f5CH6PxLfQFo3Oa           NaN          NaN
5407   25BD8B03XPvAibaEXe/9XMaU/9dsP5cbS3M9oQVE           NaN          NaN
5425   F3AA9A2FXPvAibaEXe/9n4RXguPAYOJFsIbZBBan           NaN          NaN
5429   6AC74A44XPvAibaEXe9MSDlNDFbYdrWsZXk57Hct           NaN          NaN
5430   9166895DXPvAibaEXe9x0CaUg4pZoy9Q4xTxkGAq           NaN          NaN
5434   48CE1F4CXPvAibaEXe9Qk6hDUWKQXRP1iGa4MNp0           NaN          NaN
5437   26721142XPvAibaEXe9x0CaUg4pZo2KLCB99zUiY           NaN          NaN
5442   C68A5B86XPvAibaEXe/dSnTMEtLaY91Wn0exYrqG           NaN          NaN
5445   352F6B52XPvAibaEXe/Nok7qdNjJRlLJeyjFi9bA           NaN          NaN
5448   197D30CFXPvAibaEXe9oenRjqNmEX5OwBeoBICpN           NaN          NaN
5454   5DB8BE72XPvAibaEXe/cg9419ghLE2FLNhbJMW4L           NaN          NaN
5455   B3357F31XPvAibaEXe/cg9419ghLE+mU7YTHcgSi           NaN          NaN
5464   362E0B40XPvAibaEXe/KGOYNCaEaWWWS4Y/amVw+           NaN          NaN
5465   0EE3C49AXPvAibaEXe+TZKE2gC8nUohS7x/TknLB           NaN          NaN
5469   44CB5AB9XPvAibaEXe8VziDgYa0u7gjxME1wNjCf           NaN          NaN
5473   D5AE7925XPvAibaEXe/Uev7j/8EzmX6I5+kpZ4Rv           NaN          NaN
5479   18A3BF12XPvAibaEXe/MCL0qpDhx01XBHJPA25U6           NaN          NaN
5485   FF70CBC8XPvAibaEXe/kJUgsv26Ua1SZgeP5Ugln           NaN          NaN
5514   D575575AXPvAibaEXe+NJiMjcH3vhJGheczh16YP           NaN          NaN
5517   61772D90XPvAibaEXe/a3PM8AP2Ng7x4K/etUVal           NaN          NaN
5521   4D421DD4XPvAibaEXe8yzZ/8QUtgdrXPfT7B7lip           NaN          NaN
5524   EC76F573XPvAibaEXe/a3PM8AP2Ng4J0hamacjYs           NaN          NaN
5541   BD4C7956XPvAibaEXe9afbyrOJH5CFSQtR1go3tT           NaN          NaN
5547   4A4ACDDDXPvAibaEXe9oenRjqNmEX5I9fyuYsMlg           NaN          NaN
5552   7FCEED37XPvAibaEXe8TrN3vUI8MaHc8XbXm7D9t           NaN          NaN
5557   1247EF92XPvAibaEXe8FWWF7xHXRAAdouVcJLcFt           NaN          NaN
5569   A0CEB7F5XPvAibaEXe+PmhPN+9CWc2NVb37ysrOo           NaN          NaN
5578   E8A803D5XPvAibaEXe9Qk6hDUWKQXROZHpoYWOfU           NaN          NaN
5579   0F4FADA5XPvAibaEXe9cZqyTkM8+ARGbXcQbCfpP           NaN          NaN
5596   9ABA52D9XPvAibaEXe8e8TJXhGRqkF2Tb4FL8psV           NaN          NaN
5604   F9F8B286XPvAibaEXe/H1VZJBzJAwvGRipptMVaD           NaN          NaN
5613   56FFED6DXPvAibaEXe8zt9d6Yn9pDNWovv85KQpo           NaN          NaN
5625   534A71D2XPvAibaEXe8FWWF7xHXRAHLHX8TTMnK/           NaN          NaN
5634   2610D39EXPvAibaEXe8WA4OgPtanSCGMj7abmaIq           NaN          NaN
5636   E1B5BA36XPvAibaEXe8ptkRJyotmH97lfWD7QSC3           NaN          NaN
5638   22C5DED4XPvAibaEXe8FWWF7xHXRACuCLnl2/7Sn           NaN          NaN
5643   D61CE9EDXPvAibaEXe9ETemEVgJcUVXq1JdqNefU           NaN          NaN
5647   A61F80EAXPvAibaEXe8x8S8Fn/vYpprLYsvD/h+f           NaN          NaN
5649   4204AE8BXPvAibaEXe8IlpBhypyXxhr1I+ZvQF9p           NaN          NaN
5655   15B47970XPvAibaEXe9ETemEVgJcUbLBtIGZev84           NaN          NaN
5666   A5E07AC6XPvAibaEXe8FWWF7xHXRAL+ab01DuBMH           NaN          NaN
5676   0FC537B6XPvAibaEXe/1obfbwrsd55+QlVebr8a8           NaN          NaN
5678   8D430943XPvAibaEXe8WA4OgPtanSLheNpZ25jlk           NaN          NaN
5684   39984783XPvAibaEXe9o/lUQXb5f/8Mx1S20KfF7           NaN          NaN
5702   1B35ACC6XPvAibaEXe9ej2kTw4OUmibebW0fpYV/           NaN          NaN
5705   CED62785XPvAibaEXe/ETkXgDMKQ8SymX9+C1xJU           NaN          NaN
5706   D34479E0XPvAibaEXe8x8S8Fn/vYppmG3GC7RuAu           NaN          NaN
5718   B4CE3C2AXPvAibaEXe8IlpBhypyXxjkPpJjxmsVo           NaN          NaN
5721   B416AFD1XPvAibaEXe9ajZoptpw4tS1gNFWpCu1V           NaN          NaN
5727   DB98905FXPvAibaEXe+sRe0ac318A6cScGlsCoBb           NaN          NaN
5751   4206082BXPvAibaEXe8WA4OgPtanSACPjLVYYm8l           NaN          NaN
5752   2BB219B6XPvAibaEXe8IlpBhypyXxqqU24KGxP8X           NaN          NaN
5763   B745DD48XPvAibaEXe+xRE5267JUoN//BtfKHsaP           NaN          NaN
5771   DC4A6B7FXPvAibaEXe+ai34rvuG7eBHudouRu9Yf           NaN          NaN
5785   9036154CXPvAibaEXe+PmhPN+9CWc1lB0pM5bRzk           NaN          NaN
5793   44B5A6DDXPvAibaEXe8IlpBhypyXxlEoYRUlsNJz           NaN          NaN
9226   68CDD0E2XPvAibaEXe+/EkvXK98KbVK3ygK5BAjq           NaN          NaN
9229   873EC7BFXPvAibaEXe9jjgNhrmbJFHiax0YuqGj2           NaN          NaN
9272   ACB4F4BEXPvAibaEXe+Y5CB/5gt3MKIQIxlQpNB+           NaN          NaN
9275   6541BE5DXPvAibaEXe9jjgNhrmbJFMpKau1vo91G           NaN          NaN
9317   9EAF0738XPvAibaEXe9fwZBwsCOuQEjnKDCrGOX1           NaN          NaN
9326   DFBD14D1XPvAibaEXe+gsTDvgY5pDg+1XrTGcBGO           NaN          NaN
9328   19804910XPvAibaEXe/YKAlYnC3m98sziS0YIT48           NaN          NaN
9333   04BBCFD3XPvAibaEXe8WD3qnVG2b/dP/YcbmMhzG           NaN          NaN
9334   B9C8F3D0XPvAibaEXe/SxwNRab2vgJIlevDVgBlu           NaN          NaN
9340   B360ABA8XPvAibaEXe+NmgQbVGcjJ3b3URRal7gh           NaN          NaN
9342   D2EDCC18XPvAibaEXe8wMpKQnQ7j6IUmbWFFKViI           NaN          NaN
9354   F91C8711XPvAibaEXe99GOtI/HwJhU08jg0nZTnF           NaN          NaN
9369   EAFD455EXPvAibaEXe8wlx2/dthDApPeGdUYUh4U           NaN          NaN
9374   96E4EA8DXPvAibaEXe/+PcSgI7YkeRw4toTJDREB           NaN          NaN
9382   570085C5XPvAibaEXe8ooYk4mkUGmC5n35zDc8f0           NaN          NaN
9388   7F63F478XPvAibaEXe+y4Ivhjp8SxieLsImfCyxw           NaN          NaN
9439   00B3611FXPvAibaEXe/X/wixypGyAm0R+2QlvSGE           NaN          NaN
9442   8B3D2790XPvAibaEXe/X/wixypGyAnNl5qqrJHoS           NaN          NaN
9461   E0C34467XPvAibaEXe+NmgQbVGcjJzGGuXzIE7Gx           NaN          NaN
9467   590CD0C1XPvAibaEXe+5oCRQPDKXskh92X9I+r0b           NaN          NaN
9473   DFBA9895XPvAibaEXe/ji2wENvGp6DOaDc0vcFvq           NaN          NaN
9474   753B836AXPvAibaEXe/ji2wENvGp6HQutkSlhfRI           NaN          NaN
9484   62B3B96DXPvAibaEXe/WSo41+3xFkJdBMOLrE8XH           NaN          NaN
9488   BF99690FXPvAibaEXe99j2P15eeB00KiEtW/NHTj           NaN          NaN
9501   A40DD53AXPvAibaEXe9X5bpEKoa0mt2H0pZjVzKr           NaN          NaN
9509   6ADB63CBXPvAibaEXe9X5bpEKoa0msmJDBM60XkS           NaN          NaN
9525   3DA94391XPvAibaEXe8CKeIX0ksEeBrA5495O9Vj           NaN          NaN
9532   647B94E2XPvAibaEXe9iKIRwqei6/HpkmW0WJXVt           NaN          NaN
9535   CD206968XPvAibaEXe9iKIRwqei6/GHt0zCXTZi+           NaN          NaN
9543   9C79A1BFXPvAibaEXe/Dy4K4yiQpODsmKcC+HNNb           NaN          NaN
9552   434B8D69XPvAibaEXe9HKUC7sboLjg8nh5FS9V73           NaN          NaN
9562   408560B6XPvAibaEXe/FWKstHRRDnZbbXsMIWWYI           NaN          NaN
9565   731818ABXPvAibaEXe/V2dF0qjs8bRhhM3T/ollx           NaN          NaN
9597   485F13A0XPvAibaEXe/YKN5ysyYL7K8QqB7D5u/P           NaN          NaN
9611   64807FB4XPvAibaEXe9FiaSoce50DCBHtyL38NWA           NaN          NaN
9612   D56FA1B8XPvAibaEXe9JDlHA4z2GHBHU2OSrRtnA           NaN          NaN
9619   86C8F381XPvAibaEXe8s1xx8DWM0qgWTAVhVuJfA           NaN          NaN
9639   59449FC3XPvAibaEXe86736b6Ol+/M2Z/GG9Tcbt           NaN          NaN
9663   CDC61FB0XPvAibaEXe86736b6Ol+/IVLj3Ay7m7u           NaN          NaN
9700   68678BF3XPvAibaEXe9fwZBwsCOuQN9NtmhYA5Mu           NaN          NaN
9704   43728CADXPvAibaEXe/Dy4K4yiQpOO3Ibl1zkL6r           NaN          NaN
9729   42104CC9XPvAibaEXe8Y+/3uR2PkTKjp4HXKb6p1           NaN          NaN
9766   7670808DXPvAibaEXe8k9aD0YXzUPpIDcOXLcLp9           NaN          NaN
9770   7A019083XPvAibaEXe/Hpk/kOf6+1T9xNyZ1UrB6           NaN          NaN
9775   3C6C1B42XPvAibaEXe//3t8+us0X0lSPhzgiZhj5           NaN          NaN
9776   0D87BB45XPvAibaEXe//3t8+us0X0vVucFVPup84           NaN          NaN
9795   AAC34E4AXPvAibaEXe8wlx2/dthDArSvzGSW0tnj           NaN          NaN
9804   14662366XPvAibaEXe9aucNQ7/14aBamG7RKet9Q           NaN          NaN
9808   1C00791FXPvAibaEXe8wlx2/dthDAlxocSH//nq8           NaN          NaN

# Xử lý dữ liệu

### Cột dtb_toankhoa

In [13]:
# Xử lý giá trị khuyết bằng cách điền mean
df.fillna({'dtb_toankhoa': df['dtb_toankhoa'].mean()}, inplace=True)

### Cột dtb_tichluy

In [15]:
# Xử lý giá trị khuyết bằng cách điền mean
df.fillna({'dtb_tichluy': df['dtb_tichluy'].mean()}, inplace=True)

### Kiểm tra lại bảng dữ liệu để chắc chắn không còn giá trị NaN

In [16]:
# Đếm số lượng giá trị bị khuyết cho từng cột
missing_values = df.isnull().sum()
missing_values

mssv            0
dtb_toankhoa    0
dtb_tichluy     0
dtype: int64

### Lưu dữ liệu đã làm sạch

In [17]:
df.to_excel("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_clean/sinhvien_dtb_toankhoa.xlsx", index=False)