# Import Libraries

In [101]:
import pandas as pd

# Mount Drive

In [102]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Load Data

In [103]:
# Load dữ liệu
file_path = '/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Data_merge/data_merge.xlsx'
data = pd.read_excel(file_path)

# Tạo thông tin để test recommend

In [104]:
# Lọc thông tin 1 sinhvien để đề xuất
mssv = data[data['sinhvien_nam'] >= 3]['mssv'].unique()

In [105]:
recommend_mssv = mssv[0]
recommend_data = data[data['mssv'].isin([recommend_mssv])]

In [106]:
# Loại bỏ dữ liệu từ nằm 3 trở đi của sinh viên đó
data.drop(data[(data['mssv'].isin([recommend_mssv])) & (data['sinhvien_nam'] >= 3)].index, inplace=True)

In [107]:
unrecommend_mssv = data['mssv'].unique()

In [108]:
result = [item not in mssv for item in unrecommend_mssv]

In [109]:
unrecommend_mssv = unrecommend_mssv[result]

In [110]:
unrecommend_data = data[data['mssv'].isin([unrecommend_mssv[0]])]

In [111]:

unrecommend_data

,mssv,namsinh,gioitinh,noisinh,lopsh,khoa,hedt,khoahoc,mamta,diem_thita,...,lydo,hockyxl,namhocxl,ngayqd,dtb_toankhoa,dtb_tichluy,dtbhk,drl,ghichu,sinhvien_nam
513,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
514,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
515,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
516,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
517,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
518,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
519,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1
520,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,77,Khá,1
521,01CD0FE9XPvAibaEXe/YKN5ysyYL7C/LVIRFhL6K,1993,1,khánhhoà,khtn2013,khmt,cntn,8,không,0,...,không,0,0,0,0.0,0.0,0.0,55,Trungbình,1

In [112]:
recommend_data.to_excel('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Test_recommend/recommend_data.xlsx', index=False)

In [113]:
unrecommend_data.to_excel('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Test_recommend/unrecommend_data.xlsx', index=False)

# Train_test_DataFrame

In [114]:
# Chọn ra 20 mssv có sinhvien_nam > 20 làm để test
filtered_data = data[data['sinhvien_nam'] >= 3]['mssv'].unique()[:50]

In [115]:
# Chia dữ liệu thành train/test
train_DataFrame = data[~data['mssv'].isin(filtered_data)]
test_DataFrame = data[data['mssv'].isin(filtered_data)]

In [116]:
train_DataFrame.to_excel('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Train_test_DataFrame/train_DataFrame.xlsx', index=False)

In [117]:
test_DataFrame.to_excel('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Train_test_DataFrame/test_DataFrame.xlsx', index=False)

# Clone github

In [118]:
!git clone https://github.com/LunaBlack/KGAT-pytorch.git "/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/KGAT-pytorch"

Cloning into '/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/KGAT-pytorch'...
remote: Enumerating objects: 471, done.
remote: Counting objects: 100% (471/471), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 471 (delta 303), reused 455 (delta 297), pack-reused 0 (from 0)
Receiving objects: 100% (471/471), 106.74 MiB | 14.18 MiB/s, done.
Resolving deltas: 100% (303/303), done.
Updating files: 100% (65/65), done.

# Train_test_GRAPH

KG:
- Sinhvien
- hocky
- sinhvien_nam
- khoa
- monhoc
- sotc
- trangthai

CKG:
- User-item interactions
- KG

Việc cần làm:
  -Thực thể
    - Sinhvien
    - hocky
    - sinhvien_nam
    - khoa
    - khoahoc
    - trangthai
- Quan hệ:
    - monhoc-diem
    - monhoc-hocky
    - monhoc-sinhvien_nam
    - khoa-monhoc
    - monhoc - sotc
    - monhoc - trangthai

# User - item bipartite graph filtering

In [119]:
interactions = data[['mssv', 'mamh']]

# Knowledge Graph filtering

Thêm các quan hệ

In [121]:
monhoc_diem = data[['mamh', 'diem_hp']]
monhoc_diem['relation'] = 'monhoc_diem'
monhoc_diem.columns = ['h', 't', 'r']

<ipython-input-121-765571da9efa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_diem['relation'] = 'monhoc_diem'

In [122]:
monhoc_hocky = data[['mamh', 'hocky']]
monhoc_hocky['relation'] = 'monhoc_hocky'
monhoc_hocky.columns = ['h', 't', 'r']

<ipython-input-122-be4b804fc9b5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_hocky['relation'] = 'monhoc_hocky'

In [123]:
monhoc_sinhvien_nam = data[['mamh', 'sinhvien_nam']]
monhoc_sinhvien_nam['relation'] = 'monhoc_sinhvien_nam'
monhoc_sinhvien_nam.columns = ['h', 't', 'r']

<ipython-input-123-e01f52137567>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_sinhvien_nam['relation'] = 'monhoc_sinhvien_nam'

In [124]:
monhoc_sotc = data[['mamh', 'sotc']]
monhoc_sotc['relation'] = 'monhoc_sotc'
monhoc_sotc.columns = ['h', 't', 'r']

<ipython-input-124-b55f8d51dee8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_sotc['relation'] = 'monhoc_sotc'

In [125]:
monhoc_trangthai = data[['mamh', 'trangthai']]
monhoc_trangthai['relation'] = 'monhoc_trangthai'
monhoc_trangthai.columns = ['h', 't', 'r']

<ipython-input-125-627a00e364f2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_trangthai['relation'] = 'monhoc_trangthai'

In [126]:
monhoc_khoa = data[['mamh', 'khoa']]
monhoc_khoa['relation'] = 'monhoc_khoa'
monhoc_khoa.columns = ['h', 't', 'r']

<ipython-input-126-31d9818d8293>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monhoc_khoa['relation'] = 'monhoc_khoa'

In [127]:
monhoc_attribute = pd.concat([monhoc_diem, monhoc_hocky, monhoc_sinhvien_nam, monhoc_sotc, monhoc_trangthai, monhoc_khoa], ignore_index=True)

In [128]:
monhoc_attribute

             h     t            r
0        it001   7.5  monhoc_diem
1        ma003   5.0  monhoc_diem
2        ma001   5.0  monhoc_diem
3        ph001   8.0  monhoc_diem
4        en001   6.5  monhoc_diem
...        ...   ...          ...
2554519  ec229  httt  monhoc_khoa
2554520  ec214  httt  monhoc_khoa
2554521  ec208  httt  monhoc_khoa
2554522  is334  httt  monhoc_khoa
2554523  ec213  httt  monhoc_khoa

[2554524 rows x 3 columns]

In [129]:
# Lấy danh sách duy nhất các mã môn học
unique_mamh = interactions['mamh'].unique()

# Tạo ánh xạ từ mã môn học gốc sang giá trị số nguyên liên tiếp
mamh_mapping = {mamh: idx for idx, mamh in enumerate(unique_mamh)}

# Tạo DataFrame ánh xạ
mamh_df = pd.DataFrame(list(mamh_mapping.items()), columns=['org_id', 'remap_id'])

In [130]:
interactions

                                            mssv   mamh
0       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  it001
1       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ma003
2       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ma001
3       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ph001
4       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  en001
...                                          ...    ...
425776  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec229
425777  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec214
425778  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec208
425779  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  is334
425780  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec213

[425754 rows x 2 columns]

In [131]:
mamh_df

    org_id  remap_id
0    it001         0
1    ma003         1
2    ma001         2
3    ph001         3
4    en001         4
..     ...       ...
416  ds505       416
417  ds303       417
418  ds204       418
419  ds307       419
420  cs532       420

[421 rows x 2 columns]

In [132]:
# Lấy danh sách duy nhất các mssv
unique_mssv = interactions['mssv'].unique()

# Tạo ánh xạ từ mã sinh viên gốc sang giá trị số nguyên liên tiếp
mssv_mapping = {mssv: idx for idx, mssv in enumerate(unique_mssv)}

# Tạo DataFrame ánh xạ
mssv_df = pd.DataFrame(list(mssv_mapping.items()), columns=['org_id', 'remap_id'])

In [133]:
interactions

                                            mssv   mamh
0       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  it001
1       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ma003
2       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ma001
3       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  ph001
4       BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2  en001
...                                          ...    ...
425776  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec229
425777  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec214
425778  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec208
425779  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  is334
425780  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52  ec213

[425754 rows x 2 columns]

In [134]:
mssv_df

                                        org_id  remap_id
0     BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2         0
1     2420ED57XPvAibaEXe/Lh6v1XxTKJa6JLFRUPkLM         1
2     83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt         2
3     91F785ABXPvAibaEXe/lOccskaOiO5y4GbVvuRQu         3
4     007C275DXPvAibaEXe+TFgEDwYNnveOOmOYeYzF6         4
...                                        ...       ...
8261  7D7633B0XPvAibaEXe95IhrkYSGfcCQVGm4nFGyt      8261
8262  AB431338XPvAibaEXe8xMCTZ03/BexWzDCyWVsT3      8262
8263  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM      8263
8264  CB263C18XPvAibaEXe8xMCTZ03/Be8yk40QWdPiR      8264
8265  7CD9B404XPvAibaEXe8M4ltS8XjC9c/g97NvpP52      8265

[8266 rows x 2 columns]

In [135]:
mamh_df.to_csv('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Data_mapping/mp_mamh.txt',
               index=False,
               header=True,
               sep=' ')

In [136]:
mssv_df.to_csv('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Data_mapping/mp_mssv.txt',
               index=False,
               header=True,
               sep=' ')

In [137]:
monhoc_attribute['h'] = monhoc_attribute['h'].map(mamh_mapping)

In [138]:
# Lấy danh sách duy nhất các giá trị trong cột 'r'
unique_r_values = monhoc_attribute['r'].unique()

# Tạo ánh xạ từ giá trị gốc trong 'r' sang giá trị số nguyên liên tiếp
r_mapping = {r: idx for idx, r in enumerate(unique_r_values)}

# Tạo DataFrame ánh xạ
r_mapping_df = pd.DataFrame(list(r_mapping.items()), columns=['original_value', 'remap_id'])

# Thay thế các giá trị trong cột 'r' bằng giá trị ánh xạ
monhoc_attribute['r'] = monhoc_attribute['r'].map(r_mapping)

In [139]:
r_mapping_df

        original_value  remap_id
0          monhoc_diem         0
1         monhoc_hocky         1
2  monhoc_sinhvien_nam         2
3          monhoc_sotc         3
4     monhoc_trangthai         4
5          monhoc_khoa         5

In [140]:
monhoc_attribute

           h     t  r
0          0   7.5  0
1          1   5.0  0
2          2   5.0  0
3          3   8.0  0
4          4   6.5  0
...      ...   ... ..
2554519  349  httt  5
2554520  353  httt  5
2554521  348  httt  5
2554522  122  httt  5
2554523  304  httt  5

[2554524 rows x 3 columns]

In [141]:
# Lưu DataFrame ánh xạ
r_mapping_df.to_csv("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Data_mapping/r_mapping.txt",
                    index=False,
               header=True,
               sep=' ')

In [142]:
# Lấy danh sách duy nhất các giá trị trong cột 't'
unique_t_values = monhoc_attribute['t'].unique()

# Tạo ánh xạ từ giá trị gốc trong 't' sang giá trị số nguyên liên tiếp
t_mapping = {r: idx for idx, r in enumerate(unique_t_values)}

# Tạo DataFrame ánh xạ
t_mapping_df = pd.DataFrame(list(t_mapping.items()), columns=['original_value', 'remap_id'])

# Thay thế các giá trị trong cột 'r' bằng giá trị ánh xạ
monhoc_attribute['t'] = monhoc_attribute['t'].map(t_mapping)

In [143]:
monhoc_attribute

           h    t  r
0          0    0  0
1          1    1  0
2          2    1  0
3          3    2  0
4          4    3  0
...      ...  ... ..
2554519  349  103  5
2554520  353  103  5
2554521  348  103  5
2554522  122  103  5
2554523  304  103  5

[2554524 rows x 3 columns]

In [144]:
t_mapping_df.to_csv("/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Data_mapping/t_mapping.txt",
                    index=False,
                    header=True,
                    sep=' ')

In [145]:
monhoc_attribute.to_csv('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/MODEL_DATA/kg_final.txt',
                         header=False,
                         index=False,
                         sep=' ')

In [146]:
mamh_mapping = dict(zip(mamh_df['org_id'], mamh_df['remap_id']))
mssv_mapping = dict(zip(mssv_df['org_id'], mssv_df['remap_id']))

In [147]:
import polars as pl

interactions = pl.DataFrame(interactions)

In [148]:
# Mapping và group theo mssv
interactions = interactions.with_columns(
    pl.col('mssv').replace(mssv_mapping).cast(pl.Int32),
    pl.col('mamh').replace(mamh_mapping).cast(pl.Int32))\
    .group_by('mssv') \
    .agg(pl.col('mamh')) \
    .rename({'mamh': 'monhoc_order'}) \
    .sort('mssv')

In [149]:
interactions

shape: (8_266, 2)
┌──────┬───────────────────┐
│ mssv ┆ monhoc_order      │
│ ---  ┆ ---               │
│ i32  ┆ list[i32]         │
╞══════╪═══════════════════╡
│ 0    ┆ [0, 1, … 24]      │
│ 1    ┆ [25, 26, … 62]    │
│ 2    ┆ [0, 1, … 67]      │
│ 3    ┆ [25, 26, … 6]     │
│ 4    ┆ [0, 0, … 20]      │
│ …    ┆ …                 │
│ 8261 ┆ [1, 1, … 69]      │
│ 8262 ┆ [1, 134, … 137]   │
│ 8263 ┆ [1, 134, … 237]   │
│ 8264 ┆ [6, 10, … 353]    │
│ 8265 ┆ [228, 243, … 304] │
└──────┴───────────────────┘

In [150]:
import tqdm

# Mở file để ghi dữ liệu
train_file = open('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/MODEL_DATA/train.txt', 'w')
test_file = open('/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/MODEL_DATA/test.txt', 'w')

# Duyệt qua từng dòng dữ liệu trong sorted_interactions
for row in tqdm.tqdm(interactions.iter_rows(named=True)):
    user = row['mssv']
    courses = row['monhoc_order']

    # Kiểm tra nếu người dùng có hơn một khóa học
    if len(courses) > 1:
        # Chia dữ liệu thành train, val, test
        train_courses = ' '.join(map(str, courses[:-1]))
        test_course = courses[-1]

        train_file.write(f"{user} {train_courses}\n")
        test_file.write(f"{user} {test_course}\n")
    else:
        # Nếu chỉ có một khóa học, ghi vào test
        train_file.write(f"{user} {courses[0]}\n")
        test_file.write(f"{user} {courses[0]}\n")

# Đóng các file sau khi ghi
train_file.close()
test_file.close()

8266it [00:00, 82863.57it/s]

# USER info

In [151]:
data.columns

Index(['mssv', 'namsinh', 'gioitinh', 'noisinh', 'lopsh', 'khoa', 'hedt',
       'khoahoc', 'mamta', 'diem_thita', 'dien_tt', 'diem_tt', 'TEN_TRUONG',
       'xeploai', 'mamh', 'sotc', 'hocky', 'namhoc', 'diem_hp', 'trangthai',
       'tinhtrang', 'lydo', 'hockyxl', 'namhocxl', 'ngayqd', 'dtb_toankhoa',
       'dtb_tichluy', 'dtbhk', 'drl', 'ghichu', 'sinhvien_nam'],
      dtype='object')

In [152]:
user_info = data[['mssv', 'gioitinh', 'noisinh', 'namsinh', 'lopsh', 'khoa',\
                  'hedt', 'khoahoc', 'mamta', 'diem_thita', 'xeploai', 'sinhvien_nam']]

In [153]:
# Nhóm dữ liệu theo mssv với sinhvien_nam lớn nhất
idx = user_info.groupby('mssv')['sinhvien_nam'].idxmax()

# Lọc dựa trên loc
filtered_user_info = user_info.loc[idx]

# Copy dữ liệu
user_info = filtered_user_info.copy()

In [154]:
user_info['sinhvien_nam'].value_counts()

sinhvien_nam
4     3676
5     2607
6      587
1      440
2      375
3      326
7      178
8       57
9       18
10       2
Name: count, dtype: int64

In [155]:
user_info.columns

Index(['mssv', 'gioitinh', 'noisinh', 'namsinh', 'lopsh', 'khoa', 'hedt',
       'khoahoc', 'mamta', 'diem_thita', 'xeploai', 'sinhvien_nam'],
      dtype='object')

In [156]:
object_columns = user_info.select_dtypes(include='object').columns
object_columns

Index(['mssv', 'noisinh', 'lopsh', 'khoa', 'hedt', 'mamta', 'diem_thita',
       'xeploai'],
      dtype='object')

In [157]:
for col in object_columns:
  if col != 'mssv':
    # Lấy danh sách duy nhất các mssv
    unique = user_info[col].unique()

    # Tạo ánh xạ từ mã sinh viên gốc sang giá trị số nguyên liên tiếp
    mapping = {mssv: idx for idx, mssv in enumerate(unique)}

    # Tạo DataFrame ánh xạ
    df = pd.DataFrame(list(mapping.items()), columns=['org_id', 'remap_id'])

    user_info[col] = user_info[col].map(mapping)

    df.to_csv(f'/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/Data_mapping/{col}_mapping.txt',
                         header=True,
                         index=False,
                         sep=' ')

In [158]:
user_info.sample(3)

,mssv,gioitinh,noisinh,namsinh,lopsh,khoa,hedt,khoahoc,mamta,diem_thita,xeploai,sinhvien_nam
118160,D859AB46XPvAibaEXe/a3PM8AP2NgzCjTVS86e9w,1,15,1996,37,3,0,9,1,1,1,4
135074,CF42D7FCXPvAibaEXe8/V1eK05z04y7bZTFNUkDu,1,30,1997,15,0,0,10,1,1,1,6
170849,33DA2805XPvAibaEXe8+PBTAPRlCYxPBTc4huhPn,1,9,1997,1,1,0,10,1,1,2,5

In [159]:
user_info.columns

Index(['mssv', 'gioitinh', 'noisinh', 'namsinh', 'lopsh', 'khoa', 'hedt',
       'khoahoc', 'mamta', 'diem_thita', 'xeploai', 'sinhvien_nam'],
      dtype='object')

In [160]:
user_info.columns = ['org_id', 'gioitinh', 'noisinh', 'namsinh', 'lopsh', 'khoa',\
                  'hedt', 'khoahoc', 'mamta', 'diem_thita', 'xeploai', 'sinhvien_nam']

In [161]:
mssv_df = mssv_df.merge(user_info, on='org_id', how='left')

In [162]:
mssv_df.sample(3)

,org_id,remap_id,gioitinh,noisinh,namsinh,lopsh,khoa,hedt,khoahoc,mamta,diem_thita,xeploai,sinhvien_nam
7533,A910AEB0XPvAibaEXe+wnAHzeNC8YqkMB4kk2Qhq,7533,1,26,2001,54,1,1,14,176,0,0,1
5152,DDFCFEE0XPvAibaEXe9tVd6vhP62h1/MJMRnX5y0,5152,0,26,2000,78,0,0,13,2,2,0,4
4092,F056C507XPvAibaEXe9Fg4HjUy856fFEqIrYNnGE,4092,1,37,1999,6,2,0,12,64,3,0,4

In [163]:
mssv_df.to_csv(f'/content/drive/MyDrive/IS353 - Mạng xã hội - Nhóm 6/Đồ án môn học/Project/Data/Train_test_data/MODEL_DATA/user_list.txt',
                         header=True,
                         index=False,
                         sep=' ')

In [164]:
user_info.columns

Index(['org_id', 'gioitinh', 'noisinh', 'namsinh', 'lopsh', 'khoa', 'hedt',
       'khoahoc', 'mamta', 'diem_thita', 'xeploai', 'sinhvien_nam'],
      dtype='object')